Update patch set 1
Patch Set 1:

This fixes it so that the log dosen't fill up with

[2017-06-18 16:55:18,757] [HTTP-69] WARN  com.google.gerrit.server.change.Files$ListFiles : Cannot copy patch review flags
com.google.gerrit.server.patch.PatchListNotAvailableException: patch set 0 of change 2 not found

(which is a draft and pointless doing that too.)

Patch-set: 1
Reviewer: Paladox none <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>