Fix google's import
error TS4111: Property 'codespan' comes from an index signature, so it
must be accessed with ['codespan'].

and similar for image, code, and text.

Release-Notes: skip
Change-Id: Ic90dca97aac0e60be1a33b18ac215b93d90f2bab