SshDaemon: add unknown channel tracker as a regular event listener
The "unknown channel" event tracking was added here with
Ib41c94fc43aca7c4916d40128f03b643cee66d9a.

We are still having users who are having connections fail, and the
logs showing

  SshChannelNotFoundException: Received SSH_MSG_CHANNEL_WINDOW_ADJUST
    on unassigned channel 0 (last assigned=null)

After discussions in [1] I tried adding debuging to trace more of the
channel events.  I could not get these messages to appear; and after
quite a bit of head scratching trying to ensure I was actually
capturing debug messages at all, I noticed from the original commit
[2] that:

  An **experimental**
  `ChannelIdTrackingUnknownChannelReferenceHandler` is available in
  _sshd-contrib_ package ... In order to use it, the handler instance
  needs to be registered as **both** an
  `UnknownChannelReferenceHandler` and a `ChannelListener`.

I do not believe that we are currently registering the handler added
in Ib41c94fc43aca7c4916d40128f03b643cee66d9a as a regular channel
listener.

This explains why we are seeing the "last assigned=null"; the
channelInitialized() callback is not being run, so we never track the
opening of the channel.  Thus I think the work-around is ineffective
without this change.

I have tested this locally in OpenDev CI (see change [3]) and I see
the expected tracing messages with this change.

[1] https://github.com/apache/mina-sshd/issues/319
[2] https://github.com/apache/mina-sshd/commit/11b33dee37b5b9c71a40a8a98a42007e3687131e
[3] https://review.opendev.org/c/opendev/system-config/+/873214

Change-Id: I86048576b8023219a5e544ee7a539a98a73e7dda