Remove unused exception in ApprovalQueryBuilder
The AutoAnnotationProcessor fails while building Gerrit with Bazel with
the following error:

error: [UnusedException] This catch block catches an symbol and
re-throws another, but swallows the caught symbol rather than setting it
as a cause.

Using the exception in the catch block and removing the
@SuppressWarnings annotation to avoid this error.

Change-Id: I1dd0c0e0b8dbe01ecdf9ab056f9b6045cc5042f6