Fix IllegalArgumentException when running query with limit:0
Running the query:

  ssh -p 29418 user@review gerrit query status:open limit:0

Causes an exception:

  java.lang.IllegalArgumentException: numHits must be > 0;
  please use TotalHitCountCollector if you just need the total
  hit count

  at org.apache.lucene.search.TopFieldCollector.create(TopFieldCollector.java:1120)

And this results in the query returning "Internal server error".

Add a check to ensure that the limit is always > 0.

Change-Id: I92260c6d6431c7950909c8a8ffceada7e9f690a4