Fix compilation of unit test on Java 8
Transitive dependency is missing for mina-sshd in sshd_tests rule.
The error message in Java 8 is:

gerrit-sshd/src/test/java/com/google/gerrit/sshd/commands/ProjectConfigParamParserTest.java:41:
error: cannot access org.apache.sshd.server.Command
        cmd.parsePluginConfigValues(Collections.singletonList(in));
           ^
  class file for org.apache.sshd.server.Command not found

Change-Id: I5ca948bcd04b7a5ce7588810d1db151309ed39c4