GWT DevMode is dead; set up SuperDevMode
No debugging is possible on client side, for recent versions of major
browsers and major development platform combinations:

Firefox@Linux: GWT Developer Plugin only supports Firefox 3.0 - 26.0.
Chrome@Linux: GWT Developer Plugin no longer works with Chrome on Linux

The corresponding thread on dev ML [1] suggests to stay on older browser
versions, that's obviously a no go, and not only because of exploits of
known vulnerabilities.

That effectivily means, that no development of Gerrit is possible any more.
The only option is to set up: SuperDevMode.

Unfortunately that sucks too, thanks GWT depending on outdated version of
Jetty server 8.1 that collides with our version 9.1 and was stripped from
gwt-dev library during fetching from Maven Central:

  maven_jar(
    name = 'dev',
    id = 'com.google.gwt:gwt-dev:' + VERSION,
    [...]
    exclude = ['org/eclipse/jetty/*'],
  )

So we have two options:

1. downgrade jetty 9.1 to 8.1 match the version GWT is using.
2. patch GWT to use Jetty 9.1

This is the current CNFE during start of codeserver:

Compile completed in 21470 ms
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/nio/SelectChannelConnector
	at com.google.gwt.dev.codeserver.WebServer.start(WebServer.java:108)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:101)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:71)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:49)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.nio.SelectChannelConnector
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 4 more

[1] https://groups.google.com/forum/#!topic/google-web-toolkit/Ve32_oy0kAw

Change-Id: Ieff7190db6bc151eae1274105ccf828eaa652027