Update patch set 26
Patch Set 26:

i mean the download test

Error: expected undefined to be truthy
  Function.assert.isOk at /components/chai/chai.js:2236
          Context.test at gr-change-actions_test.html:1074

which is assert.ok(element.revisionActions.download);

Patch-set: 26
Reviewer: Paladox none <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>