Update patch set 1
Patch Set 1:

Looks like this broke test execution:

 gerrit $ bazel test //...
 ERROR: package contains errors: plugins/high-availability/tools/eclipse.
 ERROR: error loading package 'plugins/high-availability/tools/eclipse': Encountered error while reading extension file 'tools/commons.bzl': 
 no such package '@com_googlesource_gerrit_bazlets//tools': error loading package 'external': The repository named 
 'com_googlesource_gerrit_bazlets' could not be resolved.
 INFO: Elapsed time: 0.397s
 ERROR: Couldn't start the build. Unable to run tests.

Patch-set: 1
Reviewer: David Pursehouse <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>