Update patch set 1
Patch Set 1: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 3.8s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/change/Abandon.java:124: error: ')' expected
            Change c = db.changes().atomicUpdate(req.getChange().getId(),
                  ^
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/change/Abandon.java:124: error: illegal start of expression
            Change c = db.changes().atomicUpdate(req.getChange().getId(),
                     ^
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/change/Abandon.java:124: error: ';' expected
...

Patch-set: 1
Label: Verified=-1