Update patch set 1
Patch Set 1:

While

  buck build //:plugin-api-src

works,

  buck build //:plugin-api

fails with

  BUILDING //:plugin-api
  java.util.zip.ZipException: duplicate entry: com/google/gerrit/reviewdb/client/CurrentSchemaVersion$Key.class
        at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:215)
        at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
        at com.facebook.buck.java.JarDirectoryStep.copyZipEntriesToJar(JarDirectoryStep.java:213)
        at com.facebook.buck.java.JarDirectoryStep.createJarFile(JarDirectoryStep.java:162)
        at com.facebook.buck.java.JarDirectoryStep.execute(JarDirectoryStep.java:122)
        at com.facebook.buck.step.DefaultStepRunner.runStepInternal(DefaultStepRunner.java:79)
        at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:68)
        at com.facebook.buck.rules.AbstractCachingBuildRule.executeCommandsNowThatDepsAreBuilt(AbstractCachingBuildRule.java:338)
        at com.facebook.buck.rules.AbstractCachingBuildRule.buildOnceDepsAreBuilt(AbstractCachingBuildRule.java:267)
        at com.facebook.buck.rules.AbstractCachingBuildRule.access$000(AbstractCachingBuildRule.java:69)
        at com.facebook.buck.rules.AbstractCachingBuildRule$1.onSuccess(AbstractCachingBuildRule.java:176)
        at com.facebook.buck.rules.AbstractCachingBuildRule$1.onSuccess(AbstractCachingBuildRule.java:172)
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1149)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)
  BUILD FAILED: //:plugin-api failed on step "jar cf" with exit code 1

. Increasing verbosity does not help much [1].

Since I suck badly at Buck, is there an easy way to help Buck to
overcome this issue and get gerrit-pgm back into the plugin-api [2]?




[1] Running with -v 9999 shows that the last command before above's ZipException is

  jar cf buck-out/gen//plugin-api.jar  buck-out/gen/gerrit-httpd/lib__httpd__output/httpd.jar buck-out/gen/gerrit-antlr/lib__query_exception__output/query_exception.jar buck-out/gen/lib/jgit/jgit/org.eclipse.jgit-2.3.1.201302201838-r.211-g36144e1.jar buck-out/gen/lib/jgit/ewah/javaewah-0.5.6.jar buck-out/gen/lib/gson/gson-2.1.jar buck-out/gen/gerrit-patch-jgit/lib__server__output/server.jar buck-out/gen/lib/gwtorm/gwtorm-1.6.jar buck-out/gen/gerrit-reviewdb/lib__server__output/server.jar buck-out/gen/lib/guava/guava-14.0.jar buck-out/gen/lib/gwtjsonrpc/gwtjsonrpc-1.3.jar buck-out/gen/gerrit-prettify/lib__server__output/server.jar buck-out/gen/lib/jsr305/jsr305-1.3.9.jar buck-out/gen/gerrit-common/lib__server__output/server.jar buck-out/gen/gerrit-extension-api/lib__api__output/api.jar buck-out/gen/gerrit-gwtexpui/lib__linker_server__output/linker_server.jar buck-out/gen/gerrit-gwtexpui/lib__server__output/server.jar buck-out/gen/gerrit-server/lib__server__output/server.jar buck-out/gen/gerrit-antlr/query_parser.jar buck-out/gen/lib/antlr/java_runtime/antlr-runtime-3.2.jar buck-out/gen/gerrit-util-ssl/lib__ssl__output/ssl.jar buck-out/gen/lib/commons/codec/commons-codec-1.4.jar buck-out/gen/lib/commons/net/commons-net-2.2.jar buck-out/gen/lib/log/api/slf4j-api-1.6.1.jar buck-out/gen/gerrit-patch-commonsnet/lib__commons-net__output/commons-net.jar buck-out/gen/lib/guice/guice_library/guice-3.0.jar buck-out/gen/lib/guice/aopalliance/aopalliance-1.0.jar buck-out/gen/lib/guice/javax-inject/javax.inject-1.jar buck-out/gen/lib/guice/guice-assistedinject/guice-assistedinject-3.0.jar buck-out/gen/lib/args4j/args4j-2.0.16.jar buck-out/gen/gerrit-util-cli/lib__cli__output/cli.jar buck-out/gen/lib/commons/dbcp/commons-dbcp-1.4.jar buck-out/gen/lib/commons/pool/commons-pool-1.5.5.jar buck-out/gen/lib/commons/lang/commons-lang-2.5.jar buck-out/gen/lib/guice/guice-servlet/guice-servlet-3.0.jar buck-out/gen/lib/prolog/prolog-cafe/prologcafe-1.3.jar buck-out/gen/lib/automaton/automaton-1.11-8.jar buck-out/gen/lib/jsch/jsch-0.1.44-1.jar buck-out/gen/lib/juniversalchardet/juniversalchardet-1.0.3.jar buck-out/gen/lib/mime-util/mime-util-2.1.3.jar buck-out/gen/lib/ow2-asm/asm-4.0.jar buck-out/gen/lib/ow2-asm-tree/asm-tree-4.0.jar buck-out/gen/lib/ow2-asm-util/asm-util-4.0.jar buck-out/gen/lib/parboiled-core/parboiled-core-1.1.3.jar buck-out/gen/lib/pegdown/pegdown-1.1.0.jar buck-out/gen/lib/parboiled-java/parboiled-java-1.1.3.jar buck-out/gen/lib/ow2-asm-analysis/asm-analysis-4.0.jar buck-out/gen/lib/velocity/velocity-1.6.4.jar buck-out/gen/lib/commons/collections/commons-collections-3.2.1.jar buck-out/gen/lib/commons/oro/oro-2.0.8.jar buck-out/gen/lib/jgit/jgit-servlet/org.eclipse.jgit.http.server-2.3.1.201302201838-r.211-g36144e1.jar buck-out/gen/gerrit-pgm/lib__pgm__output/pgm.jar buck-out/gen/lib/h2/h2-1.3.168.jar buck-out/gen/gerrit-cache-h2/lib__cache-h2__output/cache-h2.jar buck-out/gen/lib/gwtorm/gwtorm-1.6-src.jar buck-out/gen/gerrit-reviewdb/lib__client__output/client.jar buck-out/gen/lib/lucene-analyzers-common/lucene-analyzers-common-4.3.0.jar buck-out/gen/lib/lucene-core/lucene-core-4.3.0.jar buck-out/gen/gerrit-lucene/lib__lucene__output/lucene.jar buck-out/gen/gerrit-openid/lib__openid__output/openid.jar buck-out/gen/lib/openid/consumer/openid4java-0.9.8.jar buck-out/gen/lib/commons/logging/commons-logging-1.1.1.jar buck-out/gen/lib/openid/httpclient/httpclient-4.1.jar buck-out/gen/lib/openid/httpcore/httpcore-4.1.jar buck-out/gen/lib/openid/nekohtml/nekohtml-1.9.10.jar buck-out/gen/lib/openid/xerces/xercesimpl-2.8.1.jar buck-out/gen/gerrit-server/common_rules.jar buck-out/gen/gerrit-sshd/lib__sshd__output/sshd.jar buck-out/gen/lib/log/log4j/log4j-1.2.16.jar buck-out/gen/lib/mina/core/mina-core-2.0.5.jar buck-out/gen/lib/mina/sshd/sshd-core-0.6.0.jar buck-out/gen/lib/jetty/server/jetty-server-8.1.7.v20120910.jar buck-out/gen/lib/jetty/continuation/jetty-continuation-8.1.7.v20120910.jar buck-out/gen/lib/jetty/http/jetty-http-8.1.7.v20120910.jar buck-out/gen/lib/jetty/io/jetty-io-8.1.7.v20120910.jar buck-out/gen/lib/jetty/util/jetty-util-8.1.7.v20120910.jar buck-out/gen/lib/jetty/servlet/jetty-servlet-8.1.7.v20120910.jar buck-out/gen/lib/jetty/security/jetty-security-8.1.7.v20120910.jar buck-out/gen/lib/servlet-api-3_0/tomcat-servlet-api-7.0.32.jar

Running that command by hand succeeds.

[2] Currently, we'd need gerrit-pgm in plugin-api when trying to get
hooks-its to work against 2.8-SNAPSHOT, as hooks-its provides init
steps. We can just add gerrit-pgm as explicit dependency to hooks-its
for now, but in the long run it would be great to get gerrit-pgm back in.

Patch-set: 1
Label: Verified=0