Update patch set 2
Patch Set 2:

Could it be the version of slf4j I have?  I have 1.6.1 and 1.7.7 in my cache but javac is invoking 1.6.1 according to the buck output.

Here's the full error:

114 /home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/change/DeleteReviewer.java:93: error: no suitable method found for debug(java.lang.String,com.google.gerrit.reviewdb.client.Account.Id,com.google.gerrit.reviewdb.client.Account.Id,com.google.gerrit.reviewdb.client.PatchSet.Id)
115           log.debug("User {} removed approval of {} on {}",
116              ^
117     method org.slf4j.Logger.debug(org.slf4j.Marker,java.lang.String,java.lang.Throwable) is not applicable
118       (actual and formal argument lists differ in length)
119     method org.slf4j.Logger.debug(org.slf4j.Marker,java.lang.String,java.lang.Object[]) is not applicable
120       (actual and formal argument lists differ in length)
121     method org.slf4j.Logger.debug(org.slf4j.Marker,java.lang.String,java.lang.Object,java.lang.Object) is not applicable
122       (actual argument java.lang.String cannot be converted to org.slf4j.Marker by method invocation conversion)
123     method org.slf4j.Logger.debug(org.slf4j.Marker,java.lang.String,java.lang.Object) is not applicable
124       (actual and formal argument lists differ in length)
125     method org.slf4j.Logger.debug(org.slf4j.Marker,java.lang.String) is not applicable
126       (actual and formal argument lists differ in length)
127     method org.slf4j.Logger.debug(java.lang.String,java.lang.Throwable) is not applicable
128       (actual and formal argument lists differ in length)
129     method org.slf4j.Logger.debug(java.lang.String,java.lang.Object[]) is not applicable
130       (actual and formal argument lists differ in length)
131     method org.slf4j.Logger.debug(java.lang.String,java.lang.Object,java.lang.Object) is not applicable
132       (actual and formal argument lists differ in length)
133     method org.slf4j.Logger.debug(java.lang.String,java.lang.Object) is not applicable
134       (actual and formal argument lists differ in length)
135     method org.slf4j.Logger.debug(java.lang.String) is not applicable
136       (actual and formal argument lists differ in length)

Patch-set: 2