Update patch set 4
Patch Set 4: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 4.1s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/change/Submit.java:403: error: method areChangesSubmittable in class com.google.gerrit.server.change.Submit cannot be applied to given types;
    String problems = areChangesSubmittable(changesByTopic, caller, force);
                      ^
  required: java.util.List<com.google.gerrit.server.query.change.ChangeData>,com.google.gerrit.server.IdentifiedUser
  found: java.util.List<com.google.gerrit.server.query.change.ChangeData>,com.google.gerrit.server.IdentifiedUser,boolean
  reason: actual and formal argument lists differ in length
Note: Some input files use unchecked or unsafe operations.
...

Patch-set: 4
Label: Verified=-1