Update patch set 5
Patch Set 5: Verified-1

This is actually breaking one test:
FAILURE testGetPossibleStatus: expected:<[DRAFT, MERGED, ABANDONED]> but was:<[SUBMITTED, DRAFT, MERGED, ABANDONED]>
java.lang.AssertionError: expected:<[DRAFT, MERGED, ABANDONED]> but was:<[SUBMITTED, DRAFT, MERGED, ABANDONED]>

Will rework the change to get the 's' status without necessarily reintroducing the enum value.

Patch-set: 5
Label: Verified=-1