Update patch set 7
Patch Set 7: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 3.6s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/git/MergeOp.java:853: error: ';' expected
        subOp.updateSubmoduleSubscriptions(destBranch)
                                                      ^
Errors: 1. Warnings: 0.
BUILD FAILED: //gerrit-server:server failed with exit code 1:
javac
[-] BUILDING...FINISHED 6.0s
:

Patch-set: 7
Label: Verified=-1