Update patch set 1
Patch Set 1: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 4.2s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/git/ReceiveCommits.java:2664: error: ';' expected
        publich String toString() {
                      ^
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/git/ReceiveCommits.java:2664: error: invalid method declaration; return type required
        publich String toString() {
                       ^
Errors: 2. Warnings: 0.
...

Patch-set: 1
Label: Verified=-1