Update patch set 5
Patch Set 5:

Tried again:

$ bazelisk test --config=remote //...
doesn't work for me, with the following error
ERROR: /home/jenkins/gerrit/polygerrit-ui/app/node_modules_licenses/BUILD:10:1 Compiling TypeScript (devmode) //tools/node_tools/node_modules_licenses:licenses-map failed (Exit 34). Note: Remote connection/protocol failed with: execution failed INVALID_ARGUMENT: Input tree has 84256 files, above the maximum of 70000

$ bazelisk test //...
works for me, all tests are passing

$ bazelisk build --config=remote release
works for me, Elapsed time: 104.713s

$ bazelisk build release
works for me, Elapsed time: 32.262s

--- * ---

Bottom line is:
- config=remote works only for building release, not for running tests
- when building release, config=remote takes 100s vs. 32s ... why is it almost 3x slower?

I guess the fact that this test is run from my laptop with a broadband connection and now from GCP to RBE is playing its role. I'm keen to repeat the test from GCP as soon as Han-Wen grants the service user the permission to access RBE.

The tests are failing though, because of "INVALID_ARGUMENT: Input tree has 84256 files, above the maximum of 70000". Possibly another permission setting to adjust?

Patch-set: 5
Reviewer: Gerrit User 1006192 <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>