Update patch set 1
Patch Set 1:

Um, what?

 ERROR: /home/jenkins/workspace/Gerrit-verifier-bazel/gerrit/javatests/com/google/gerrit/server/schema/BUILD:47:1: Building javatests/com/google/gerrit/server/schema/Schema_159_to_160_Test.jar (1 source file) failed (Exit 1)
 javatests/com/google/gerrit/server/schema/Schema_159_to_160_Test.java:57: error: [strict] Using type com.google.gerrit.server.schema.Schema_160 from an indirect dependency (TOOL_INFO: "//java/com/google/gerrit/server/schema"). See command below **
   @Inject private Schema_160 schema160;
                   ^
  ** Please add the following dependencies: 
   //java/com/google/gerrit/server/schema  to //javatests/com/google/gerrit/server/schema:Schema_159_to_160_Test 
  ** You can use the following buildozer command: 
 buildozer 'add deps //java/com/google/gerrit/server/schema ' //javatests/com/google/gerrit/server/schema:Schema_159_to_160_Test 

That's complaining about a missing dep on //java/com/google/gerrit/server/schema. When I add one, I get this error:

 ERROR: Analysis of target '//javatests/com/google/gerrit/server/schema:Schema_150_to_151_Test' failed; build aborted: no such package 'java/com/google/gerrit/server/schema': BUILD file not found on package path

Which is reasonable, because that package does not exist:

 $ for d in $(find j* -type d -name schema); do ls $d/BUILD; done
 ls: cannot access 'java/com/google/gerrit/server/schema/BUILD': No such file or directory
 javatests/com/google/gerrit/server/schema/BUILD

So it seems like a bug that Bazel is suggesting it. I am guessing based on the fact that tests pass on my machine that this was fixed in a recent version of Bazel.

Patch-set: 1
Reviewer: Dave Borowitz <1010008@173816e5-2b9a-37c3-8a2e-48639d4f1153>