Update patch set 1
Patch Set 1: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 4.1s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/change/Submit.java:31: error: package com.google.gerrit.client.changes does not exist
import com.google.gerrit.client.changes.Util;
                                       ^
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/change/Submit.java:31: error: package com.google.gerrit.client.changes does not exist
import com.google.gerrit.client.changes.Util;
                                       ^
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/change/Submit.java:258: error: package Util does not exist
...

Patch-set: 1
Label: Verified=-1