Align httpcore and httpcore-nio versions
Since the introduction of Change-Id: I1cd6048 the httpcore-nio
and httpcore have been misaligned creating inconsistencies between
methods exposed by httpcore and those assumed by httpcore-nio.

One example of the inconsistency is the assumption by httpcore-nio
that the org.apache.http.ConnectionClosedException has a constructor
without parameters whilst the httpcore version does not expose
such method, causing java.lang.NoSuchMethodError(s).

Align the httpcore and httpcore-nio version to resolve the
inconsistency between the two by exporting HTTPCORE_VERS
in nongoogle.bzl that can be reused in WORKSPACE for aligning
the two artifacts to the same version and keep them in sync from now on.

Updates in nongoogle.bzl of the HTTPCORE_VERS could in theory be
merged without a LC+1 but that would never go through because the exact
version of the httpcore artifact is checked with the SHA1 that can
be only found in WORKSPACE and therefore would always require a LC+1
for being merged.

Bug: Issue 15186
Change-Id: I8b49b41dae9fc10af1e37927e256cdf645695372