Fix focus to commit message
After clicking edit button, editable-content tried to put focus into
textarea. However iron-autogrow-textarea was not yet rendered so
it throw js error:
Error: selector 'iron-autogrow-textarea' did not match anything'

Google-Bug-Id: b/228800894
Release-Notes: skip
Change-Id: I51a48f84f750798d6a93a00ca765b308341b7517
(cherry picked from commit 43d22deb14e3d25b67166e44b3f7a033d6c1ff27)