Revert "Simplify how AppContext is created."
This reverts commit ace0b336a15646f15d2d69f7e1b1105cb2263aab.

Reason for revert: Broke building gerrit.

You can see the breakage at [0].

```
polygerrit-ui/app/embed/gr-diff-app-context-init.ts(11,29): error TS2307: Cannot find module '../test/mocks/gr-rest-api_mock' or its corresponding type declarations.
```

[0] https://gerrit-ci.gerritforge.com/job/Gerrit-bazel-master/1683/console

Release-Notes:skip
Change-Id: I26b660b16771f654b6a200feafee01cff183c075