Add handling of not-logged-in and error states
Screenshots
Not logged in: https://imgur.com/a/G28GOpA
Error: https://imgur.com/a/kFumBt1
Loading: https://imgur.com/a/gqHDuvp

Change-Id: I701a2fbdebca8d5b4adc437554b49597c8cc166a
(cherry picked from commit 6a293fa932dbae7dfb5f7031d8c92514aa119f4a)