Update patch set 2
Patch Set 2: Code-Review-1 Verified-1

Compilation fails.
 
 /Users/david/git/gerrit/gerrit-server/src/test/java/com/google/gerrit/server/change/CommentsTest.java:367: error: cannot access org.hamcrest.Matcher
     exception.expect(ResourceNotFoundException.class);
              ^
   class file for org.hamcrest.Matcher not found
 Errors: 1. Warnings: 0.

Patch-set: 2
Label: Code-Review=-1
Label: Verified=-1