Guard repository reference counting internals
The I3037064388 change introduced the repository reference counting
check in integration tests. It also uses the reference counting
mechanism in Gerrit test server called in tests. It seems that in
certain cases the reference counting clear (that is called after each
TC) is called before the Gerrit test server is stopped. When that
happens any operation on reference counting internal may result in NPE
e.g.:

SEVERE: Error while getting full commit message for change 1 [CONTEXT PLUGIN="gerrit" ]
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "this.decrementCallersStacks" is null
  at com.google.gerrit.testing.GitRepositoryReferenceCountingManager$RepositoryTracking.close(GitRepositoryReferenceCountingManager.java:119)
  at com.google.gerrit.server.query.change.ChangeData.loadCommitData(ChangeData.java:919)
  at com.google.gerrit.server.query.change.ChangeData.commitMessage(ChangeData.java:865)
  at com.google.gerrit.server.events.EventFactory.addCommitMessage(EventFactory.java:355)
  ...

Changes:
* ensure that any operation on the reference counting is NPE protected

* when Repository.clear is called during
  `assertThatAllRepositoriesAreClosed` then false negative might be
  reported e.g.:

P.S. Hints to resolve the issue:
     See below the tracking information of when the Repository was created,
     referenced and closed throughout the test. Look carefully at the
     open/close or incrementOpen/close pairs for all the AutoCloseable
     objects (either Repository or one of its wrappers, like
     RepoView or RepoRefCache) that is not managed properly inside a
     try-with-resource enclosure.

See below more details about the Repository objects created / opened and not closed.
------------

  but without any repository being mentioned in the list as assertion
  check competes with `RepostoryTracking.close` function on access to
  `openRepositories` leading to false negative errors; ensure that
  these two functions are synchronized

* having both assertion check and `RepostoryTracking.close` synchronized
  means that every now and then assertion will be checked on closed
  repository that is waiting on `openRepositories` access to remove
  itself failing with another false negative e.g.:

JGit Repository object com.google.gerrit.acceptance.ssh.StreamEventsIT_draftCommentRefsDeletionShowInStreamEventsUponPublishingdefault_project
was opened 1 time(s) but closed only 1 time(s), leaving a reference counting of 0 instance leaked
------------
  opened from com.google.gerrit.server.query.change.ChangeData.loadCommitData(ChangeData.java:911)
              called by com.google.gerrit.server.query.change.ChangeData.commitMessage(ChangeData.java:865)
              called by com.google.gerrit.server.events.EventFactory.addCommitMessage(EventFactory.java:355)
              called by com.google.gerrit.server.events.EventFactory.asChangeAttribute(EventFactory.java:153)
              called by com.google.gerrit.server.events.StreamEventsApiListener.lambda$changeAttributeSupplier$0(StreamEventsApiListener.java:197)
  closed from com.google.gerrit.server.query.change.ChangeData.loadCommitData(ChangeData.java:919)
              called by com.google.gerrit.server.query.change.ChangeData.commitMessage(ChangeData.java:865)
              called by com.google.gerrit.server.events.EventFactory.addCommitMessage(EventFactory.java:355)
              called by com.google.gerrit.server.events.EventFactory.asChangeAttribute(EventFactory.java:153)
              called by com.google.gerrit.server.events.StreamEventsApiListener.lambda$changeAttributeSupplier$0(StreamEventsApiListener.java:197)

  ensure that fail is raised only for those reposities that have
  `referenceCounter > 0` to avoid this kind of false negative results

Release-Notes: skip
Change-Id: If77805574f4becb6ec3986ab906c0efa782198f1