Bazel: Include eclipse-out directory in .bazelignore
Since [1] Bazel added support for .bazelignore, allowing to specify
directories that should be ignored. This allows us to remove the hacks
during .classpath generation in tools/eclips/project.py and just ignore
eclipse-out directory entirely.

Test Plan:

1. Generate .classpath project with:
  $ tools/eclipse/project.py

2. Re-build the gerrit project from the Eclipse IDE
3. Confirm that BUILD files are now included in eclipse-out directory:
  $ find eclipse-out -name BUILD | wc -l
  122

4. Confirm that Bazel doesn't find anything to build in eclipse-out
package:

  $ bazel build eclipse-out/...
  ERROR: Skipping 'eclipse-out/...': no targets found beneath \
  'eclipse-out'

[1] https://github.com/bazelbuild/bazel/issues/4888

Change-Id: I8dfd9b5701dfcc85fd51f626af448d0306b02857