Update patch set 21
Patch Set 21:

I'm guessing that this failure when generating the eclipse project with sources is related to this change?

$ ~/git/gerrit/tools/eclipse/project.py --src
Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 3.0s [100%]
Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 0.9s
[2016-02-15 11:02:08.178][error][command:a5c5e9ea-f186-4032-8beb-e3f5950e0f76][tid:25][com.facebook.buck.cli.Main] Uncaught exception from thread Thread[Build-6,5,Build]
com.facebook.buck.util.HumanReadableException: No rule found when resolving target //:junit__download_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:264)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:1)
	at com.facebook.buck.parser.OptimisticLoadingCache.get(OptimisticLoadingCache.java:61)
	at com.facebook.buck.parser.DaemonicParserState.getTargetNode(DaemonicParserState.java:242)
	at com.facebook.buck.parser.PerBuildState.getTargetNode(PerBuildState.java:212)
	at com.facebook.buck.parser.PerBuildState$BuildTargetParserWorker.run(PerBuildState.java:439)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.facebook.buck.parser.NoSuchBuildTargetException: No rule found when resolving target //:junit__download_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.NoSuchBuildTargetException.createForMissingBuildRule(NoSuchBuildTargetException.java:49)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:265)
	... 8 more

[2016-02-15 11:02:08.179][error][command:a5c5e9ea-f186-4032-8beb-e3f5950e0f76][tid:24][com.facebook.buck.cli.Main] Uncaught exception from thread Thread[Build-5,5,Build]
com.facebook.buck.util.HumanReadableException: No rule found when resolving target //:jgit-archive__download_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:264)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:1)
	at com.facebook.buck.parser.OptimisticLoadingCache.get(OptimisticLoadingCache.java:61)
	at com.facebook.buck.parser.DaemonicParserState.getTargetNode(DaemonicParserState.java:242)
	at com.facebook.buck.parser.PerBuildState.getTargetNode(PerBuildState.java:212)
	at com.facebook.buck.parser.PerBuildState$BuildTargetParserWorker.run(PerBuildState.java:439)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.facebook.buck.parser.NoSuchBuildTargetException: No rule found when resolving target //:jgit-archive__download_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.NoSuchBuildTargetException.createForMissingBuildRule(NoSuchBuildTargetException.java:49)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:265)
	... 8 more

[2016-02-15 11:02:08.179][error][command:a5c5e9ea-f186-4032-8beb-e3f5950e0f76][tid:21][com.facebook.buck.cli.Main] Uncaught exception from thread Thread[Build-2,5,Build]
com.facebook.buck.util.HumanReadableException: No rule found when resolving target //:jgit__download_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:264)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:1)
	at com.facebook.buck.parser.OptimisticLoadingCache.get(OptimisticLoadingCache.java:61)
	at com.facebook.buck.parser.DaemonicParserState.getTargetNode(DaemonicParserState.java:242)
	at com.facebook.buck.parser.PerBuildState.getTargetNode(PerBuildState.java:212)
	at com.facebook.buck.parser.PerBuildState$BuildTargetParserWorker.run(PerBuildState.java:439)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.facebook.buck.parser.NoSuchBuildTargetException: No rule found when resolving target //:jgit__download_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.NoSuchBuildTargetException.createForMissingBuildRule(NoSuchBuildTargetException.java:49)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:265)
	... 8 more

[2016-02-15 11:02:08.179][error][command:a5c5e9ea-f186-4032-8beb-e3f5950e0f76][tid:23][com.facebook.buck.cli.Main] Uncaught exception from thread Thread[Build-4,5,Build]
com.facebook.buck.util.HumanReadableException: No rule found when resolving target //:jgit-servlet_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:264)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:1)
	at com.facebook.buck.parser.OptimisticLoadingCache.get(OptimisticLoadingCache.java:61)
	at com.facebook.buck.parser.DaemonicParserState.getTargetNode(DaemonicParserState.java:242)
	at com.facebook.buck.parser.PerBuildState.getTargetNode(PerBuildState.java:212)
	at com.facebook.buck.parser.PerBuildState$BuildTargetParserWorker.run(PerBuildState.java:439)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.facebook.buck.parser.NoSuchBuildTargetException: No rule found when resolving target //:jgit-servlet_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.NoSuchBuildTargetException.createForMissingBuildRule(NoSuchBuildTargetException.java:49)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:265)
	... 8 more

[2016-02-15 11:02:08.179][error][command:a5c5e9ea-f186-4032-8beb-e3f5950e0f76][tid:30][com.facebook.buck.cli.Main] Uncaught exception from thread Thread[Build-11,5,Build]
com.facebook.buck.util.HumanReadableException: No rule found when resolving target //:jgit-archive_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:264)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:1)
	at com.facebook.buck.parser.OptimisticLoadingCache.get(OptimisticLoadingCache.java:61)
	at com.facebook.buck.parser.DaemonicParserState.getTargetNode(DaemonicParserState.java:242)
	at com.facebook.buck.parser.PerBuildState.getTargetNode(PerBuildState.java:212)
	at com.facebook.buck.parser.PerBuildState$BuildTargetParserWorker.run(PerBuildState.java:439)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.facebook.buck.parser.NoSuchBuildTargetException: No rule found when resolving target //:jgit-archive_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.NoSuchBuildTargetException.createForMissingBuildRule(NoSuchBuildTargetException.java:49)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:265)
	... 8 more

[2016-02-15 11:02:08.179][error][command:a5c5e9ea-f186-4032-8beb-e3f5950e0f76][tid:22][com.facebook.buck.cli.Main] Uncaught exception from thread Thread[Build-3,5,Build]
com.facebook.buck.util.HumanReadableException: No rule found when resolving target //:jgit_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:264)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:1)
	at com.facebook.buck.parser.OptimisticLoadingCache.get(OptimisticLoadingCache.java:61)
	at com.facebook.buck.parser.DaemonicParserState.getTargetNode(DaemonicParserState.java:242)
	at com.facebook.buck.parser.PerBuildState.getTargetNode(PerBuildState.java:212)
	at com.facebook.buck.parser.PerBuildState$BuildTargetParserWorker.run(PerBuildState.java:439)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.facebook.buck.parser.NoSuchBuildTargetException: No rule found when resolving target //:jgit_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.NoSuchBuildTargetException.createForMissingBuildRule(NoSuchBuildTargetException.java:49)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:265)
	... 8 more

[2016-02-15 11:02:08.179][error][command:a5c5e9ea-f186-4032-8beb-e3f5950e0f76][tid:26][com.facebook.buck.cli.Main] Uncaught exception from thread Thread[Build-7,5,Build]
com.facebook.buck.util.HumanReadableException: No rule found when resolving target //:ewah__download_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:264)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:1)
	at com.facebook.buck.parser.OptimisticLoadingCache.get(OptimisticLoadingCache.java:61)
	at com.facebook.buck.parser.DaemonicParserState.getTargetNode(DaemonicParserState.java:242)
	at com.facebook.buck.parser.PerBuildState.getTargetNode(PerBuildState.java:212)
	at com.facebook.buck.parser.PerBuildState$BuildTargetParserWorker.run(PerBuildState.java:439)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.facebook.buck.parser.NoSuchBuildTargetException: No rule found when resolving target //:ewah__download_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.NoSuchBuildTargetException.createForMissingBuildRule(NoSuchBuildTargetException.java:49)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:265)
	... 8 more

[2016-02-15 11:02:08.179][error][command:a5c5e9ea-f186-4032-8beb-e3f5950e0f76][tid:29][com.facebook.buck.cli.Main] Uncaught exception from thread Thread[Build-10,5,Build]
com.facebook.buck.util.HumanReadableException: No rule found when resolving target //:junit_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:264)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:1)
	at com.facebook.buck.parser.OptimisticLoadingCache.get(OptimisticLoadingCache.java:61)
	at com.facebook.buck.parser.DaemonicParserState.getTargetNode(DaemonicParserState.java:242)
	at com.facebook.buck.parser.PerBuildState.getTargetNode(PerBuildState.java:212)
	at com.facebook.buck.parser.PerBuildState$BuildTargetParserWorker.run(PerBuildState.java:439)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.facebook.buck.parser.NoSuchBuildTargetException: No rule found when resolving target //:junit_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.NoSuchBuildTargetException.createForMissingBuildRule(NoSuchBuildTargetException.java:49)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:265)
	... 8 more

[2016-02-15 11:02:08.178][error][command:a5c5e9ea-f186-4032-8beb-e3f5950e0f76][tid:33][com.facebook.buck.cli.Main] Uncaught exception from thread Thread[Build-14,5,Build]
com.facebook.buck.util.HumanReadableException: No rule found when resolving target //:ewah_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:264)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:1)
	at com.facebook.buck.parser.OptimisticLoadingCache.get(OptimisticLoadingCache.java:61)
	at com.facebook.buck.parser.DaemonicParserState.getTargetNode(DaemonicParserState.java:242)
	at com.facebook.buck.parser.PerBuildState.getTargetNode(PerBuildState.java:212)
	at com.facebook.buck.parser.PerBuildState$BuildTargetParserWorker.run(PerBuildState.java:439)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.facebook.buck.parser.NoSuchBuildTargetException: No rule found when resolving target //:ewah_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.NoSuchBuildTargetException.createForMissingBuildRule(NoSuchBuildTargetException.java:49)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:265)
	... 8 more

[2016-02-15 11:02:08.178][error][command:a5c5e9ea-f186-4032-8beb-e3f5950e0f76][tid:31][com.facebook.buck.cli.Main] Uncaught exception from thread Thread[Build-12,5,Build]
com.facebook.buck.util.HumanReadableException: No rule found when resolving target //:jgit-servlet__download_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:264)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:1)
	at com.facebook.buck.parser.OptimisticLoadingCache.get(OptimisticLoadingCache.java:61)
	at com.facebook.buck.parser.DaemonicParserState.getTargetNode(DaemonicParserState.java:242)
	at com.facebook.buck.parser.PerBuildState.getTargetNode(PerBuildState.java:212)
	at com.facebook.buck.parser.PerBuildState$BuildTargetParserWorker.run(PerBuildState.java:439)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.facebook.buck.parser.NoSuchBuildTargetException: No rule found when resolving target //:jgit-servlet__download_src in build file ///BUCK
Defined in file: /usr/local/google/home/ekempin/git/gerrit/BUCK
	at com.facebook.buck.parser.NoSuchBuildTargetException.createForMissingBuildRule(NoSuchBuildTargetException.java:49)
	at com.facebook.buck.parser.DaemonicParserState$4.call(DaemonicParserState.java:265)
	... 8 more

Patch-set: 21