Fix NullPointerException in PRED_uploader_1 when patch set is missing
When the current patch set was missing the exception was:

Exception calling :(user,submit_filter) on change 12345 of MyProject
com.google.gerrit.server.project.RuleEvalException: Exception calling :(user,submit_filter) on change 12345 of MyProject
        at com.google.gerrit.server.project.SubmitRuleEvaluator.runSubmitFilters(SubmitRuleEvaluator.java:591)
        at com.google.gerrit.server.project.SubmitRuleEvaluator.evaluateImpl(SubmitRuleEvaluator.java:506)
        at com.google.gerrit.server.project.SubmitRuleEvaluator.evaluate(SubmitRuleEvaluator.java:237)
        at com.google.gerrit.server.query.change.ChangeData.submitRecords(ChangeData.java:1023)
        at com.google.gerrit.server.change.ChangeJson.submitRecords(ChangeJson.java:581)
        at com.google.gerrit.server.change.ChangeJson.initLabels(ChangeJson.java:634)
        ...

Caused by: java.lang.NullPointerException
        at gerrit.PRED_uploader_1.exec(PRED_uploader_1.java:42)
        at com.googlecode.prolog_cafe.lang.PrologControl.executePredicate(PrologControl.java:191)
        at com.googlecode.prolog_cafe.lang.BufferingPrologControl.run(BufferingPrologControl.java:147)
        at com.googlecode.prolog_cafe.lang.BufferingPrologControl.once(BufferingPrologControl.java:84)
        at com.google.gerrit.server.project.SubmitRuleEvaluator.runSubmitFilters(SubmitRuleEvaluator.java:583)
        ... 113 more

Change-Id: Ica7903edefa61f52bafd78401496a6ae8e1f3a52
Signed-off-by: Edwin Kempin <ekempin@google.com>