ChangeEditApiImpl: explicitly assign return value to an unused variable
This is to fix the error prone error.

error: [CheckReturnValue] The result of `apply(...)` must be used
modifyIdentity.apply(changeResource, input); ^ If you really don't want
to use the result, then assign it to a variable: `var unused = ...`.

If callers of `apply(...)` shouldn't be required to use its result, then
annotate it with `@CanIgnoreReturnValue`.

Release-Notes: skip
Change-Id: Ica2c018d1dc90e79024481d195022ac114d87509