Update patch set 14
Patch Set 14:

> Doesn't work for me

Have you checked the CI log?

  ERROR: /home/jenkins/.cache/bazel/_bazel_jenkins/3239551e333dc09ba2b5ef07ff4549b6/external/jgit/lib/BUILD:216:1: no such package '@servlet-api-3_1//jar':
  The repository '@servlet-api-3_1' could not be resolved and referenced by '@jgit//lib:servlet-api'

That's because JGit build tool chain must be adapted after the rename of @servlet-api-3_1 to @servlet-api in Gerrit core (the same must happen in JGit as well). See this change for more details: [1]. 

> and the solution relies on GitHub, which would bring more instability to our build :-(

It is not the problem of that change, as can be seen in the comment, but Eclipse Organization is not able to upgrade Gerrit version. They are still on 2.14.6, and git archive command is broken in JGit version. Having said that, this shouldn't be a problem, because:

* a) This artifact is cached: so that every tarball will be downloaded only once and never again
* b) If GitHub is down, you will not be able to build Gerrit already today, just search for GH in WORKSPACE.

* [1] https://gerrit-review.googlesource.com/c/gerrit/+/238496

Patch-set: 14
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>