Update patch set 3
Patch Set 3:

This broke the build for me (detected by git bisect):

$ bazel build gerrit
ERROR: /usr/local/google/home/ekempin/git/gerrit/lib/js/BUILD:27:1: in js_component rule //lib/js:highlightjs: 
Traceback (most recent call last):
	File "/usr/local/google/home/ekempin/git/gerrit/lib/js/BUILD", line 27
		js_component(name = 'highlightjs')
	File "/usr/local/google/home/ekempin/git/gerrit/tools/bzl/js.bzl", line 170, in _js_component
		ctx.actions
object of type 'ctx' has no field 'actions'
ERROR: Analysis of target '//:gerrit' failed; build aborted
INFO: Elapsed time: 1.240s
FAILED: Build did NOT complete successfully (116 packages loaded)

Anything I need to update?

Patch-set: 3
CC: Edwin Kempin <1003935@173816e5-2b9a-37c3-8a2e-48639d4f1153>