Update patch set 2
Patch Set 2:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > > Patch Set 1:
> > > 
> > > This fails when the owners plugin is included:
> > > 
> > >   ERROR: /Users/dpursehouse/git/gerrit/plugins/find-owners/BUILD:24:1: Building plugins/find-owners/libfind-owners-prolog-rules.jar (1 source jar) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed (Exit 1)
> > >   /find_owners/PRED_owner_approval_label_1.java:8: error: [WildcardImport] Wildcard imports, static or otherwise, should not be used
> > >   import com.googlecode.prolog_cafe.builtin.*;
> > >   ^
> > >       (see https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports) 
> > >   Target //:release failed to build
> > >   Use --verbose_failures to see the command lines of failed build steps.
> > 
> > s/owner/find-owners
> 
> But this is not a core plugin.

It is not, but google uses it, and thus we need to make sure we don't break it.

See Ia1e7faa1de5381ea139ae6fedf8d12356670e62a

Patch-set: 2
Reviewer: Gerrit User 1011123 <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>