Update patch set 2
Patch Set 2: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUILD FILES...FINISHED 2.2s
/home/deckard/workspace/gerrit/gerrit-sshd/src/main/java/com/google/gerrit/sshd/commands/SetAccountCommand.java:266: error: unreported exception com.google.gerrit.extensions.restapi.AuthException; must be caught or declared to be thrown
    deleteSshKey.apply(
                      ^
Note: /home/deckard/workspace/gerrit/gerrit-sshd/src/main/java/com/google/gerrit/sshd/DispatchCommandProvider.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Errors: 1. Warnings: 0.
BUILD FAILED: //gerrit-sshd:sshd failed with exit code 1:
...

Patch-set: 2
Label: Verified=-1