Update patch set 10
Patch Set 10:

> Patch Set 9:
> 
> It fails again with:
> 
>  error: cannot access CheckReturnValue

My bad. I've only tested `bazel build java/com/google/gerrit/common:server`, but it is failing in GWT's common:client library. We could exclude this source form GWT client part, but I decided to move to another package, dedicated to logging: c.g.g.util.logging. Done.

Patch-set: 10
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>