Don't use transactions for GwtormChangeBundleReader
As noted in the TODO, this is a temporary measure until we can figure
out a better way. In the meantime, the old behavior is preventing
manual testing of the NoteDb migration on PostgreSQL, causing lots of
SQLExceptions:

com.google.gwtorm.server.OrmException: Cannot set auto commit mode
        at com.google.gwtorm.jdbc.JdbcSchema.rollback(JdbcSchema.java:95)
        at com.google.gerrit.reviewdb.server.ReviewDbWrapper.rollback(ReviewDbWrapper.java:46)
        at com.google.gerrit.server.notedb.GwtormChangeBundleReader.fromReviewDb(GwtormChangeBundleReader.java:46)
        at com.google.gerrit.server.notedb.rebuild.ChangeRebuilderImpl.rebuild(ChangeRebuilderImpl.java:189)
        at com.google.gerrit.server.notedb.rebuild.ChangeRebuilderImpl.rebuild(ChangeRebuilderImpl.java:170)
        at com.google.gerrit.server.notedb.rebuild.NoteDbMigrator.rebuildProject(NoteDbMigrator.java:706)
        at com.google.gerrit.server.notedb.rebuild.NoteDbMigrator.lambda$rebuild$5(NoteDbMigrator.java:642)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:295)
        at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:435)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: Cannot commit when autoCommit is enabled.
        at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:795)
        at org.postgresql.jdbc.PgConnection.setAutoCommit(PgConnection.java:760)
        at org.apache.commons.dbcp.DelegatingConnection.setAutoCommit(DelegatingConnection.java:371)
        at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.setAutoCommit(PoolingDataSource.java:328)
        at com.google.gwtorm.jdbc.JdbcSchema.rollback(JdbcSchema.java:93)
        ... 17 more

Change-Id: I4cd280284b57b24c37ffc074c05424de7865dda0