Update patch set 8
Patch Set 8: Verified-1

I installed that version, configured the replication plugin to be mandatory and then touched the delete-project plugin. This causes the following error in the error_log:

[2019-05-14 12:43:53,170] [PluginScanner] INFO  com.google.gerrit.server.plugins.PluginLoader : Reloading plugin delete-project
[2019-05-14 12:43:53,237] [PluginScanner] INFO  com.google.gerrit.server.plugins.PluginLoader : Unloading plugin delete-project, version v3.0.0-rc3-2-ga4b777a
[2019-05-14 12:43:53,238] [PluginScanner] INFO  com.google.gerrit.server.plugins.PluginLoader : Reloaded plugin delete-project, version v3.0.0-rc3-2-ga4b777a
[2019-05-14 12:43:53,240] [PluginScanner] ERROR com.google.gerrit.pgm.Daemon : Thread PluginScanner threw exception
com.google.gerrit.server.plugins.MissingMandatoryPluginsException: Cannot find or load the following mandatory plugins: [replication]
	at com.google.gerrit.server.plugins.PluginLoader.rescan(PluginLoader.java:439)
	at com.google.gerrit.server.plugins.PluginScannerThread.run(PluginScannerThread.java:42)

Patch-set: 8
Reviewer: Gerrit User 1004034 <1004034@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1