Fix the warning to not appear while loading a plugin
Prior to this change, warning [1] was observed in the error logs for a
plugin which has exclusively bindings for SshExecuteCommandInterceptor/
SshCreateCommandInterceptor in the ssh module as outlined in the
documentation provided in references [2] and [3]. Fix this by extending
the warning to address the cases mentioned above.

[1]  WARN  com.google.gerrit.sshd.SshPluginStarterCallback : Plugin
<plugin_name> did not define its top-level command nor any DynamicOptions
com.google.inject.ConfigurationException: Guice configuration errors:

[Guice/MissingImplementation]: No implementation for Command annotated
with @CommandName("<plugin_name>") was bound.

[2] https://gerrit-review.googlesource.com/Documentation/dev-plugins.html#ssh-command-creation-interception

[3] https://gerrit-review.googlesource.com/Documentation/dev-plugins.html#ssh-command-execution-interception

Change-Id: I80a2de37f2d38766b66315359779f7678f7062db
Release-Notes: skip
Google-Bug-Id: b/302408544