Update patch set 11
Patch Set 11: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Watchman not found, please install when using buckd.
See https://github.com/facebook/watchman for details.
[-] PARSING BUILD FILES...FINISHED 5.7s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/securestore/SecureStoreProvider.java:58: error: method scan in class com.google.gerrit.server.plugins.JarScanner cannot be applied to given types;
        JarScanner.scan(pluginFile, pluginName, Export.class);
                  ^
  required: java.util.jar.JarFile,java.lang.String,java.lang.Iterable<java.lang.Class<? extends java.lang.annotation.Annotation>>
  found: java.io.File,java.lang.String,java.lang.Class<com.google.gerrit.extensions.annotations.Export>
  reason: actual argument java.io.File cannot be converted to java.util.jar.JarFile by method invocation conversion
...

Patch-set: 11
Label: Verified=-1