Bazel: Fix vulcanize rule
bazel test //... was failing with the following errir. Specify allow
file instead of listing extension subset:

  attr.label_list(allow_files=True)

ERROR: /home/davido/projects/gerrit/polygerrit-ui/app/BUILD:32:1: in
srcs attribute of _vulcanize_rule rule //polygerrit-ui/app:gr-app: file
'//polygerrit-ui/app:bower_components/accessibility-developer-tools/.bower.json'
is misplaced here (expected .js, .html, .txt, .css or .ico). Since this
rule was created by the macro 'vulcanize', the error might have been
caused by the macro implementation in
/home/davido/projects/gerrit/polygerrit-ui/app/BUILD:32:1.

Change-Id: I797980fea6dbbbf00e3e34d392fb9eb920fab40a