Update patch set 5
Patch Set 5: Code-Review+2

> Patch Set 5:
> 
> vagrant@ubuntu1804:~/src/gerrit$ ./polygerrit-ui/run-server.sh 
>  INFO: Invocation ID: 3d42161e-3d84-4e22-a78c-4c2e727fb4e8
>  ERROR: /home/vagrant/.cache/bazel/_bazel_vagrant/b1099410123f139d050b4d83d1dab9f0/external/io_bazel_rules_go/BUILD.bazel:66:1: in go_context_data rule @io_bazel_rules_go//:go_context_data: 
>  Traceback (most recent call last):
>          File "/home/vagrant/.cache/bazel/_bazel_vagrant/b1099410123f139d050b4d83d1dab9f0/external/io_bazel_rules_go/BUILD.bazel", line 66
>                  go_context_data(name = 'go_context_data')
>          File "/home/vagrant/.cache/bazel/_bazel_vagrant/b1099410123f139d050b4d83d1dab9f0/external/io_bazel_rules_go/go/private/context.bzl", line 400, in _go_context_data_impl
>                  cc_common.configure_features(cc_toolchain = cc_toolchain, reque..., ...)
>  Incompatible flag --incompatible_require_ctx_in_configure_features has been flipped, and the mandatory parameter 'ctx' of cc_common.configure_features is missing. Please add 'ctx' as a named parameter. See https://github.com/bazelbuild/bazel/issues/7793 for details.
>  ERROR: Analysis of target '//polygerrit-ui:devserver' failed; build aborted: Analysis of target '@io_bazel_rules_go//:go_context_data' failed; build aborted
>  INFO: Elapsed time: 1.858s
>  INFO: 0 processes.
>  FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
>  FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
> 
> Any hints how to get the server to run would be welcome.

Sorry you have to experience this pain.

- package.json was not backported to 2.16: https://gerrit.googlesource.com/gerrit/+/refs/heads/master/package.json#17
- go error seems to be caused by some 2.16 incompatibility with the latest version of go, that's also fixed in master

I will try to find someone to fix these. In the meanwhile, I guess we cannot expect you to write tests.

Patch-set: 5
Reviewer: Gerrit User 1070860 <1070860@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=+2