Update patch set 1
Patch Set 1:

Ok, so this NoSuchMethodError occurs when there are more then one javax.servlet on classpath. As far as I see we have javax.servlet 6.0 and 7.0 maybe we should remove servlet-api from dependency and also exclude it from war archive?

Patch-set: 1