Update patch set 4
Patch Set 4:

> @davido:
 > 
 > This change broke the LightweightPluginDaemonTest in standalone
 > mode, the SshDaemon fails to start because it cannot init a single
 > cipher. Every cipher that normally are there are failing to init
 > with the following stack trace. Any hint how I can fix this?
 > 
 > Disabling cipher aes128-ctr: Unable to initialize cipher
 > BaseCipher[AES,16,16,AES/CTR/NoPadding]
 > org.apache.sshd.common.SshException: Unable to initialize cipher
 > BaseCipher[AES,16,16,AES/CTR/NoPadding]
 > at org.apache.sshd.common.cipher.BaseCipher.init(BaseCipher.java:80)
 > at com.google.gerrit.sshd.SshDaemon.initCiphers(SshDaemon.java:514)
 > at com.google.gerrit.sshd.SshDaemon.<init>(SshDaemon.java:222)
 > at com.google.gerrit.sshd.SshDaemon$$FastClassByGuice$$70af8117.newInstance(<generated>)
 > at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
 > at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
 > at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
 > at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
 > at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
 > at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
 > at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
 > at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
 > at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
 > at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
 > at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
 > at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
 > at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
 > at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
 > at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
 > at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
 > at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
 > at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
 > at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
 > at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
 > at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
 > at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
 > at com.google.gerrit.pgm.Daemon.createSshInjector(Daemon.java:475)
 > at com.google.gerrit.pgm.Daemon.initSshd(Daemon.java:456)
 > at com.google.gerrit.pgm.Daemon.start(Daemon.java:313)
 > at com.google.gerrit.acceptance.GerritServer.start(GerritServer.java:169)
 > at com.google.gerrit.acceptance.AbstractDaemonTest.beforeTest(AbstractDaemonTest.java:341)
 > at com.google.gerrit.acceptance.AbstractDaemonTest$1$1.evaluate(AbstractDaemonTest.java:257)
 > at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
 > at org.junit.rules.RunRules.evaluate(RunRules.java:20)
 > at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
 > at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
 > at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
 > at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
 > at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
 > at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
 > at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
 > at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
 > at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
 > at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
 > at org.junit.runners.Suite.runChild(Suite.java:127)
 > at org.junit.runners.Suite.runChild(Suite.java:26)
 > at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
 > at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
 > at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
 > at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
 > at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
 > at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
 > at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
 > at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
 > at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
 > at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
 > at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
 > at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
 > at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
 > Caused by: java.lang.SecurityException: JCE cannot authenticate the
 > provider BC
 > at javax.crypto.Cipher.getInstance(Cipher.java:657)
 > at javax.crypto.Cipher.getInstance(Cipher.java:596)
 > at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 > at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 > at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 > at java.lang.reflect.Method.invoke(Method.java:498)
 > at org.apache.sshd.common.util.security.SecurityEntityFactory$2.getInstance(SecurityEntityFactory.java:131)
 > at org.apache.sshd.common.util.security.SecurityUtils.getCipher(SecurityUtils.java:719)
 > at org.apache.sshd.common.cipher.BaseCipher.init(BaseCipher.java:74)
 > ... 58 more
 > Caused by: java.util.jar.JarException: file:/home/ehugare/workspaces/gerritplugins/high-availability/buck-out/gen/lib/gerrit/__acceptance-framework__/gerrit-acceptance-framework-2.14-SNAPSHOT.jar
 > has unsigned entries - build-data.properties
 > at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:464)
 > at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:322)
 > at javax.crypto.JarVerifier.verify(JarVerifier.java:250)
 > at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:160)
 > at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:186)
 > at javax.crypto.Cipher.getInstance(Cipher.java:653)
 > ... 66 more

Are you sure that your problem was caused by this change?

http://stackoverflow.com/questions/32775478/jce-cannot-authenticate-the-provider-bc

Patch-set: 4
Reviewer: Paladox none <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>