Update patch set 6
Patch Set 6:

> Patch Set 6: Code-Review-1
> 
> CI failure seems to be legit:
> 
> ERROR com.google.gerrit.httpd.restapi.RestApiServlet : Error in PUT /a/changes/I0000000000000000000000000000000000000001/topic
> java.lang.InstantiationException: Cannot make I
> 	at com.google.gerrit.httpd.restapi.RestApiServlet.createInstance(RestApiServlet.java:806)
> 	at com.google.gerrit.httpd.restapi.RestApiServlet.parseString(RestApiServlet.java:781)
> 	at com.google.gerrit.httpd.restapi.RestApiServlet.parseRequest(RestApiServlet.java:696)
> 	at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:385)
>         ...

Yeah, this is going to be a pain to fix, because of the way RestApiServlet#extractInputType tries to infer the input type...

Patch-set: 6
Reviewer: Dave Borowitz <1010008@173816e5-2b9a-37c3-8a2e-48639d4f1153>