Update patch set 19
Patch Set 19:

This breaks the tests currently:

 $ buck test --all -e slow
 warning: [options] bootstrap class path not set in conjunction with -source 1.6
 /Users/nasserg/work/gerrit/./gerrit-gwtui/src/test/java/com/google/gerrit/client/diff/LineMapperTest.java:19: error: package com.google.gerrit.common.changes does not exist
 import com.google.gerrit.common.changes.Side;
                                        ^
 /Users/nasserg/work/gerrit/./gerrit-gwtui/src/test/java/com/google/gerrit/client/diff/LineMapperTest.java:54: error: cannot find symbol
     assertEquals(9, mapper.lineOnOther(Side.PARENT, 9));
                                        ^
   symbol:   variable Side
   location: class com.google.gerrit.client.diff.LineMapperTest
 /Users/nasserg/work/gerrit/./gerrit-gwtui/src/test/java/com/google/gerrit/client/diff/LineMapperTest.java:61: error: cannot find symbol
     assertEquals(10, mapper.lineOnOther(Side.PARENT, 10));
                                         ^
   symbol:   variable Side
   location: class com.google.gerrit.client.diff.LineMapperTest
 /Users/nasserg/work/gerrit/./gerrit-gwtui/src/test/java/com/google/gerrit/client/diff/LineMapperTest.java:68: error: cannot find symbol
     assertEquals(-1, mapper.lineOnOther(Side.REVISION, 9));
                                         ^
   symbol:   variable Side
   location: class com.google.gerrit.client.diff.LineMapperTest
 /Users/nasserg/work/gerrit/./gerrit-gwtui/src/test/java/com/google/gerrit/client/diff/LineMapperTest.java:75: error: cannot find symbol
     assertEquals(0, mapper.lineOnOther(Side.REVISION, 10));
                                        ^
   symbol:   variable Side
   location: class com.google.gerrit.client.diff.LineMapperTest
 /Users/nasserg/work/gerrit/./gerrit-gwtui/src/test/java/com/google/gerrit/client/diff/LineMapperTest.java:82: error: cannot find symbol
     assertEquals(-1, mapper.lineOnOther(Side.PARENT, 9));
                                         ^
   symbol:   variable Side
   location: class com.google.gerrit.client.diff.LineMapperTest
 /Users/nasserg/work/gerrit/./gerrit-gwtui/src/test/java/com/google/gerrit/client/diff/LineMapperTest.java:89: error: cannot find symbol
     assertEquals(0, mapper.lineOnOther(Side.PARENT, 10));
                                        ^
   symbol:   variable Side
   location: class com.google.gerrit.client.diff.LineMapperTest
 BUILD FAILED: //gerrit-gwtui:ui_tests failed on step "javac buck-out/bin/gerrit-gwtui/lib__ui_tests__classes" with exit code 1

Patch-set: 19
Reviewer: Nasser Grainawi <1006432@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0