Revert "submitted_together: Add a dummy change for not visible changes"
This reverts commit e73ebe2dc4103955e5d568aee13fcc78970de087.  It
broke anonymous access in projects with the CherryPick submit type.

Add a test to prevent the problem from happening again.

 Error in GET /changes/24150/revisions/f3d9f239bc26908994eebc8b4ba64e89c634f352/actions
 java.lang.IllegalStateException: user already specified: IdentifiedUser[account 5195]
	at com.google.gerrit.server.query.change.ChangeData.changeControl(ChangeData.java:691)
	at com.google.gerrit.server.git.ChangeSet.<init>(ChangeSet.java:66)
	at com.google.gerrit.server.git.MergeSuperSet.completeChangeSetWithoutTopic(MergeSuperSet.java:169)
	at com.google.gerrit.server.git.MergeSuperSet.completeChangeSet(MergeSuperSet.java:103)
	at com.google.gerrit.server.change.GetRevisionActions.getETag(GetRevisionActions.java:75)
	at com.google.gerrit.server.change.GetRevisionActions.getETag(GetRevisionActions.java:39)
	at com.google.gerrit.httpd.restapi.RestApiServlet.addResourceStateHeaders(RestApiServlet.java:496)
	at com.google.gerrit.httpd.restapi.RestApiServlet.configureCaching(RestApiServlet.java:476)
	at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:347)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)

Change-Id: I143300e7b3a17046559d640bd589ba34aed662f0