Update patch set 4
Patch Set 4:

> I'm not able to generate the Eclipse project on the head of master;
 > it's failing with:
 > 
 > TypeError: Object #<Object> has no method 'tmpDir'
 > 
 > I checked out this series of changes to see if that makes it any
 > better, but now I get the same errors with `buck build gerrit`.
 > 
 > I'm sure this is caused by something wrong with my environment. 
 > Now I'm on Ubuntu 12.04 behind a corporate firewall.  When I was
 > using my macbook, It Just Worked.
 > 
 > Full log here: http://paste.openstack.org/show/479203/

OK, looks like this was caused by an out-of-date version of nodejs.  After installing a newer version (actually, after cloning it from github and building from source because I can't apt-get update to a newer one) it gets further.

Now it's failing due to:

 Error: Request to https://bower.herokuapp.com/packages/webcomponentsjs failed: tunneling socket could not be established

Which is most certainly caused by the proxy I'm stuck behind :(

Patch-set: 4
Label: Verified=0