Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> I successfully ran the build on my laptop:
> 
> - install ant 1.9.13
> - use java 1.7_80
> - install JCE unlimited strength jurisdiction policy
> - recompile buck with java 7
> - buck build :release succeeds
> - buck build :api succeeds
> - buck test --all: most tests succeed except GarbageCollectionIT fails (4 errors) all with the error
> 
> [2019-01-08 15:06:06,319] ERROR com.google.gerrit.pgm.Daemon : Unable to start daemon
> java.lang.IllegalStateException: No SSHD host key
> 	at com.google.gerrit.sshd.SshDaemon.checkConfig(SshDaemon.java:315)
[...]
> 
> not yet sure if that's a problem with the code or with my environment

I ran all tests on GerritForge docker image and they were all passing, see m previous comment and the link where I pasted the reault of the tests.

However, that is not enough, as David Pursehouse pointed out. The problem fixed in: [1] is not covered in any existing integration test:

"
In protocol v0 bidirectional transports, the AdvertiseRefsHook is called at ref advertisement time and all is well. But in protocol v0 HTTP, we're not seeing the AdvertiseRefsHook called anywhere for the /git-upload-pack request, meaning that wants aren't validated and I can fetch anything that is pointed to by any ref (using fetch-by-sha1), as long as I can guess the object name.
"

Someone would have to test manually, that without this change, we have this vulnerability and this change did actually fix it.

[1] https://bugs.chromium.org/p/gerrit/issues/detail?id=10262

Patch-set: 3
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0