AbstractQueryChangesTest: Don't reuse account external ID
I4206f725e caused ES tests to start throwing an error:

 1) reindexIfStale(com.google.gerrit.elasticsearch.ElasticQueryChangesTest)
 com.google.gerrit.server.account.AccountException: Cannot assign external ID "gerrit:user" to account 1000001; external ID already in use.
   at com.google.gerrit.server.account.AccountManager.create(AccountManager.java:270)
   at com.google.gerrit.server.account.AccountManager.authenticate(AccountManager.java:133)
   at com.google.gerrit.server.query.change.AbstractQueryChangesTest.createAccount(AbstractQueryChangesTest.java:688)
   at com.google.gerrit.server.query.change.AbstractQueryChangesTest.reindexIfStale(AbstractQueryChangesTest.java:1627)

This is because the createAccount call in these two new test methods
reused an external ID. In other words, failing here is the correct
thing to do.

More investigation is needed into why *only* the ES tests caught this
problem, but this change at least makes the tests pass at head.

Change-Id: I91ae7dcd500ea861ef79a5644a97a4186ba1212a