Update patch set 3
Patch Set 3:

FYI this change invalidates the existing mergeability cache, and causes a scary-looking but hopefully harmless stack trace on startup.

I think we need to rework the cache code to fail more quietly in these cases (e.g. with a warning but not a stack trace). Alternatively, we could replace the old SubmitType class.

 WARN  com.google.gerrit.server.cache.h2.H2CacheImpl : Cannot build BloomFilter for jdbc:h2:file:.../cache/conflicts
 org.h2.jdbc.JdbcSQLException: Deserialization failed, cause: "java.lang.ClassNotFoundException: com.google.gerrit.extensions.common.SubmitType" [90027-174]
 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
 	at org.h2.message.DbException.get(DbException.java:161)
 	at org.h2.util.Utils.deserialize(Utils.java:413)
 	at org.h2.jdbc.JdbcConnection.convertToDefaultObject(JdbcConnection.java:1846)
 	at org.h2.jdbc.JdbcResultSet.getObject(JdbcResultSet.java:489)
 	at com.google.gerrit.server.cache.h2.H2CacheImpl$KeyType.get(H2CacheImpl.java:248)
 	at com.google.gerrit.server.cache.h2.H2CacheImpl$SqlStore.buildBloomFilter(H2CacheImpl.java:376)
 	at com.google.gerrit.server.cache.h2.H2CacheImpl$SqlStore.open(H2CacheImpl.java:337)
 	at com.google.gerrit.server.cache.h2.H2CacheImpl.start(H2CacheImpl.java:167)
 	at com.google.gerrit.server.cache.h2.H2CacheFactory$1.run(H2CacheFactory.java:113)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 	at java.lang.Thread.run(Thread.java:745)
 Caused by: java.lang.ClassNotFoundException: com.google.gerrit.extensions.common.SubmitType
 	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
 	at java.security.AccessController.doPrivileged(Native Method)
 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:428)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:361)
 	at java.lang.Class.forName0(Native Method)
 	at java.lang.Class.forName(Class.java:270)
 	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:625)
 	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
 	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
 	at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1725)
 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1347)
 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
 	at org.h2.util.Utils.deserialize(Utils.java:411)
 	... 10 more

Patch-set: 3
Reviewer: Dave Borowitz <1010008@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0