Update patch set 1
Patch Set 1:

> ListBranchesIT is failing:
 > 
 > FAIL      8.4s  7 Passed   0 Skipped   1 Failed   com.google.gerrit.acceptance.rest.project.ListBranchesIT
 > FAILURE listBranchesOfEmptyProject: Not true that <[HEAD,
 > refs/meta/config]> contains exactly <[refs/meta/config]>. It has
 > unexpected items <[HEAD]>
 > java.lang.AssertionError: Not true that <[HEAD, refs/meta/config]>
 > contains exactly <[refs/meta/config]>. It has unexpected items
 > <[HEAD]>

I suspect it's something wrong with the test.  I've tested on a live site, and a newly created empty project does not have the HEAD revision.

Patch-set: 1