Update patch set 4
Patch Set 4:

> > If you download release.war from GerritForge CI from patch set 4, you will be only able to run it with Java 11.
> 
> That is clear. What isn't clear to me is how I can run a Java 11 .war executable on a machine that doesn't have Java 11 installed and do an E2E test with that. Another "magic spell" done by Bazel?

Bazel testrunner is a Java program that is launched with specific Java runtime, that is loading the  acceptance framework and all Gerrit tests and execute them.

The question to ask here is: what Java runime is used as host_java_toolchain that is launching Bazel testrunnner?

Per default this is your current runtime pointing by your JAVA_HOME environment variable. Let's say it is JDK 8. Like in case of GerritForge CI, it doesn't have Java 11 installed at all, so that the question indeed is, how comes that patch set 4, that produced Java 11 (byte code major version 55) was successful verified and all tests are passing, even though GerritForge CI docker image, based on Debian stretch, only includes Java 8?

This is (again) Bazel toolchain magic. That option is relevant here:

   --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11

With this option in place in .bazelrc file, Bazel ignoring your locally installed Java 8 runtime and instead using toolchain_java11 provided by Bazel (remote_jdk) to launch testrunner application.

In fact, if you remove the above line in .bazelrc, all tests would fail as expected, with UnsupportedClassVersionError exception, e.g.:

  java.lang.UnsupportedClassVersionError: SshSubmitOnPushITTestSuite has been compiled by a more recent version
  of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
  [...]

Patch-set: 4
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>