Update patch set 15
Patch Set 15:

> Patch Set 14:
> 
> > Patch Set 14:
> > 
> > > Doesn't work for me
> > 
> > Have you checked the CI log?
> > 
> >   ERROR: /home/jenkins/.cache/bazel/_bazel_jenkins/3239551e333dc09ba2b5ef07ff4549b6/external/jgit/lib/BUILD:216:1: no such package '@servlet-api-3_1//jar':
> >   The repository '@servlet-api-3_1' could not be resolved and referenced by '@jgit//lib:servlet-api'
> > 
> > That's because JGit build tool chain must be adapted after the rename of @servlet-api-3_1 to @servlet-api in Gerrit core (the same must happen in JGit as well). See this change for more details: [1]. 
> 
> Done with https://git.eclipse.org/r/#/c/150449/.

I've put a reference to the SHA1 in PS15.
Using GitHub is problematic, because doesn't allow to do verification of changes in Gerrit and JGit at the same time.

To make it work, I had to use a workaround, forking it on GitHub and pushing the same SHA1 on my fork in a feature branch. That is *very* messy, but works for now.

As soon as Patrick setup the mirroring on gerrit-review, we should get rid of the fetching from GitHub.

Patch-set: 15
Reviewer: Gerrit User 1006192 <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>