Update patch set 18
Patch Set 18:

> Patch Set 18:
> 
> > Patch Set 18:
> > 
> > > Patch Set 18:
> > > 
> > > > Patch Set 18:
> > > > 
> > > > > Patch Set 14:
> > > > > 
> > > > > > Doesn't work for me
> > > > > 
> > > > > Have you checked the CI log?
> > > > > 
> > > > >   ERROR: /home/jenkins/.cache/bazel/_bazel_jenkins/3239551e333dc09ba2b5ef07ff4549b6/external/jgit/lib/BUILD:216:1: no such package '@servlet-api-3_1//jar':
> > > > >   The repository '@servlet-api-3_1' could not be resolved and referenced by '@jgit//lib:servlet-api'
> > > > > 
> > > > > That's because JGit build tool chain must be adapted after the rename of @servlet-api-3_1 to @servlet-api in Gerrit core (the same must happen in JGit as well). See this change for more details: [1]. 
> > > > 
> > > > note that updating to another version of any 3rd party dependency (or adding a new one) in JGit requires filing a CQ ticket in IPzilla and is subject to approval by the Eclipse legal team, this means this can take a while
> > > 
> > > Well, it was only renaming of Bazel rule, not a fetch or any new version of third party dependency.
> > > 
> > > However, it was enough to break JGit build in Gerrit tree.
> > > 
> > > However: Doe we really have to support building gerrit upstream against non-merged JGit changes?
> > 
> > Yes, and it was exactly for *this* change to get verified :-)
> > 
> > If JGit and Gerrit would have been on the same server, I could have used the 'topic' to link them together.
> > 
> > > If it is a critical issue, then it could be merged within hours. And to verify JGit change with gerrit, even with bazel, the JGit change could be fetched locally.
> > 
> > Locally from where? How can the CI fetch and build the change?
> 
> Not at all! Unsupported feature to build on the CI Gerrit against non merged JGit changes.
> 
> However, if this change is merged, and CI is running and building Gerrit against JGit from a specific SHA1, then the change that changes servlet-api-3_1 to servlet-api wouldn't build n the fist place.
> 
> In the same time, if you change something in JGit and break something that wouldn't build with gerrit, then the Upgrade of JGit SHA1 in gerrit wouldn't build.
> 
> Anyway, I don't see atm why would we require building gerrit against non merged JGit commits. Gerrit wasn't able to do it for the last 11 years.

Isn't this the role of a CI to build non-merged commits and make sure they work together?
:-)

Anyway, it is not true, before we could do that.
Shawn had put in place the ability to anticipate JGit fixes in Gerrit so that could have been validated and test.

> Why is this feature suddenly and so urgently required today?

The whole purpose of this change was to go faster and not wait for official JGit releases for development Gerrit master. Otherwise, why bothering with JGit build from source code?

Patch-set: 18
Reviewer: Gerrit User 1006192 <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>