Update patch set 4
Patch Set 4: Verified-1

This is an automated message from the Diffy, the Autoverifier.

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  [-] PARSING BUILD FILES...FINISHED 3.7s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/change/RevisionEditCommands.java:131: error: method create in interface com.google.gerrit.server.change.PatchSetInserter.Factory cannot be applied to given types;
          patchSetInserterFactory.create(repo, rw, ctl.getRefControl(), me, c,
                                 ^
  required: org.eclipse.jgit.lib.Repository,org.eclipse.jgit.revwalk.RevWalk,com.google.gerrit.server.project.ChangeControl,org.eclipse.jgit.revwalk.RevCommit
  found: org.eclipse.jgit.lib.Repository,org.eclipse.jgit.revwalk.RevWalk,com.google.gerrit.server.project.RefControl,com.google.gerrit.server.IdentifiedUser,com.google.gerrit.reviewdb.client.Change,org.eclipse.jgit.revwalk.RevCommit
  reason: actual and formal argument lists differ in length
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
...

Patch-set: 4
Label: Verified=-1