Update patch set 3
Patch Set 3:

This causes internal server errors with:

com.google.gerrit.server.update.UpdateException: com.google.gerrit.server.project.NoSuchChangeException: 1901

yet the change does indeed exist so it must be using the wrong logic. though not sure

This only happends when using the drop down. Not when entering the full commit number.

Patch-set: 3
Reviewer: Paladox none <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>