Expose tools:gjf rule based on google-java-format validate option
To intergrate google-java-format utility check with a CI system in
non-intrusive way, validation mode is needed: [1], that is currently
missing. There are two pull requests pending for review, that provide
this feature: [2],[3].

This change is relying on the forked version that is packaging PR from
GH release page, based on gjf release 1.3 that is currently used.

With this change in place the gjf check in CI context, would be a one
liner:

 $ git show --diff-filter=AM --name-only HEAD | grep java$ | \
   sed 's@^@'"$PWD"/'@' | xargs -r bazel run tools:gjf -- --dry-run
  INFO: Running command line: bazel-bin/tools/gjf --dry-run
  Need Formatting:
  [gerrit-server/src/test/java/com/google/gerrit/testutil/InMemoryH2Type.java,
   gerrit/gerrit-server/src/test/java/com/google/gerrit/testutil/NoteDbMode.java]
  ERROR: Non-zero return code '1' from command: Process exited with
  status 1.

* [1] https://github.com/google/google-java-format/issues/105
* [2] https://github.com/google/google-java-format/pull/106
* [3] https://github.com/google/google-java-format/pull/154

Change-Id: If11be6d5ff7b046571e61550fe7f4ff925daf50e