Update patch set 2
Patch Set 2:

I also tried to move rules_closures, bazel_skylib, net_zlib and bazel_gazelle (that are not used by Google) to tools/nongoogle.bzl: [1]. Unfortunately, this does not work, because load() 
 invocation is currently only allowed in WORKSPACE file:

  $ bazel build :gerrit
  INFO: Invocation ID: eb5c3f99-b866-47a6-9f07-c2bb899185a3
  ERROR: /home/davido/projects/gerrit2/tools/nongoogle.bzl:43:5: syntax error at 'load':
    expected expression
  ERROR: /home/davido/projects/gerrit2/tools/nongoogle.bzl:52:5: Trailing comma is allowed
    only in parenthesized tuples.

@philwo, @laurentlb: Any clue why this restriction is in place and whether this is going to be lifted?


* [1] http://paste.openstack.org/show/750849

Patch-set: 2
Reviewer: Gerrit User 1030339 <1030339@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Gerrit User 1031439 <1031439@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>