Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> I notice that the test failed. Looks like I need to update some test expectations. I will look into it if you think this is a good change to make (and the right way of doing it). Thank you!

A few things:

1) I need to talk to design before we implement this. The reason that I held off doing it myself was because they had not included the comment count in their designs, which took up a good amount of space, and are extremely important. In the first iteration, we opted to included those in favor of the date.  I am going to chat with them about this today, so stay tuned.

2) I ran the change myself and there is a javascript error. It's probably in your best interest to get set up running this locally. Feel free to DM me if you need help with this.

TypeError: dateStr.replace is not a function
    at Object.util.parseDate (util.js:24)
    at HTMLElement._computeFullDateStr (gr-date-formatter.js:164)
    at HTMLElement._computeEffect (polymer.html:1635)
    at HTMLElement._effectEffects (polymer.html:1458)
    at HTMLElement._propertySetter (polymer.html:1442)
    at HTMLElement.setter (polymer.html:1521)
    at _getPreferenc

Patch-set: 5
Reviewer: Becky Siegel <1030207@173816e5-2b9a-37c3-8a2e-48639d4f1153>