Update patch set 1
Patch Set 1: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 4.5s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/git/BatchUpdate.java:25: error: cannot find symbol
import com.google.gerrit.server.change.ChangeOp;
                                      ^
  symbol:   class ChangeOp
  location: package com.google.gerrit.server.change
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/git/BatchUpdate.java:25: error: cannot find symbol
import com.google.gerrit.server.change.ChangeOp;
...

Patch-set: 1
Reviewer: Diffy Cuckoo (Automated Verifier) <1012977@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1