Update patch set 1
Patch Set 1:

* I released this version some minutes ago, it should appear on Maven central within the next hours
* the following test is failing with this version, this is probably due to https://git.eclipse.org/r/#/c/98478/

 There was 1 failure:
1) zipFormat(com.google.gerrit.acceptance.ssh.UploadArchiveIT)
java.lang.AssertionError: Not true that <2> is equal to <1>
	at com.google.gerrit.acceptance.ssh.UploadArchiveIT.zipFormat(UploadArchiveIT.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

Patch-set: 1
Reviewer: Matthias Sohn <1004034@173816e5-2b9a-37c3-8a2e-48639d4f1153>