Update patch set 5
Patch Set 5:

> The test is provoking NoClassDefFound

What class couldn't be found?

I was getting this on jgit when upgrading commons-compress [1]:

> java.lang.NoClassDefFoundError: org/tukaani/xz/FilterOptions

and it turned out to be caused by a mismatch between commons-compress and tukaani-xz.

David O noted that we seem to have mismatching versions in gerrit [2].  Could that be the cause here too?

[1] https://git.eclipse.org/r/#/c/115360/
[2] https://gerrit-review.googlesource.com/c/gerrit/+/133150/7/WORKSPACE#277

Patch-set: 5
Reviewer: David Pursehouse <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>