Update patch set 6
Patch Set 6:

> This is actually breaking one test:
 > FAILURE testGetPossibleStatus: expected:<[DRAFT, MERGED,
 > ABANDONED]> but was:<[SUBMITTED, DRAFT, MERGED, ABANDONED]>
 > java.lang.AssertionError: expected:<[DRAFT, MERGED, ABANDONED]> but
 > was:<[SUBMITTED, DRAFT, MERGED, ABANDONED]>
 > 
 > Will rework the change to get the 's' status without necessarily
 > reintroducing the enum value.

I'm happy with the end result, but this particular failing test is not the only reason you should not re-add SUBMITTED. There are lots of examples of removing things (columns, tables) that result in slightly more complexity in the schema upgrade code. This is ok, because it's better to have that ugliness restricted to the schema upgrade code than have it spread out over the rest of Gerrit.

Patch-set: 6