Update patch set 1
Patch Set 1:

> The problem is that Chromium depot_tools is able to squash changesets automatically on upload 

Sorry, I've never used that tool, so have no idea how it's supposed to work, but squashing changes sounds like something that might have caused this:

 > https://gerrit-review.googlesource.com/100756 closed)
 > error: failed to push some refs to 'https://gerrit.googlesource.com/gerrit'

Could be caused by:

- You've done a rebase locally including that other change, before it was merged, and now you have it with a different sha1 locally.

- Somehow you've replaced the Change-Id in one of your local changes with that change's Change-Id 

 > 
 > So what to do now?

Reset your local head to origin/master.  Cherry pick the previous commit, and then cherry pick this commit (use the links from the Download menu).

Then, do an interactive rebase:

  git rebase -i HEAD~2

and for this commit, change "pick" to "fixup".

Patch-set: 1
Reviewer: David Pursehouse <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>