Update patch set 5
Patch Set 5:

I addressed Jonathans concerns and the notedb is only updated when we're sure the update can be performed without merge conflict and submit rule check failing.

There are 2 known tests failing (the earlier message about build failure was a bogus bot posting things)


FAILURE submitOnPushMergeConflict: Not true that <[]> contains exactly <[1000000]>. It is missing <[1000000]>
java.lang.AssertionError: Not true that <[]> contains exactly <[1000000]>. It is missing <[1000000]>
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:25)
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:21)
	at com.google.common.truth.Subject.failWithRawMessage(Subject.java:319)
	at com.google.common.truth.IterableSubject.failWithBadResultsAndSuffix(IterableSubject.java:355)
	at com.google.common.truth.IterableSubject.containsExactly(IterableSubject.java:335)
	at com.google.common.truth.IterableSubject.containsExactlyElementsIn(IterableSubject.java:259)
	at com.google.gerrit.acceptance.PushOneCommit$Result.assertReviewers(PushOneCommit.java:257)
	at com.google.gerrit.acceptance.PushOneCommit$Result.assertChange(PushOneCommit.java:250)
	at com.google.gerrit.acceptance.git.SubmitOnPushIT.submitOnPushMergeConflict(SubmitOnPushIT.java:127)


This test pushes via "push HEAD:refs/for/master%submit" and then there is a conflict. the only failing assertion is the pusher not being put as a reviewer. I wonder if we want to keep that feature or if that is not desired any more.

The second failure is


FAILURE submitOnPushSuccessfulMerge: expected:<[admin@examp]le.com> but was:<[sbeller@sbeller.mtv.corp.goog]le.com>
org.junit.ComparisonFailure: expected:<[admin@examp]le.com> but was:<[sbeller@sbeller.mtv.corp.goog]le.com>
	at com.google.common.truth.Platform.comparisonFailure(Platform.java:133)
	at com.google.common.truth.Truth$1.failComparing(Truth.java:77)
	at com.google.common.truth.StringSubject.isEqualTo(StringSubject.java:69)
	at com.google.gerrit.acceptance.git.SubmitOnPushIT.assertMergeCommit(SubmitOnPushIT.java:258)
	at com.google.gerrit.acceptance.git.SubmitOnPushIT.submitOnPushSuccessfulMerge(SubmitOnPushIT.java:143)

I have no idea where this comes from and how to debug into that yet.

Patch-set: 5