Update patch set 1
Patch Set 1:

> One way to test this: populate your cache with some data from prior
 > to the key change, then run with the key change and see if there
 > are errors.

I tested 2 scenarios:
1. cache with data from before the deltaSize field was added, then upgrade to this change
2. cache with data that contains the deltaSize field, but without updated serialVersionUID, then upgrade to this change

In both cases there is no error for the user and it works as expected, but in the first case there is a warning with an exception for the failed deserialization in the error log. This looks pretty ugly, but I guess it's okay/expected?

[HTTP-38] WARN  com.google.gerrit.server.cache.h2.H2CacheImpl : Cannot read cache jdbc:h2:file:///usr/local/google/home/ekempin/site/cache/diff for PatchListKey[BASE..502e8a68b9b7f95982016c8e2ca70047bfde05bd IGNORE_NONE]
org.h2.jdbc.JdbcSQLException: Deserialization failed, cause: "java.io.IOException: Invalid enum 46 for class com.google.gerrit.reviewdb.client.Patch$ChangeType" [90027-176]
  at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
  at org.h2.message.DbException.get(DbException.java:167)              
  at org.h2.util.Utils.deserialize(Utils.java:419)                     
  at org.h2.jdbc.JdbcConnection.convertToDefaultObject(JdbcConnection.java:1911)
  at org.h2.jdbc.JdbcResultSet.getObject(JdbcResultSet.java:504)       
  at com.google.gerrit.server.cache.h2.H2CacheImpl$SqlStore.getIfPresent(H2CacheImpl.java:465)
  ...
Caused by: java.io.IOException: Invalid enum 46 for class com.google.gerrit.reviewdb.client.Patch$ChangeType
  at com.google.gerrit.server.ioutil.BasicSerialization.readEnum(BasicSerialization.java:164)
  at com.google.gerrit.server.patch.PatchListEntry.readFrom(PatchListEntry.java:221)
  at com.google.gerrit.server.patch.PatchList.readObject(PatchList.java:191)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)       
  ...

Patch-set: 1
Label: Verified=0