Update git submodules
* Update plugins/delete-project from branch 'stable-3.8'
  to 825dcb41a9abfc5892ef3b0f8e89b7ca25c8dfe1
  - Merge branch 'stable-3.7' into stable-3.8
    
    * stable-3.7:
      ConfigurationTest: Remove flaky invalidTargetArchiveFolder test
      Send project-deleted event after project deletion
    
    Change-Id: I2ac01b00d7ce442b96a032d90b4037670e65d79a
    
  - ConfigurationTest: Remove flaky invalidTargetArchiveFolder test
    
    This test is failing when running gerrit test in docker image with root
    user. It's also failing when remote build execution is used (BuildBuddy
    provider).
    
    It seems to rely on the fact that the exception is thrown:
    
    java.nio.file.FileSystemException: /\\\: Operation not permitted
    
    However when the test is executed with BuildBuddy RBE that exception is
    not raised and as a consequence of that the test ends up failing. It
    looks that the folder /\\\ is created in the remote executor.
    
    While it could be fixed with:
    
    exec_properties = {
        "dockerUser": "nobody",
    },
    
    we prefer not to complicate our build toolchain and rather remove the
    test.
    
    Change-Id: I51bccdf2cb19559690d3d88bd92cf60bc28f5fcd
    
  - Send project-deleted event after project deletion
    
    Gerrit EventDispatcher has two types of listeners: user restricted or
    unrestricted. For the restricted listeners before sending the event
    Gerrit checks if user has permission to access the project. This means
    that `project-deleted` event will not be delivered to the restricted
    listeners because when we send the event project is already removed
    so we cannot check permissions anymore.
    
    Bug: Issue 15778
    Change-Id: I86386cf8b321a2dcc8a4a8ee6f36815e5c9228a2