Run consistency checker for GroupIT
TODO:

* stalenessChecker[noteDbConfig](com.google.gerrit.acceptance.api.group.GroupsIT)
java.lang.AssertionError: Not true that <[ERROR: name map has entry
(71dde2da231ef951c0da952f964e3cbb4fd44318,
com.google.gerrit.acceptance.api.group.GroupsIT_stalenessCheckernoteDbConfig_foo),
entry missing as group ref]> is empty

* cannotCreateGroupNamesBranch[disableReviewDb](com.google.gerrit.acceptance.api.group.GroupsIT)
java.lang.AssertionError: Not true that <[ERROR: ref refs/meta/group-names does not exist]> is empty
        at com.google.gerrit.acceptance.api.group.GroupsIT.consistencyCheck(GroupsIT.java:152)


* cannotCreateGroupNamesBranch[noteDbConfig](com.google.gerrit.acceptance.api.group.GroupsIT)
java.lang.AssertionError: Not true that <[ERROR: ref refs/meta/group-names does not exist]> is empty
        at com.google.gerrit.acceptance.api.group.GroupsIT.consistencyCheck(GroupsIT.java:152)

Change-Id: I2672ba0c7aea387fe0eaea91d4b551764565e8a8