Update patch set 1
Patch Set 1:

> When running the test suite, I get lots of
 > 
 > java.lang.OutOfMemoryError: GC overhead limit exceeded

That is not a new regression.

Patch-set: 1