Update patch set 10
Patch Set 10: Code-Review-1

> @David Pursehouse im wondering could i have help please since it
 > keeps failing to build.
 > 
 > with errors like
 > 
 > ProjectTagsScreen.java:408: error: cannot find symbol
 > if (k.canDelete()) {
 > ^
 > symbol:   method canDelete()
 > location: variable k of type com.google.gerrit.client.projects.TagInfo
 > /home/paladox/gerrit4/gerrit-gwtui/src/main/java/com/google/gerrit/client/admin/ProjectTagsScreen.java:430:
 > error: cannot find symbol
 > if (k.webLinks() != null) {
 > 
 > 
 > please?

It's because TagInfo doesn't have a canDelete() method.  Only the canDelete member was added.  See the base class RefInfo for example methods.

https://gerrit.googlesource.com/gerrit/+/stable-2.13/gerrit-gwtui/src/main/java/com/google/gerrit/client/projects/RefInfo.java


I'm not sure if this should be on the stable branch anyway. I'd rather put it on master.

Patch-set: 10
Reviewer: David Pursehouse <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=-1