Update patch set 10
Patch Set 10: Verified-1

I can confirm that cookbook-plugin is failing to load on closure compiler optimized version of Gerrit on latest Firefox:

 TypeError: a._loadedGwt is not a function

Chrome works just fine, though. So we probably should try to create a small reproducer and report it to GWT or closure-compiler team?

Patch-set: 10
Label: Verified=-1