Update patch set 4
Patch Set 4:

This change broke pegdown:1.4.2 => parboiled:1.1.6 => asm:4.1 toolchain, as GitBlit integration change has shown: [1]. Trying to open plugin markdown page is failing with:

 [2014-12-10 01:29:43,790] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /plugins/reviewers/Documentation/index.html
java.lang.RuntimeException: Error creating extended parser class: null
	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:92)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:61)
	at com.google.gerrit.server.documentation.MarkdownFormatter.parseMarkdown(MarkdownFormatter.java:147)
	at com.google.gerrit.server.documentation.MarkdownFormatter.extractTitleFromMarkdown(MarkdownFormatter.java:114)
	at com.google.gerrit.httpd.plugins.HttpPluginServlet.extractTitleFromMarkdown(HttpPluginServlet.java:529)
	at com.google.gerrit.httpd.plugins.HttpPluginServlet.appendEntriesSection(HttpPluginServlet.java:352)
	at com.google.gerrit.httpd.plugins.HttpPluginServlet.sendAutoIndex(HttpPluginServlet.java:432)
	at com.google.gerrit.httpd.plugins.HttpPluginServlet.onDefault(HttpPluginServlet.java:310)
	at com.google.gerrit.httpd.plugins.HttpPluginServlet.access$2(HttpPluginServlet.java:247)
	at com.google.gerrit.httpd.plugins.HttpPluginServlet$3.doFilter(HttpPluginServlet.java:229)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at com.google.gerrit.httpd.plugins.HttpPluginServlet.service(HttpPluginServlet.java:233)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:279)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:269)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:180)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.gerrit.httpd.GetUserFilter.doFilter(GetUserFilter.java:82)
	at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:73)
	at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:117)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:64)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:67)
	at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:92)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:485)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535)
	at java.lang.Thread.run(Thread.java:744)
  Caused by: java.lang.IllegalStateException
	at org.objectweb.asm.tree.ClassNode.<init>(Unknown Source)
	at org.parboiled.transform.ParserClassNode.<init>(ParserClassNode.java:41)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:43)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
	... 50 more

This change is needed because of GWT upgrade to 2.7. Without it, GWT module fails to compile. Can we create custom build of pegdown that works with asm 5.0.3?

 [1] https://gerrit-review.googlesource.com/61594

Patch-set: 4