NoteDbMigrator: Totally skip migration for orphan changes
This case was explicitly handled by ChangeRebuilderImpl, and
NoteDbMigrator in fact caught RepositoryNotFoundException and let the
migration proceed. Unfortunately, this would then cause the primary
storage migration step to fail with:

  com.google.gwtorm.server.OrmRuntimeException: change X has no note_db_state; rebuild it first

Work around this by catching this exception and checking after the fact
whether the change is known to be unrecoverably corrupt. There is
already another check in place: no patch set, in which case the
migration process would also proceed, that was added in I0439c7fc8e5.
So that we are just adding yet another "supported" kind of change
corruption recovery mechanism to the migration proccess.

The usual use case for orphan changes, also, the changes with not
existing git repsitories on the file system, is often seen for gerrit
test instances: Database replicated from the production system but only
a couple of git repositories are replicated, leading to orphan changes.

Reported-by: Alan Tokaev <tokaev@gmail.com>
Change-Id: I516f40f03feaafe3014fabb0c2f5c40d6753b8bc