Update patch set 11
Patch Set 11: Verified+1

Good catch by Hugo: fixed the missing file and re-tested on GerritHub.io:

   [2018-04-20 14:19:04,316] [HTTP-995] WARN  com.google.gerrit.server.query.change.ChangeIsVisibleToPredicate : Skipping change 8194 because the corresponding repository was not found
com.google.gerrit.server.permissions.PermissionBackendException: project 'Distrotech/linux' is unavailable

Patch-set: 11
Reviewer: Hugo Arès <1012987@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Luca Milanesio <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=+1