[DO_NOT_SUBMIT] Reproduce QueryParseException in logs when trying to get a non-visible-account suggested as reviewer
If a user cannot see account 'foo' and then tries to get reviewer
suggestion for 'foo' it is expected that reviewer suggestion list is
empty since non-visible accounts are filtered out. This change adds a
new test to verify it and it passes.

However since the refactoring of AccountResolver [1] we now log
'QueryParseException: Account '<account-id>' not found' for the
non-visible account which spams the logs.

Full stacktrace:
ERROR com.google.gerrit.server.restapi.change.ReviewerRecommender : Exception while suggesting reviewers
com.google.gerrit.index.query.QueryParseException: Account '1000006' not found
	at com.google.gerrit.server.query.change.ChangeQueryBuilder.parseAccount(ChangeQueryBuilder.java:1350)
	at com.google.gerrit.server.query.change.ChangeQueryBuilder.label(ChangeQueryBuilder.java:821)
	at com.google.gerrit.server.restapi.change.ReviewerRecommender.baseRankingForCandidateList(ReviewerRecommender.java:251)
	at com.google.gerrit.server.restapi.change.ReviewerRecommender.suggestReviewers(ReviewerRecommender.java:117)
	at com.google.gerrit.server.restapi.change.ReviewersUtil.recommendAccounts(ReviewersUtil.java:300)
	at com.google.gerrit.server.restapi.change.ReviewersUtil.suggestReviewers(ReviewersUtil.java:196)
	at com.google.gerrit.server.restapi.change.SuggestChangeReviewers.apply(SuggestChangeReviewers.java:73)
	at com.google.gerrit.server.api.changes.ChangeApiImpl.suggestReviewers(ChangeApiImpl.java:439)
	at com.google.gerrit.server.api.changes.ChangeApiImpl.access$0(ChangeApiImpl.java:434)
	at com.google.gerrit.server.api.changes.ChangeApiImpl$1.get(ChangeApiImpl.java:429)
	at com.google.gerrit.acceptance.rest.change.SuggestReviewersIT.suggestReviewers(SuggestReviewersIT.java:549)
	at com.google.gerrit.acceptance.rest.change.SuggestReviewersIT.nonVisibleAccountIsNotSuggested(SuggestReviewersIT.java:528)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at com.google.gerrit.acceptance.AbstractDaemonTest$1$1.evaluate(AbstractDaemonTest.java:221)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.google.gerrit.server.account.AccountResolver$UnresolvableAccountException: Account '1000006' not found
	at com.google.gerrit.server.account.AccountResolver$Result.asNonEmptyIdSet(AccountResolver.java:162)
	at com.google.gerrit.server.query.change.ChangeQueryBuilder.parseAccount(ChangeQueryBuilder.java:1345)
	... 53 more

If this change is cherry-pick onto a commit before the refactoring
series [1], e.g. commit 936fd002, this exception doesn't appear in the
logs when the new test is run.

This doesn't affect the correctness of the REST endpoint but adds log
spam which can make the investigation of other issues more difficult.

[1] https://gerrit-review.googlesource.com/q/topic:account-resolver-2

Signed-off-by: Edwin Kempin <ekempin@google.com>
Change-Id: I01b8fb6d5160e8cc316cad68e95f6ba8b8215eab