Handle size-based quota exceptions explicitly
Quota enforcerers have already been integrated into Gerrit core.  When
handling receive-packs, Gerrit asks for available bytes the repository
can grow, before reaching a size quota, if any.

The way this limit is enforced is through the JGit maxPackSizeLimit
property, which will throw a TooLargePackException, should the packfile
being uploaded exceeds the allowance.

This error is exposed to the client as-is:

``` TooLargePackException: Pack exceeds the limit of 190,821 bytes,
rejecting the pack
```

For a committer reading the error, it is not at all intuitive to
understand that this error is associated to the enforcing of a quota.

To fix this, explicitly handle the TooLargePackException and
construct an informative QuotaException instead.

```
Push rejected: it would exceed the available repository size quota of
190,821 bytes.
```

Also handle the special case where the repository size has already
exceeded the quota and thus the available quota was zero. In this case
Jgit returned an EOFException and the error showed as a cryptic:

```
error: remote unpack failed: error Packfile is truncated.
```

The error now shows more clearly as:
```
Push rejected: the repository size is over the quota of <quota of the repo> bytes.
```

A follow up to this change will be to allow Quota Enforcerers (for
example the quota plugin), to specify their own error message, so that
each enforcerer can differentiate how to inform the user about the quota
being exceeded and what they can do about it (i.e. get in touch with
the administrator, open an issue, etc).

Bug: Issue 459520484
Release-Notes: Return a clear error when a push exceeds the size quota.
Change-Id: If45a1bc9b8a6a77f1c4ec1bf22cb5c74b8c7f5f9