DuplicateExternalIdKeyException: add constructor with cause
Google-Bug-Id: b/383052900
Release-Notes: skip
Change-Id: I84d88468c3beddfc23e937ab612870ca38619d86