Update patch set 2
Patch Set 2:

Output now looks like this:

 $ git push origin HEAD:refs/for/master
 Counting objects: 4, done.
 Writing objects: 100% (3/3), 277 bytes, done.
 Total 3 (delta 0), reused 0 (delta 0)
 remote: Processing changes: refs: 1, done    
 remote: ERROR: missing Change-Id in commit message
 remote: Suggestion for commit message:
 remote: Test without change id in message
 remote: 
 remote: Change-Id: I1c7beb6579405866b2e3fd715b43e8276ce905e9
 remote: Hint: To automatically add a Change-Id to commit messages, install the commit-msg hook:
 remote:       $ scp -p -P 29418 david.pursehouse@xxxxxx.xxxxxx.net:hooks/commit-msg .git/hooks/
 To ssh://david.pursehouse@xxxxxx:29418/another-test
  ! [remote rejected] HEAD -> refs/for/master (missing Change-Id in commit message)
 error: failed to push some refs to 'ssh://david.pursehouse@xxxxxx:29418/another-test'

Patch-set: 2
Label: Code-Review=0
Label: Verified=0