Bazel: Use custom Ubuntu 18.04 image for RBE
Due to outdated git version in Ubuntu 18.04 releases, custom built
docker image must be used for RBE.

Switch to using new release of rbe_autoconfig 3.0.0, that is using
the new published docker image with git-core version 2.34.1 and
re-enable git protocol V2 tests in RBE environment.

Due to JGit dead lock issue, some tests were disabled in RBE
environment. Now, that this issue was fixed, bump JGit version to
this change: [1] and remove no_rbe tag from all affected tests.

With this change all tests are running in RBE environment and test
execution in non RBE environment is a no-op now and can be disabled.

Now, that the bazel test invocation on non RBE platform is a no-op,
the test command is failing with:

  $ bazelisk test --test_tag_filters=-flaky,elastic,no_rbe //...
  WARNING: All specified test targets were excluded by filters
  ERROR: No test targets were found, yet testing was requested

We should disable non RBE checker, but to make the test pass add
no_rbe tag to always_pass_test rule. It was added so that test
verification for plugin changes always succeed, also in the case
when plugins don't have any tests.

[1] https://git.eclipse.org/r/c/jgit/jgit/+/189208

Bug: Issue 12486
Change-Id: Ic64102766a2667b31c73d1b09957c0ba9aa74c70