Update patch set 8
Patch Set 8: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 2.7s
/home/deckard/workspace/gerrit/gerrit-pgm/src/main/java/com/google/gerrit/pgm/SwitchSecureStore.java:147: error: unreported exception java.io.IOException; must be caught or declared to be thrown
    JarScanner scanner = new JarScanner(secureStore);
                         ^
Errors: 1. Warnings: 0.
BUILD FAILED: //gerrit-pgm:pgm failed with exit code 1:
javac
[-] BUILDING...FINISHED 6.1s
:

Patch-set: 8
Label: Verified=-1