Update patch set 2
Patch Set 2: Code-Review-2

CI failure is because upstream Bazelk version doesn't support: local_disk_cache options:

  ERROR: Unrecognized option: --experimental_local_disk_cache_path=~/.gerritcodereview/bazel-cache/cas

Patch-set: 2
Reviewer: David Ostrovsky <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=-2