Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> > Patch Set 4:
> > 
> > Tried on Linux also after having authenticated using my GCloud account and from within the same GCP application inside a GCloud Compute node, but I get a permission denied error:
> > ERROR: Failed to query remote execution capabilities: PERMISSION_DENIED: Request had insufficient authentication scopes.
> 
> On my Linux laptop, I installed gcloud SDK and authenticated using `gcloud auth` command. Have you done that? What is the output of this command for you:
> 
>   $ gcloud auth list
> 
> I can also can list projects I have ACL fors, using:
> 
>   $ gcloud projects list
> 
> Does it work for you?

Found the issue, look at that:
User [164060093628@project.gserviceaccount.com] does not have permission to access project [api-project-164060093628]

Beucase I am running the command inside GCP I am assigned a service account that has no permissions to access the RBE on that project. I believe I need @Han-Wen to do something and then we'll be able to use RBE from GCP.

Patch-set: 4
Reviewer: Gerrit User 1006192 <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>