Revert "Change.Id should be int in generated events" DO NOT MERGE
This reverts commit b0cfe140164f866cffa107549063d3b3da0e8a5f.

Causes the its-base plugin to fail with

incompatible types: int cannot be converted to String
    properties.add(propertyFactory.create("change-number", changeAttribute.number));
                                                                          ^plugins/its-base/src/main/java/com/googlesource/gerrit/plugins/its/base/util/PropertyAttributeExtractor.java:79: error: incompatible types: int cannot be converted to String
        patchSetAttribute.number));

This is for WMF.

Change-Id: I577fdbf23abd747de87a18b6e101cb790a4f5d0d