Update patch set 2
Patch Set 2:

> NoteDB - Gerrit-CI Build: https://gerrit-ci.gerritforge.com/job/Gerrit-verifier-notedb/767/consoleText

LuceneQueryChangesV14Test byHashtagWithNotedb: Not true that hashtag:foo (<[2]>) contains exactly <[2, 1]>. It is missing <[1]>
java.lang.AssertionError: Not true that hashtag:foo (<[2]>) contains exactly <[2, 1]>. It is missing <[1]>

Unrelated?

Patch-set: 2
Reviewer: Jonathan Nieder <1011842@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0