Update patch set 5
Patch Set 5: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 2.6s
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/change/FileTable.java:663: error: cannot find symbol
                : Gerrit.RESOURCES.editUndo()))
                                  ^
  symbol:   method editUndo()
  location: variable RESOURCES of type com.google.gerrit.client.GerritResources
Errors: 1. Warnings: 0.
BUILD FAILED: //gerrit-gwtui:ui_module failed with exit code 1:
...

Patch-set: 5
Label: Verified=-1