Update patch set 1
Patch Set 1:

> CI environment flaky?
 > <=>
 > Failed when trying to copy: cp /home/jenkins/jobs/Gerrit-verifier-default/workspace/lib/jgit/buck-out/gen/org.eclipse.jgit/jgit__download_src/jgit/org.eclipse.jgit-4.3.0.201604071810-r-src.jar
 > buck-out/gen/org.eclipse.jgit/jgit/jgit#gwt_module-gwt.jar
 > java.nio.file.NoSuchFileException: /home/jenkins/jobs/Gerrit-verifier-default/workspace/lib/jgit/buck-out/gen/org.eclipse.jgit/jgit__download_src/jgit/org.eclipse.jgit-4.3.0.201604071810-r-src.jar

Currently, all changes get -1 because of that error.

Patch-set: 1