Update patch set 2
Patch Set 2:

(1 comment)

> I cherry-picked this on top of stable-2.11 and it doesn't compile.
 > I'm getting many messages like:
 > 
 > /home/orgads/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/project/ListDashboards.java:87:
 > error: try-with-resources not applicable to variable type
 > RevWalk rw = new RevWalk(git)) {
 > ^
 > required: java.lang.AutoCloseable
 > found:    org.eclipse.jgit.revwalk.RevWalk

That's because in JGit 3.7.0.201502260915-r.58-g65c379e from Google storage bucket was patched with number of commits compare to official JGit 3.7.0 from Maven central. Particularly it contains this change: [1]. IOW, 3.7.1.201504261725-r JGit release must be patched again to be used for 2.11, or this change: [2] must be reverted on stable-2.11, that makes use of patched stuff. I don't know, what other commits the patched JGit version contains, though. I think it should be documented by release engineer and this documentation should be available for everyone. Something like "JGit 3.7.0.201502260915-r.58-g65c379e is based on official 3.7.0.201502260915-r + these commits: foo, bar, baz".

* [1] https://git.eclipse.org/r/40463
* [2] https://gerrit-review.googlesource.com/66624

Patch-set: 2
Label: Verified=0