Fix RBE build failure for plugins
In change 315122 we started seeing RBE errors when trying to build
the delete-project plugin, which was recently converted to a
TypeScript based build. The error is:

ERROR: .../Gerrit-verifier-bazel/gerrit/plugins/delete-project/BUILD:49:17:
  Bundling JavaScript plugins/delete-project/gr-delete-repo-bundle.js [rollup] failed: ......
Error: '@gerritcodereview/typescript-api/gerrit' is imported by
  .../gr-delete-repo/plugin.js, but could not be resolved

Apparently this error does not happen locally or in other CI builds.
Dmitrii suggested passing in npm dep sources explicitly into
rollup_bundle(), which is what we do here. And it fixes the issue! :-)

Change-Id: I31b66afe3542dcb63ac14bebb1f1c8a330a390bd