Update patch set 3
Patch Set 3:

Do we have flaky tests?
see the failure below.

1) removeNotExistingHashtag(com.google.gerrit.acceptance.rest.change.HashtagsIT)
java.lang.AssertionError: Not true that <[tag1]> contains exactly <[tag1, tag2, tag3]>. It is missing <[tag2, tag3]>

Patch-set: 3