Revert "Upgrade jruby to version 9.4.0.0"
This reverts commit 56e23bd35b012e45574ff580a7cd07b6704fbed6.

Reason for revert: Breaks the CI build [1]

[1]
1): asciidoc failed: error executing command bazel-out/k8-opt-exec-FB83C324/bin/java/com/google/gerrit/asciidoctor/asciidoc --mktmp -z bazel-out/k8-fastbuild/bin/Documentation/html_htmlonly.zip --in-ext .txt.html_htmlonly_expn --out-ext .html -b ... (remaining 227 arguments skipped)
Exception in thread "main" java.lang.NoSuchMethodError: 'org.jruby.runtime.backtrace.BacktraceElement[] org.jruby.runtime.ThreadContext.getBacktrace()'
	at org.asciidoctor.log.internal.JavaLogger.createLogRecord(JavaLogger.java:97)
	at org.asciidoctor.log.internal.JavaLogger.add(JavaLogger.java:87)
	at org.asciidoctor.log.internal.JavaLogger$INVOKER$i$0$2$add.call(JavaLogger$INVOKER$i$0$2$add.gen)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:329)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:561)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:363)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:66)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:82)
        ...

Change-Id: I88b72788389f69de24c32c40f09bb47dd287e069