TooManyTermsInQueryException: Re-Add constructors
Two constructors were removed in change If38623aab but these have
internal usages at Google, hence bringing them back.

Release-Notes: skip
Change-Id: I131136f2a906b1a966264d70427fcbaa4d1d5336