Update patch set 4
Patch Set 4: Verified-1

One of the tests needed to be adapted since the HTML after the cleaning step doesn't contain the 'html' tag anymore.

Running the test from Eclipse succeeds now, but ProjectDocumentationIT fails when executed from

  buck test --all

The reason for the failure is:

  java.lang.NoClassDefFoundError: org/w3c/css/sac/DocumentHandler

This class is contained in the gwt-user-2.5.1.jar, but the acceptance tests don't depend on it (I guess they shouldn't?). I believe this class could also be retrieved from the xml-apis jar (which is available on Maven Central) but I fail to add the dependency to this jar in the correct place so that the tests would work...

Patch-set: 4
Label: Verified=-1