Update patch set 6
Patch Set 6:

@David Pursehouse would you know how i can get the match part to work? it kept failing because it could not do 

INFO: Found 1 target...
ERROR: /Users/patrickmulhall/Documents/workspace/gerrit/gerrit-server/BUILD:28:1: Building gerrit-server/libserver-class.jar (1420 source files) failed: Worker process sent response with exit code: 1.
gerrit-server/src/main/java/com/google/gerrit/server/plugins/ListPlugins.java:172: error: no suitable method found for filter(PluginLoader,(p)->p.get[...].US)))
      return Iterables.filter(
                      ^
    method Iterables.<T#1>filter(Iterable<T#1>,Predicate<? super T#1>) is not applicable
      (cannot infer type-variable(s) T#1
        (argument mismatch; PluginLoader cannot be converted to Iterable<T#1>))
    method Iterables.<T#2>filter(Iterable<?>,Class<T#2>) is not applicable
      (cannot infer type-variable(s) T#2
        (argument mismatch; PluginLoader cannot be converted to Iterable<?>))
  where T#1,T#2 are type-variables:
    T#1 extends Object declared in method <T#1>filter(Iterable<T#1>,Predicate<? super T#1>)
    T#2 extends Object declared in method <T#2>filter(Iterable<?>,Class<T#2>)
Target //:release failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 43.420s, Critical Path: 43.21s


please?

I've since changed it since then to not use .contains as it did not work. Not sure how to get this part to work.

Patch-set: 6
Reviewer: Paladox none <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>