Update patch set 7
Patch Set 7:

> When trying to run the tests I hit an error:
 > 
 > $ bazel test --define jgit-dev=1 //...
 > ERROR: /private/var/tmp/_bazel_d029788/7bad2a2008c0528ccb0e391a73771531/external/jgit/lib/BUILD:43:1:
 > no such package '@hamcrest_library//jar': error loading package
 > 'external': The repository named 'hamcrest_library' could not be
 > resolved and referenced by '@jgit//lib:hamcrest-library'.

Thanks for the reporting. Not sure how I missed that one. I did run the tests, but apparently not all of them ;-(.

So the issue is that in jgit not only hamcrest-core, but also hamcrest-library is used. Due to this Bazel issue: [1] the dependency are resolved in gerrit and not in jgit. The workaround for that problem is, when jgit develeopment tree is activated in addition to provided instructions, in the dev-bazel.txt, this dependency definition should be added to the WORKSPACE file in gerrit:

  maven_jar(
      name = "hamcrest_library",
      artifact = "org.hamcrest:hamcrest-library:1.3",
      sha1 = "4785a3c21320980282f9f33d0d1264a69040538f",
  )

I will upload documentation fix in a moment.

* [1] https://github.com/bazelbuild/bazel/issues/2391

Patch-set: 7
Reviewer: David Ostrovsky <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>