Fix updating and publishing draft comment on old patch set
If an existing draft comment on an old patch set is updated and at the
same time published by making a Post Review request on the current patch
set with DraftHandling = PUBLISH_ALL_REVISIONS the request was failing
with 500 ISE.

The exception was:
java.lang.IllegalArgumentException: cannot set commit ID for patch set
<change-id>,<patch-set-num> on comment ...
  at com.google.common.base.Preconditions.checkArgument(Preconditions.java:451)
  at com.google.gerrit.server.CommentsUtil.setCommentCommitId(CommentsUtil.java:351)
  at com.google.gerrit.server.restapi.change.PostReviewOp.resolveInputCommentsAndDrafts(PostReviewOp.java:415)
  at com.google.gerrit.server.restapi.change.PostReviewOp.insertComments(PostReviewOp.java:342)
  at com.google.gerrit.server.restapi.change.PostReviewOp.updateChange(PostReviewOp.java:261)
  ...

The failure happened in CommentsUtil#setCommentCommitId which populates
the commit ID in the comment if it's not set already. If the commit ID
is not set it uses the change, the patch set on which the Post Review
request was done (i.e. the current patch set) and the comment side to
determine the commit ID. For this it's important that the patch set
matches with the patch set on which the comment was applied. This is
verified via checkArgument. This check fails if an draft comment on an
old patch set is updated and published, because its patch set (the old
patch set) doesn't match with the patch set on which the Post Review
request was done (i.e. the current patch set).

To fix this we do the checkArgument check only if the comment doesn't
have a commit ID yet. This way the checkArgument check is skipped for
draft comments that are updated, since draft comments always have a
commit ID already set. The commit ID can only be missing for comments
which are provided in the request input and which don't exist as a draft
comment yet.

Bug: Google b/298706943
Change-Id: I066073498d85aa4efd0c10253674894c06b86098
Signed-off-by: Edwin Kempin <ekempin@google.com>
Release-Notes: Fixed updating and publishing draft comment on old patch set