Add PluginServletContext#getVirtualServerName
Gerrit is using some magic, to be compatible with both servlet API 3.1
with Jetty, and servlet-api 2.5 for Google Web Server.
But PluginServletContext doesn't have this method which causes

NoSuchMethodException: com.google.gerrit.httpd.plugins.
  PluginServletContext$API.getVirtualServerName()

each time when a plugin is loaded.

We run Gerrit on Tomcat 8.5.69.
We also have some Gerrit servers running on embedded Jetty. There we
don't observe these exceptions.

Bug: Issue 14968
Change-Id: I8cb865df8e7b626ee1c1b3028f8af3d39bbea1fd