Update patch set 3
Patch Set 3:

> I think this breaks the build on master:
 > 
 > hiesel@hiesel:~/gerrit(master)$ bazel build //...
 > ERROR: /usr/local/google/home/hiesel/gerrit/javatests/com/google/gerrit/elasticsearch/BUILD:30:2:
 > no such target '//javatests/com/google/gerrit/server:abstract_query_tests':
 > target 'abstract_query_tests' not declared in package
 > 'javatests/com/google/gerrit/server' defined by /usr/local/google/home/hiesel/gerrit/javatests/com/google/gerrit/server/BUILD
 > and referenced by '//javatests/com/google/gerrit/elasticsearch:elasticsearch_accounts_test'

Thanks for letting us know. Investigating. Can it be that ES tests don't run on CI? I'm asking, because the CI was green wth this change.

Patch-set: 3
Reviewer: David Ostrovsky <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>