Fix NPE when listing change comments that have the same context
CommentContextCacheImpl.Loader#loadForSameChange gets a list of
CommentContextKey's as input and should return CommentContext's for
these keys, as a Map<CommentContextKey, CommentContext>. Callers expect
that each key that they pass in can be found in the returned map.
However if the CommentContext was the same for multiple keys, this
context was only returned for one of the keys and the other keys were
missing in the map. Due to this callers run into NPE's when they tried
to lookup the CommentContext for keys that were missing (e.g. [1]).

CommentContextCacheImpl.Loader#loadForSameChange missed to return some
keys, because for the computation it created a Map<ContextInput,
CommentContextKey> and when putting entries into this map previous
entries got overridden when keys had the same ContextInput. Since the
keys in this map were used to create the result, some keys were missing
in the result.

[1]
    java.lang.NullPointerException: null value in entry: CommentContextKey{project=myproject, changeId=286427113, id=c70baa47_54c6afa7, path=/PATCHSET_LEVEL, patchset=3, contextPadding=3}=null
      at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:35)
      at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:188)
      at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:298)
      at com.google.gerrit.server.comment.CommentContextCacheImpl.getAll(CommentContextCacheImpl.java:122)
      at com.google.gerrit.server.restapi.change.CommentJson$BaseCommentFormatter.addCommentContext(CommentJson.java:172)
      at com.google.gerrit.server.restapi.change.CommentJson$BaseCommentFormatter.format(CommentJson.java:143)
      at com.google.gerrit.server.restapi.change.CommentJson$HumanCommentFormatter.format(CommentJson.java:241)
      at com.google.gerrit.server.restapi.change.ListChangeComments.getAsMap(ListChangeComments.java:105)
      at com.google.gerrit.server.restapi.change.ListChangeComments.apply(ListChangeComments.java:83)
      at com.google.gerrit.server.restapi.change.ListChangeComments.apply(ListChangeComments.java:38)
      ...

Signed-off-by: Edwin Kempin <ekempin@google.com>
Change-Id: I49ac2e5f9492410af5015a8705bc1040b18d6182