Update patch set 15
Patch Set 15:

> Patch Set 15: Verified-1
> 
> As I was currently rerunning these tests, I just noticed the very recent disappearance of the V6 alpine image used in this amended change. -Getting an exception when trying to createAndStart that container in ElasticContainer:
> 
> org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=elasticsearch:6.2.4-alpine).
> 
> And reverting to the previously used image does not currently work either (Issue 9212).
> This means that the work described in that issue needs to start as soon as possible.

Work started. As we speak, testing with the currently supported V6 image [1] works without security hassles, not anymore. Maybe they amended their images array since I started amending this change. Anyway, I will push another amend to this change, along with a documentation paragraph proposal for the virtual memory part.

Another /follow-up change will then be needed, to amend the other two deprecated images (V2 and V5), which are still available currently btw -unlike the V6 one.

[1] docker.elastic.co/elasticsearch/elasticsearch:6.2.4

Patch-set: 15
Reviewer: Marco Miller <1012732@173816e5-2b9a-37c3-8a2e-48639d4f1153>