Update patch set 10
Patch Set 10:

> > Patch Set 10: Verified-1
 > >
 > > (1 comment)
 > >
 > > bazel build of this change is failing:
 > >
 > > $ bazel buildg gerrit
 > > ...
 > > java/com/google/gerrit/server/config/ConfigUpdatedEvent.java:17:
 > error: package com.google.gerrit.sshd.commands does not exist
 > > import com.google.gerrit.sshd.commands.ReloadConfig;
 > 
 > Yes. The {@link} wanted the package. Eclipse accepted it, but not
 > bazel.

We need to remove the import, we cannot add a dependency from server to sshd.

Patch-set: 10