Fix errors introduced by TypeScript 4.7
error TS2731: Implicit conversion of a 'symbol' to a 'string' will
fail at runtime. Consider wrapping this expression in 'String(...)'.`

Release-Notes: skip
Change-Id: I5b9d48d5d1c1e23bd3fde551e406a6feb1e4d20b