Fixes for Typescript 4.2
Typescript 4.2 reports the following errors without fixes:
  gr-repo-access.ts(302,59): error TS2339: Property 'name' does not
    exist on type 'never'.
  date-util.ts(166,47): error TS2345: Argument of type 'Options' is
    not assignable to parameter of type 'DateTimeFormatOptions'.
    Types of property 'year' are incompatible.

Change-Id: I2387d5664c6748a1194ca52a0560d1d961ca64e4
(cherry picked from commit aab9825b89fe99ef57c940aa67711ff195320efc)