Update patch set 2
Patch Set 2:

> gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/server/change/ConsistencyCheckerIT.java:68:
 > error: cannot find symbol
 > (InMemoryRepository) repoManager.openRepository(project));
 > ^
 > symbol:   class InMemoryRepository
 > location: class com.google.gerrit.acceptance.server.change.ConsistencyCheckerIT
 > Errors: 1. Warnings: 0.

The import of InMemoryRepository is missing.  There are also several unused imports.

Patch-set: 2