Update patch set 35
Patch Set 35:

The deprecated `org.apache.lucene.util.Version.LUCENE_3_6` was removed in Lucene 5.0 but is still referenced from Elasticsearch.  This causes a NoSuchFieldError:

 java.lang.NoSuchFieldError: LUCENE_3_6
 	at org.elasticsearch.Version.<clinit>(Version.java:43)

This has been fixed in Elasticsearch, but that fix is not included in the latest release (1.5.0).

Patch-set: 35