Update patch set 2
Patch Set 2: Verified+1

I was doing some tests to verify this change.

TEST PLAN:
- setup a local SMTP server (I installed Postfix as described in [1])
- create a self-signed certificate and use it for the SMTP server (described in [1])
- when creating the certifacte you must provide some input data, the value for CN is important,
  do the test once with CN = <your-host-name> and once with CN = <other-host-name>
- configure the SMTP server with TLS encryption in gerrit.config:
[sendemail]                                                            
  smtpServer = <your-host-name>                         
  smtpEncryption = tls      
- do an action in Gerrit that triggers an email notification (e.g. comment on a change of another user)

RESULT WITHOUT THIS FIX:
- for both certificates sending the email fails with
  javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed:   
    sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
This error means that the certificate is missing in the trust store [2] and
this is the expected result since we didn't add the certificate to the trust store.

RESULT WITH THIS FIX:
- for CN = <your-host-name> we get the same failure as described above
- for CN = <other-host-name> it is now failing earlier with
  javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No name matching <other-host-name> found
As explained in [2] this error is raised when there is a mismatch of the host names.

This shows that without the fix we did not verify the host name and the fix works as intended.

[1] https://help.ubuntu.com/community/Postfix
[2] http://java.globinch.com/enterprise-java/security/fix-java-security-certificate-exception-no-matching-localhost-found/

Patch-set: 2
Reviewer: ekempin <1003935@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=+1