Set up Eclipse to work with Java 9
Auto-value doesn't work with Eclipse-Oxygen and Java 9: [1]. To fix
it, apply provided patches from this PR[2] to auto-value tree:

* 0001-Add-a-static-overrides-method-to-MoreElements-that-u.patch
* 0002-Have-CHANGES.md-explain-that-it-is-obsolete.patch
* 0003-Adjust-AutoValueTest-so-that-it-covers-setting-an-im.patch
* 0004-Template-arguments-should-not-be-null.patch

To build and install snapshot auto-value version, run:

  $ mvn -Dmaven.test.skip=true install

To create .classpath with java 9, run:

  $ tools/eclipse/project.py --java9

Start Eclipse-Oxygen, and now Gerrit project can be built with Java 9.

To run gerrit from Eclipse, the system classpath is cast to
URLClassLoader to retrieve the needed JARs. In Java 9 system classpath
cannot be cast to URLClassLoader. To rectify, extract the classpath from
Bazel. Currently this would also add compiled source JARs, that we don't
want to be added and should be rather filtered out to support hot
deployment (Gerrit own classes should be rather be loaded from the
Eclipse's classes directory).

To load Gerrit dependency from the external repositories bazel's
output_base path is needed. Hard code it for now and find a way to
retrieve it programmatically later.

This still doesn't work. The error we are getting during the start is:
[3]:

[2018-06-26 08:39:32,697] [main] ERROR com.google.gerrit.pgm.Daemon : Unable to start daemon
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getProcessCpuTime() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @5b3f61ff

^^^ We need to find a way to pass corresponding parameters to Java 9
runtime.

[1] https://github.com/google/auto/issues/645
[2] https://github.com/google/auto/pull/646
[3] http://paste.openstack.org/show/724279

Change-Id: Ie341cd4dfee5520f689fc50f34aa5395b74b5e7d