Fix IllegalStateException whilst updating user link to external ids
When using HTTP authentication + auth.httpExternalIdHeader the user
link update to its external ID was generating a IllegalStateException
because of the username not being set in the AuthRequest.

StackTrace was:
java.lang.IllegalStateException: Username cannot be changed.
 at c.g.g.s.a.ChangeUserName.call(ChangeUserName.java:78)
 at c.g.g.s.a.AccountManager.update(AccountManager.java:162)
 at c.g.g.s.a.AccountManager.link(AccountManager.java:331)
 at c.g.g.s.a.AccountManager.updateLink(AccountManager.java:386)
 at c.g.g.h.a.c.HttpLoginServlet.updateRemoteExternalId(HttpLoginServlet.java:159)

It was actually a regression on the AccountManager update that was
always to try updating the full profile even if the AuthRequest included
only the external id.

Change-Id: Ie0f36d9a74415f937f3f2b7e6cfc5f538b12f250