ChangeSet: don't support different users
We were running into 500s for non identified users on hosts with
submitWholeTopic disabled:

java.lang.IllegalStateException: user already specified: IdentifiedUser[account XXXXX]
        at com.google.gerrit.server.query.change.ChangeData.changeControl(ChangeData.java:691)
        at com.google.gerrit.server.git.ChangeSet.<init>(ChangeSet.java:66)
        at com.google.gerrit.server.git.MergeSuperSet.completeChangeSetWithoutTopic(MergeSuperSet.java:169)
        at com.google.gerrit.server.git.MergeSuperSet.completeChangeSet(MergeSuperSet.java:103)
        at com.google.gerrit.server.change.SubmittedTogether.getForOpenChange(SubmittedTogether.java:139)
        at com.google.gerrit.server.change.SubmittedTogether.apply(SubmittedTogether.java:91)
        at com.google.gerrit.server.change.SubmittedTogether.apply(SubmittedTogether.java:51)
        at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:331)

This happened because we called `cd.changeControl(user)` in ChangeSet.

However we do not need to make use of passing in a potentially new
user as it is always the same user in one request, so
`cd.changeControl()` is sufficient (and that doesn't throw 500s).

To make clear we don't fiddle with different users, replace the
`user` argument in ChangeSet by a boolean indicating if we want to
have the full set or if we want to have the restricted set.

Tests are WIP, as they don't fail before this change.

Change-Id: Id4c767a62ddc16ed211d4ea084b17bfaee3b4b6d