CreateNewChangeForAllNotInTarget: Fix working with change series
If a change is pushed that depends on an open change and both changes
are targeted to the same destination branch, we don't want to recreate
the base change for the same branch if the
CreateNewChangeForAllNotInTarget project option is set to true. We also
don't want to do any validation of the base change as it is not touched
by the upload of a successor change.

At the moment trying to push a change that depends on an open change of
another user fails with "invalid committer" if the uploading user
doesn't have the Forge Committer access right. This is because
CreateNewChangeForAllNotInTarget wrongly attempts to create a new change
for the base change, and hence does validation for the commit of the
base change. The error message for the base change is:

invalid committer

ERROR:  In commit 683c42e4ba60ffa68c820de9064b6c36238600c4
ERROR:  committer email address other.user@example.com
ERROR:  does not match your user account.
ERROR:
ERROR:  The following addresses are currently registered:
ERROR:    user@example.com
ERROR:
ERROR:  To register an email address, please visit:
ERROR:  http://localhost:0/#/settings/contact

This is confusing to the user who only uploaded a successor change but
didn't touch the base change.

Change-Id: I04e25b5eb09e0c9540652c93eb1408d2fab39f6b
Signed-off-by: Edwin Kempin <ekempin@google.com>