Update patch set 4
Patch Set 4: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 2.6s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/change/EditMessage.java:87: error: exception com.google.gerrit.server.patch.PatchSetInfoNotAvailableException is never thrown in body of corresponding try statement
    } catch (MissingObjectException | IncorrectObjectTypeException
      ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Errors: 1. Warnings: 0.
BUILD FAILED: //gerrit-server:server failed with exit code 1:
...

Patch-set: 4
Label: Verified=-1