Update patch set 10
Patch Set 10: Verified+1

Generally most things are working fine. I just had a few error for corner cases:

 * if path is a submodule link, I get a error 500:

  [2014-08-27 16:50:56,763] ERROR com.google.gerrit.httpd.restapi.RestApiServlet : Error in GET /changes/91/edit/test
  org.eclipse.jgit.errors.MissingObjectException: Missing unknown 903a95c69f78b55f97e50c0c8a11322e83329cb5
          at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:148)
          at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:177)
          at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:147)
           .....

 * trying to get non-existing patn from git, gives a rather unspecific error on firts hit, after set, I just get a 'working box'

Patch-set: 10
Reviewer: Björn Pedersen <1011624@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=+1