Bazel: Prepare Eclipse classpath generation
Comment out the tests targets for now, as in Bazel java_library cannot
depend on java_test:

ERROR: (11-13 07:48:23.239)
/home/davido/projects/gerrit/tools/eclipse/BUILD:5:10: in deps attribute
of java_library rule //tools/eclipse:classpath: '//gerrit-gpg:gpg_tests'
does not have mandatory provider 'link_params' and java_test rule
'//gerrit-gpg:gpg_tests' is misplaced here (expected cc_binary,
cc_library, genrule, genproto, java_import, java_library,
java_proto_library, java_lite_proto_library, proto_library, sh_binary or
sh_library).

Change-Id: I984068350244ee9d66807e4bc8c6779b34a26bab