Fix capabilities acceptance test broken by batch changes limit
This was missed before in Ic929dc4 and the acceptance tests are
currently broken:
  FAILURE testCapabilitiesUser: batchChangesLimit
  java.lang.NoSuchFieldException: batchChangesLimit

Add handling of the batch changes limit field in the acceptance
test.

Change-Id: I486864594cbccaaf0a6f14f14c0b5bc7107e580d