Update patch set 5
Patch Set 5:

This breaks tools/eclipse/project.py:

 $ ./tools/eclipse/project.py
 [-] PARSING BUCK FILES...FINISHED 0.1s
 [2016-04-20 15:02:17.583][error][command:c98d0711-2cd0-4446-a847-a460a5396356][tid:1029][com.facebook.buck.cli.Main] Uncaught exception at top level
 java.lang.IllegalStateException: Raw data claims to come from [org.eclipse.jgit.archive], but we tried rooting it at [lib/jgit/org.eclipse.jgit.archive].
         at com.facebook.buck.parser.ParsePipeline.parseBuildTargetFromRawRule(ParsePipeline.java:556)
         at com.facebook.buck.parser.ParsePipeline$1.apply(ParsePipeline.java:222)
         at com.facebook.buck.parser.ParsePipeline$1.apply(ParsePipeline.java:1)
         at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
         at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
         at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
         at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
         at com.google.common.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:153)
         at com.google.common.util.concurrent.Futures.transformAsync(Futures.java:1108)
         at com.facebook.buck.parser.ParsePipeline.getAllTargetNodesJob(ParsePipeline.java:208)
         at com.facebook.buck.parser.PerBuildState.getAllTargetNodesJob(PerBuildState.java:175)
         at com.facebook.buck.parser.Parser.resolveTargetSpecs(Parser.java:450)
         at com.facebook.buck.parser.Parser.buildTargetGraphForTargetNodeSpecs(Parser.java:359)
         at com.facebook.buck.cli.BuildCommand.createActionGraphAndResolver(BuildCommand.java:389)
         at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:320)
         at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:279)
         at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:168)
         at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:90)
         at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1036)
         at com.facebook.buck.cli.Main.tryRunMainWithExitCode(Main.java:1494)
         at com.facebook.buck.cli.Main.runMainThenExit(Main.java:1579)
         at com.facebook.buck.cli.Main.nailMain(Main.java:1694)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:497)
         at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)

Patch-set: 5