Add missing space to exception message for Prolog rule error
If an error occurs while executing a Prolog rule we now fail with

com.google.gerrit.exceptions.StorageException: Submit type rule failed: RULE_ERROR (Error evaluating project rules, check server log)

instead of

com.google.gerrit.exceptions.StorageException: Submit type rule failed: RULE_ERROR(Error evaluating project rules, check server log)

Signed-off-by: Edwin Kempin <ekempin@google.com>
Change-Id: Ic5947f83675c837717dd2ea59ace2590ee63b35b