Update patch set 2
Patch Set 2: Code-Review+1

More context: this is happening in production.

 Can't update the superprojects
 com.google.gerrit.server.git.SubmoduleException: Cannot update gitlinks
        at  com.google.gerrit.server.git.SubmoduleOp.updateSuperProjects(SubmoduleOp.java:355)
        at com.google.gerrit.server.git.ReceiveCommits.processCommands(ReceiveCommits.java:673)
        at com.google.gerrit.server.git.AsyncReceiveCommits$Worker.run(AsyncReceiveCommits.java:89)
 Caused by: com.google.gerrit.server.git.UpdateException: java.lang.IllegalStateException: ObjectDatabase must not be closed
        at com.google.gerrit.server.git.BatchUpdate.executeUpdateRepo(BatchUpdate.java:726)
        at com.google.gerrit.server.git.BatchUpdate.execute(BatchUpdate.java:425)
        at com.google.gerrit.server.git.SubmoduleOp.updateSuperProjects(SubmoduleOp.java:351)
        ... 16 more
 Caused by: java.lang.IllegalStateException: ObjectDatabase must not be closed

Patch-set: 2
Reviewer: Jonathan Nieder <1011842@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=+1