Update patch set 1
Patch Set 1:

Not 100% sure but I think this might be causing a problem.

If I try to upload a new patch set to a change, I get "internal server error", and in the log:

 [2013-01-09 18:16:02,593] ERROR com.google.gerrit.server.git.ReceiveCommits : Can't insert changes for another-test
 com.google.gwtorm.server.OrmException: Error updating database
         at com.google.gerrit.server.git.ReceiveCommits$1.apply(ReceiveCommits.java:227)
         at com.google.gerrit.server.git.ReceiveCommits$1.apply(ReceiveCommits.java:221)
         at com.google.common.util.concurrent.Futures$MappingCheckedFuture.mapException(Futures.java:1246)
         at com.google.common.util.concurrent.AbstractCheckedFuture.checkedGet(AbstractCheckedFuture.java:85)
         at com.google.gerrit.server.git.ReceiveCommits.insertChangesAndPatchSets(ReceiveCommits.java:700)
         at com.google.gerrit.server.git.ReceiveCommits.processCommands(ReceiveCommits.java:543)
         at com.google.gerrit.server.git.AsyncReceiveCommits$Worker.run(AsyncReceiveCommits.java:90)
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
         at com.google.gerrit.server.util.RequestScopePropagator$5.call(RequestScopePropagator.java:222)
         at com.google.gerrit.server.util.RequestScopePropagator$4.call(RequestScopePropagator.java:201)
         at com.google.gerrit.server.util.ThreadLocalRequestScopePropagator$1.call(ThreadLocalRequestScopePropagator.java:55)
         at com.google.gerrit.server.util.RequestScopePropagator$1.call(RequestScopePropagator.java:98)
         at com.google.gerrit.server.util.RequestScopePropagator$2.run(RequestScopePropagator.java:131)
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
         at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
         at java.util.concurrent.FutureTask.run(FutureTask.java:138)
         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
         at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:337)
         at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
         at java.lang.Thread.run(Thread.java:662)
 Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Failed to create ref refs/changes/32/132/2 in /home/CORPUSERS/22708925/work/gerrit_tests$
         at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
         at java.util.concurrent.FutureTask.get(FutureTask.java:83)
         at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:63)
         at com.google.common.util.concurrent.AbstractCheckedFuture.checkedGet(AbstractCheckedFuture.java:78)
         ... 18 more
 Caused by: java.io.IOException: Failed to create ref refs/changes/32/132/2 in /home/CORPUSERS/22708925/work/gerrit_testsite/git/another-test.git: NO_CHANGE
         at com.google.gerrit.server.git.ReceiveCommits$ReplaceRequest.insertPatchSet(ReceiveCommits.java:1753)
         at com.google.gerrit.server.git.ReceiveCommits$ReplaceRequest$1.call(ReceiveCommits.java:1642)
         at com.google.gerrit.server.git.ReceiveCommits$ReplaceRequest$1.call(ReceiveCommits.java:1637)
         at com.google.gerrit.server.util.RequestScopePropagator$1.call(RequestScopePropagator.java:96)
         at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
         at java.util.concurrent.FutureTask.run(FutureTask.java:138)
         at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:262)
         at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:55)
         at com.google.gerrit.server.git.ReceiveCommits$ReplaceRequest.insertPatchSet(ReceiveCommits.java:1636)
         at com.google.gerrit.server.git.ReceiveCommits.insertChangesAndPatchSets(ReceiveCommits.java:691)
         ... 17 more

Patch-set: 1