Update patch set 6
Patch Set 6: Verified+1

Upgrading to this version on a site without index support, produces. It is kind expected. May be we can improve the error message?

  com.google.inject.ProvisionException: Guice provision errors:
  1) No index versions ready; run Reindex

Patch-set: 6