Update patch set 1
Patch Set 1: Library-Compliance+1

I see this exception when building Gerrit with this change:

xception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:62)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/datatype/jdk7/Jdk7Module
	at com.facebook.buck.cli.Main.<init>(Main.java:622)
	at com.facebook.buck.cli.Main.main(Main.java:1723)
	... 5 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.datatype.jdk7.Jdk7Module
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

Patch-set: 1
Label: Library-Compliance=+1