Revert "Expose instanceName in the subject template"
This reverts commit eb4d2d8da7bfc29511154fffe19f89f769a6a03c.

Reason for revert:

we observe

com.google.template.soy.tofu.SoyTofuException: In 'print' tag, expression "$instanceAndProjectName" evaluates to undefined.
        at com.google.gerrit.server.mail.template.ChangeSubject(ChangeSubject.soy:9)

in production

Change-Id: I1701b5bcb4720086783536c5c987866bf73e54f4