Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > > Patch Set 2:
> > > 
> > > > Patch Set 2:
> > > > 
> > > > Well, the CI would just build that change and run the tests. Can someone verify it manually and vote VRFY+1? We could skip then the CI and move forward here, by merging this change to stable-2.10, stable-2.11, stable-2.12 and stable-2.13.
> > > 
> > > Unfortunately I don't have any local environment to test these old branches,
> > 
> > Well, I don't have Java 7 on my machine too. However, if you have docker daemon on your machine, you could download GerritForge CI image, run the docker image, clone gerrit, apply this change, set-up java 7 and build this change with Buck and run the tests with `buck test --all`.
> 
> I can do it tonight.

Verifying it now on GerritForge docker image.

Wenn I do su - jenkins and set java 7 and buck 7, and just build buck build :release, then it's failing with wrong encoding:

  GitWebConfig.java:217: error: unmappable character for encoding ASCII
   * Reasoning: http://www.ietf.org/rfc/rfc1738.txt ?? 2.2:

Setting LANG=en_US.UTF-8 and exporting LANG fixed it. Still I wonder why it
is missing and where it's set on the CI side?

I started the CI image like this:

  $ docker run --privileged -it gerritforge/gerrit-ci-slave-bazel:debian-jessie bash

Patch-set: 2
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>