Avoid 500s when a topic includes patch sets that are not visible
I560508c8d94 (Avoid 500s when a topic includes changes that are not
visible, 2016-06-15) forgot that even when a change is visible, it
is possible for its current patch set not to be visible:

 com.google.gwtorm.server.OrmException: Failed to get submit type for 78957: Patch set 78957,2 not found
	at com.google.gerrit.server.git.MergeSuperSet.logErrorAndThrow(MergeSuperSet.java:245)
	at com.google.gerrit.server.git.MergeSuperSet.completeChangeSetWithoutTopic(MergeSuperSet.java:140)
	at com.google.gerrit.server.git.MergeSuperSet.completeChangeSetIncludingTopics(MergeSuperSet.java:199)
	at com.google.gerrit.server.git.MergeSuperSet.completeChangeSet(MergeSuperSet.java:104)
	at com.google.gerrit.server.change.GetRevisionActions.getETag(GetRevisionActions.java:75)

We can think of a non-visible draft patch set on a change as a proposed
edit that the current user does not need to be aware of.  Until the
draft patch set is made visible, it should not enter into the calculation
of the list of changes to be submitted together.  Use the most current
visible patch set instead.

If there is no visible patch set on the change (for example because it
was a draft that was abandoned and revived), there is no good answer:

* we do not want to hide the change from the results because it is
  visible

* there is no appropriate patch set in the change to use to continue
  traversal

On such changes, use the current patch set and avoid 500s by taking
advantage of the existing workaround for inability to retrieve the
submit type on a non-visible patch set.

Change-Id: I080cdf213b035ace6588fe3493d429f469cd72ce