Bazel: Try to fix building PolyGerrit UI using rules_nodejs
Test Plan:

1. Install yarn using:

  $ curl -o- -L https://yarnpkg.com/install.sh | bash

2. Verify, that yarn is added to the path:

  $ yarn --version
  1.21.1

3. Run:

  $ bazel build polygerrit-ui/app:polygerrit_ui.zip

This is still failing with:

ERROR: /home/davido/projects/gerrit2/polygerrit-ui/app/BUILD:9:1: Bundling JavaScript polygerrit-ui/app/gr-app-bundle-js.js [rollup] failed (Exit 1) rollup-bin.sh failed: error executing command bazel-out/host/bin/tools/node_tools/rollup-bin.sh bazel-out/k8-fastbuild/bin/polygerrit-ui/app/gr-app-prebundling-srcs/entry.js --output.file ... (remaining 10 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
loaded bazel-out/k8-fastbuild/bin/polygerrit-ui/app/_gr-app-bundle-js.rollup_config.js with warnings
(!) Unused external imports
default imported from external module 'fs' but never used

bazel-out/k8-fastbuild/bin/polygerrit-ui/app/gr-app-prebundling-srcs/entry.js → bazel-out/k8-fastbuild/bin/polygerrit-ui/app/gr-app-bundle-js.js...
[!] Error: 'polymer-bridges/polymer/polymer.html_gen.js' is imported by bazel-out/k8-fastbuild/bin/polygerrit-ui/app/gr-app-prebundling-srcs/elements/gr-app.html_gen.js, but could not be resolved – treating it as an external dependency
Error: 'polymer-bridges/polymer/polymer.html_gen.js' is imported by bazel-out/k8-fastbuild/bin/polygerrit-ui/app/gr-app-prebundling-srcs/elements/gr-app.html_gen.js, but could not be resolved – treating it as an external dependency
    at Object.onwarn (/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/sandbox/linux-sandbox/5/execroot/gerrit/bazel-out/k8-fastbuild/bin/polygerrit-ui/app/_gr-app-bundle-js.rollup_config.js:26:11)
    at Object.onwarn (/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/sandbox/linux-sandbox/5/execroot/gerrit/node_modules/rollup/dist/shared/index.js:129:25)
    at Graph.onwarn (/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/sandbox/linux-sandbox/5/execroot/gerrit/node_modules/rollup/dist/shared/index.js:129:25)
    at Graph.warn (/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/sandbox/linux-sandbox/5/execroot/gerrit/node_modules/rollup/dist/rollup.js:13256:14)
    at ModuleLoader.handleResolveId (/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/sandbox/linux-sandbox/5/execroot/gerrit/node_modules/rollup/dist/rollup.js:12311:24)
    at ModuleLoader.<anonymous> (/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/sandbox/linux-sandbox/5/execroot/gerrit/node_modules/rollup/dist/rollup.js:12197:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/sandbox/linux-sandbox/5/execroot/gerrit/node_modules/rollup/dist/shared/index.js:33:28)

Change-Id: I07ea131504fa4e28d888b5d1499715ae0c340180