Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [gerrit/try/Verify gerrit CL](https://cr-buildbucket.appspot.com/build/8787260996581610209) has failed with summary:

---
yarn run v1.22.19
$ tsc --project ./polygerrit-ui/app/tsconfig.json
polygerrit-ui/app/elements/change/gr-confirm-rebase-dialog/gr-confirm-rebase-dialog.ts(150,13): error TS2322: Type 'AccountInfo | undefined' is not assignable to type 'AccountDetailInfo | undefined'.
polygerrit-ui/app/elements/change/gr-confirm-rebase-dialog/gr-confirm-rebase-dialog.ts(150,13): error TS2322: Type 'AccountInfo | undefined' is not assignable to type 'AccountDetailInfo | undefined'.
  Property 'registered_on' is missing in type 'AccountInfo' but required in type 'AccountDetailInfo'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Patch-set: 2
Tag: autogenerated:cq:new-patchset-run:1678211889