Update patch set 2
Patch Set 2: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 3.8s
BUILD FAILED: //gerrit-launcher:launcher failed on step javac with an exception:
invalid source release: 8
java.lang.IllegalArgumentException: invalid source release: 8
	at com.sun.tools.javac.main.RecognizedOptions$GrumpyHelper.error(RecognizedOptions.java:88)
	at com.sun.tools.javac.main.RecognizedOptions$9.process(RecognizedOptions.java:348)
	at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:242)
	at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:199)
...

Patch-set: 2
Reviewer: Diffy Cuckoo (Automated Verifier) <1012977@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1