Update git submodules
* Update plugins/delete-project from branch 'master'
  to c9894f60c6fa55bf4a93f6aaf9ea35f1e08f7486
  - ConfigurationTest: Remove flaky invalidTargetArchiveFolder test
    
    This test is failing when running gerrit test in docker image with root
    user. It's also failing when remote build execution is used (BuildBuddy
    provider).
    
    It seems to rely on the fact that the exception is thrown:
    
    java.nio.file.FileSystemException: /\\\: Operation not permitted
    
    However when the test is executed with BuildBuddy RBE that exception is
    not raised and as a consequence of that the test ends up failing. It
    looks that the folder /\\\ is created in the remote executor.
    
    While it could be fixed with:
    
    exec_properties = {
        "dockerUser": "nobody",
    },
    
    we prefer not to complicate our build toolchain and rather remove the
    test.
    
    Change-Id: I51bccdf2cb19559690d3d88bd92cf60bc28f5fcd