Revert "Fix eclipse warnings"
This reverts commit 3175942514602f3c6c0e4441ff37a762af2841b0.

Reason for revert: this change leads to breakages inside google. We are still on BC 1.5.5

gerrit-gpg/test/java/com/google/gerrit/gpg/testutil/TestKey.java:80: error: incompatible types: Object cannot be converted to String
    return getPublicKey().getUserIDs().next();
                                           ^

Change-Id: Idc603ad379f1265da8b851afed3fdea6598bf27c