gerrit-extension-api: update deps for java_doc
 gerrit-commom:annotations was missing, resulting in:
   error: package com.google.gerrit.common does not exist
 import com.google.gerrit.common.Nullable;
                                ^
This can be seen on gerrit-ci as well.

Change-Id: I5a8e9ddeafc7e0b9d73c6feb5f4c3ed10c0b5670