DO NOT SUBMIT: Instrument approval retrieval and label normalization
It seems that seconday index corruption during ReviewDb to NoteDb
migration is related to label normalization and permission checks.
Running reindex twice on fresh NoteDb migrated site produces different
results. First time, approval values are wrong:

CRVW+1
VRFY is missing

Running this second time produces correct approval values:

CRVW+2
VRFY+1

Complete log:

$ bazel build headless
INFO: Analysed target //:headless (0 packages loaded).
INFO: Found 1 target...
Target //:headless up-to-date:
  bazel-bin/headless.war
INFO: Elapsed time: 18.163s, Critical Path: 17.88s
INFO: Build completed successfully, 8 total actions
davido@wizball:~/projects/gerrit2 (stable-2.15 *%>)$ java -jar bazel-bin/headless.war reindex --site-path ../test_site_stable_2.14
[2018-02-20 08:35:44,676] [main] INFO  com.google.gerrit.server.git.LocalDiskRepositoryManager : Defaulting core.streamFileThreshold to 1764m
[2018-02-20 08:35:45,372] [main] INFO  com.google.gerrit.server.cache.h2.H2CacheFactory : Enabling disk cache /home/davido/projects/test_site_stable_2.14/cache
Collecting accounts:    1
Reindexing accounts:    100% (1/1)
Reindexed 1 documents in accounts index in 0.2s (4.8/s)
Reindexing groups:      100% (2/2)
Reindexed 2 documents in groups index in 0.1s (21.3/s)
Collecting projects:    3
Reindexing changes: projects: 66% (2/3)+2 Looks good to me, approved
label(): Checking label permission for: label-Code-Review
getRange(): checking for range for: label-Code-Review
access(): for: label-Code-Review
[-1..+1 group Registered Users]
getRange: -1..+1
-1..+1
label(): Checking label permission for: label-Code-Review
-1..+1
com.google.gerrit.extensions.restapi.AuthException: label Code-Review=+2 not permitted
	at com.google.gerrit.server.project.ChangeControl$ForChangeImpl.check(ChangeControl.java:434)
	at com.google.gerrit.server.git.LabelNormalizer.applyRightFloor(LabelNormalizer.java:172)
	at com.google.gerrit.server.git.LabelNormalizer.normalize(LabelNormalizer.java:145)
	at com.google.gerrit.server.ApprovalCopier.getForPatchSet(ApprovalCopier.java:215)
	at com.google.gerrit.server.ApprovalCopier.getForPatchSet(ApprovalCopier.java:151)
	at com.google.gerrit.server.ApprovalCopier.getForPatchSet(ApprovalCopier.java:134)
	at com.google.gerrit.server.ApprovalsUtil.byPatchSet(ApprovalsUtil.java:396)
	at com.google.gerrit.server.query.change.ChangeData.currentApprovals(ChangeData.java:648)
	at com.google.gerrit.server.index.change.ChangeField.lambda$static$19(ChangeField.java:410)
	at com.google.gerrit.index.FieldDef.get(FieldDef.java:138)
	at com.google.gerrit.index.Schema$1.apply(Schema.java:185)
	at com.google.gerrit.index.Schema$1.apply(Schema.java:180)
	at com.google.common.collect.Iterators$5.transform(Iterators.java:757)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$4.computeNext(Iterators.java:623)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.google.gerrit.lucene.AbstractLuceneIndex.toDocument(AbstractLuceneIndex.java:289)
	at com.google.gerrit.lucene.LuceneChangeIndex.replace(LuceneChangeIndex.java:207)
	at com.google.gerrit.lucene.LuceneChangeIndex.replace(LuceneChangeIndex.java:102)
	at com.google.gerrit.server.index.change.ChangeIndexer.index(ChangeIndexer.java:207)
	at com.google.gerrit.server.index.change.AllChangesIndexer$ProjectIndexer.index(AllChangesIndexer.java:238)
	at com.google.gerrit.server.index.change.AllChangesIndexer$ProjectIndexer.lambda$call$0(AllChangesIndexer.java:225)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.google.gerrit.server.index.change.AllChangesIndexer$ProjectIndexer.call(AllChangesIndexer.java:225)
	at com.google.gerrit.server.index.change.AllChangesIndexer$ProjectIndexer.call(AllChangesIndexer.java:199)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:435)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
label(): Checking label permission for: label-Code-Review
-1..+1
label(): Checking label permission for: label-Code-Review
-1..+1
label(): Checking label permission for: label-Code-Review
-1..+1
label(): Checking label permission for: label-Code-Review
-1..+1
label(): Checking label permission for: label-Code-Review
-1..+1
label(): Checking label permission for: label-Code-Review
-1..+1
+1 Verified
label(): Checking label permission for: label-Verified
getRange(): checking for range for: label-Verified
access(): for: label-Verified
[]
getRange: +0
+0
[
  {
    "key": {
      "patchSetId": {
        "changeId": {
          "id": 1
        },
        "patchSetId": 2
      },
      "accountId": {
        "id": 1000000
      },
      "categoryId": {
        "id": "Code-Review"
      }
    },
    "value": 1,
    "granted": "Feb 10, 2018 4:19:00 PM",
    "tag": null,
    "realAccountId": null,
    "postSubmit": false
  }
Reindexing changes: projects: 100% (3/3), 100% (1/1), done
davido@wizball:~/projects/gerrit2 (stable-2.15 *%>)$ java -jar bazel-bin/headless.war reindex --site-path ../test_site_stable_2.14
[2018-02-20 08:36:09,487] [main] INFO  com.google.gerrit.server.git.LocalDiskRepositoryManager : Defaulting core.streamFileThreshold to 1764m
[2018-02-20 08:36:10,172] [main] INFO  com.google.gerrit.server.cache.h2.H2CacheFactory : Enabling disk cache /home/davido/projects/test_site_stable_2.14/cache
Collecting accounts:    1
Reindexing accounts:    100% (1/1)
Reindexed 1 documents in accounts index in 0.2s (4.5/s)
Reindexing groups:      100% (2/2)
Reindexed 2 documents in groups index in 0.1s (22.7/s)
Collecting projects:    3
Reindexing changes: projects: 66% (2/3)+2 Looks good to me, approved
label(): Checking label permission for: label-Code-Review
getRange(): checking for range for: label-Code-Review
access(): for: label-Code-Review
[-2..+2 group Administrators, -1..+1 group Registered Users]
getRange: -2..+2
-2..+2
label(): Checking label permission for: label-Code-Review
-2..+2
+1 Verified
label(): Checking label permission for: label-Verified
getRange(): checking for range for: label-Verified
access(): for: label-Verified
[-1..+1 group Administrators]
getRange: -1..+1
-1..+1
label(): Checking label permission for: label-Verified
-1..+1
[
  {
    "key": {
      "patchSetId": {
        "changeId": {
          "id": 1
        },
        "patchSetId": 2
      },
      "accountId": {
        "id": 1000000
      },
      "categoryId": {
        "id": "Code-Review"
      }
    },
    "value": 2,
    "granted": "Feb 10, 2018 4:19:00 PM",
    "tag": null,
    "realAccountId": null,
    "postSubmit": false
  },
  {
    "key": {
      "patchSetId": {
        "changeId": {
          "id": 1
        },
        "patchSetId": 2
      },
      "accountId": {
        "id": 1000000
      },
      "categoryId": {
        "id": "Verified"
      }
    },
    "value": 1,
    "granted": "Feb 10, 2018 4:19:00 PM",
    "tag": null,
    "realAccountId": null,
    "postSubmit": false
  }
Reindexing changes: projects: 100% (3/3), 100% (1/1), done

Bug: Issue 8191
Change-Id: I74e48ea3147a106e47bc8ba001b263dfa97c19a5