Update patch set 20
Patch Set 20:

I get a JS error.
TypeError: this is undefined
On this line:       url: this.getBaseUrl() + '/admin/groups',

This is not defined since the ADMIN_LINKS and DEFAULT_LINKS is outside the global scope. You could make them a function

Patch-set: 20
CC: Reyad Attiyat <1032567@173816e5-2b9a-37c3-8a2e-48639d4f1153>