Fix showing diff for *.ini.erb files
Showing the diff for *.ini.erb files may fail with the following
CodeMirror error:

  SEVERE: (TypeError) : a.multiplexingMode is not a function
    Class$S155: (TypeError) : a.multiplexingMode is not a function
      at Unknown.wrap_4(gerrit_ui-0.js)
      at Unknown.entry0(gerrit_ui-0.js)
      at Unknown.<anonymous>(gerrit_ui-0.js)
      ...

This is because the htmlembedded mode requires the CodeMirror
mode/multiplex addon [1]. Adding it fixes the issue.

[1] https://github.com/fixlr/codemirror-rails/issues/37

Change-Id: I5d33f0d073b9c9329dd4eaad1c4667d419777693
Signed-off-by: Edwin Kempin <ekempin@google.com>