Buck: Strip SNAPSHOT suffix in artifact names only for GERRIT repositories
Maven artifact names on Google bucket replacing SNAPSHOT suffix with
timestamp. 731967591ef98ab3c94691ba9dc0f217630dda76 changed this by
preserving the SNAPSHT suffix. This broke fetching of gwtorm and
gwtjsonrpc and was reverted by 731967591ef98ab3c94691ba9dc0f217630dda76.

This change fixes this for both worlds: striping it for GERRIT and
GERRIT_API Maven repositories but preserving it for the rest.

Test plan:

maven_jar is working for rest and still failing for GERRIT:

* gwtorm:gwtorm:1.10-SNAPSHOT

Error: Buck tring to download this file:
http://gerrit-maven.storage.googleapis.com/gwtorm/gwtorm/1.10-SNAPSHOT/gwtorm-1.10.jar
But it doesn't exist. The one that is there:

gwtorm/gwtorm/1.10-SNAPSHOT/gwtorm-1.10-20140310.015132-1.jar

But looking into the code, i cannot see, how it can ever work?

* org.eclipse.jgit:org.eclipse.jgit:3.4.0-SNAPSHOT

OK: works as expected

Change-Id: I5357abe9ad6a40538c444ad70016c8c6d75d8ff3