Update patch set 4
Patch Set 4:

Since this change was merged I can't build Gerrit anymore [1].
Reverting this commit makes the build work again.
Is there anything I need to install/update to build Gerrit with this change?
This problem blocks me from importing upstream Gerrit.

[1]
$ bazel build gerrit
INFO: Analysed target //:gerrit (0 packages loaded).
INFO: Found 1 target...
ERROR: /usr/local/google/home/ekempin/git/gerrit/polygerrit-ui/app/BUILD:9:1: error executing shell command: 'export PATH && p=$PWD && rm -rf bazel-out/k8-fastbuild/bin/polygerrit-ui/app/gr-app.html.dir && mkdir -p bazel-out/k8-fastbuild/bin/polygerrit-ui/app/gr-app.html.dir/polygerrit-ui/app/bower_compone...' failed (Exit 1)
/usr/local/google/home/ekempin/.cache/bazel/_bazel_ekempin/04250bee69fe54b0ca9e02f8a8931c32/execroot/gerrit/external/polymer-bundler/polymer-bundler@4.0.2-6b296b6099ab5a0e93ca914cbe93e753f2395910/package/lib/bin/polymer-bundler.js:186
const { moduleResolution } = options;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
Traceback (most recent call last):
  File "/usr/local/google/home/ekempin/.cache/bazel/_bazel_ekempin/04250bee69fe54b0ca9e02f8a8931c32/execroot/gerrit/tools/js/run_npm_binary.py", line 102, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/google/home/ekempin/.cache/bazel/_bazel_ekempin/04250bee69fe54b0ca9e02f8a8931c32/execroot/gerrit/tools/js/run_npm_binary.py", line 92, in main
    subprocess.check_call([nodejs, libbin] + args[1:])
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/nodejs', '/usr/local/google/home/ekempin/.cache/bazel/_bazel_ekempin/04250bee69fe54b0ca9e02f8a8931c32/execroot/gerrit/external/polymer-bundler/polymer-bundler@4.0.2-6b296b6099ab5a0e93ca914cbe93e753f2395910/package/lib/bin/polymer-bundler.js', '--inline-scripts', '--inline-css', '--strip-comments', '--out-file', '/usr/local/google/home/ekempin/.cache/bazel/_bazel_ekempin/04250bee69fe54b0ca9e02f8a8931c32/execroot/gerrit/bazel-out/k8-fastbuild/genfiles/polygerrit-ui/app/gr-app.html.bundled.html', 'polygerrit-ui/app/elements/gr-app.html']' returned non-zero exit status 1
Target //:gerrit failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.428s, Critical Path: 1.62s
INFO: 7 processes: 3 remote cache hit, 4 linux-sandbox.
FAILED: Build did NOT complete successfully

Patch-set: 4
CC: Gerrit User 1003935 <1003935@173816e5-2b9a-37c3-8a2e-48639d4f1153>