Revert "Additional log on plug-in self-registration and failures."
This reverts commit c0732b13010b1d83dccf6d69002a1653087ad24e


The commit broke server startup with:

java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.google.gerrit.extensions.registration.DynamicSet.<clinit>(DynamicSet.java:45)
        at com.google.gerrit.server.config.GerritGlobalModule.configure(GerritGlobalModule.java:146