Update patch set 2
Patch Set 2:

I cherry-picked this on top of stable-2.11 and it doesn't compile. I'm getting many messages like:

/home/orgads/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/project/ListDashboards.java:87: error: try-with-resources not applicable to variable type
        RevWalk rw = new RevWalk(git)) {
                ^
  required: java.lang.AutoCloseable
  found:    org.eclipse.jgit.revwalk.RevWalk

Patch-set: 2
Reviewer: Orgad Shaneh <1010516@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0