Update patch set 7
Patch Set 7: Verified-1

It seems that JGit 5.3 would require changes in the Gitiles plugin:
plugins/gitiles/src/main/java/com/googlesource/gerrit/plugins/gitiles/FilteredRepository.java:209: error: getRef(String) in FilteredRefDatabase cannot override getRef(String) in RefDatabase
    public Ref getRef(String name) throws IOException

@Dave is it too risky to fix it? Or should we just give up?

Patch-set: 7
Reviewer: Gerrit User 1006192 <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1