Add curl to the building prerequisites
`tools/download_file.py` calls `curl` and so building Gerrit on a
fresh system without `curl` (E.g.: fresh debian buster) fails with

```
ERROR: An error occurred during the fetch of repository 'impl-log4j':
   failed [/usr/bin/python, [...]/gerrit/tools/download_file.py, [...]
could not invoke curl: [Errno 2] No such file or directory
is curl installed?
```

As `curl` is obviously required, we list it as prerequisite.

Change-Id: I3d41130816ce9aa3c1c75b70bf21e08dae8bff18