Update patch set 1
Patch Set 1: Code-Review-1

This doesn't work (yet). I need to look into the underlying data base problems.

FAILURE submitTwoChangesWithFastForward[submitWholeTopicEnabled]: Cannot query submittedTogether
com.google.gerrit.extensions.restapi.RestApiException: Cannot query submittedTogether
	at com.google.gerrit.server.api.changes.ChangeApiImpl.submittedTogether(ChangeApiImpl.java:207)
	at com.google.gerrit.acceptance.AbstractDaemonTest.assertSubmittedTogether(AbstractDaemonTest.java:603)
	at com.google.gerrit.acceptance.rest.change.SubmitByFastForwardIT.submitTwoChangesWithFastForward(SubmitByFastForwardIT.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Caused by: java.lang.IllegalArgumentException: numHits must be > 0; please use TotalHitCountCollector if you just need the total hit count
	at org.apache.lucene.search.TopFieldCollector.create(TopFieldCollector.java:625)
	at org.apache.lucene.search.IndexSearcher$4.newCollector(IndexSearcher.java:665)
	at org.apache.lucene.search.IndexSearcher$4.newCollector(IndexSearcher.java:660)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:694)
	at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:680)
	at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:622)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:528)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:578)
	at com.google.gerrit.lucene.LuceneChangeIndex$QuerySource.read(LuceneChangeIndex.java:428)
	at com.google.gerrit.server.index.IndexedChangeQuery.read(IndexedChangeQuery.java:94)
	at com.google.gerrit.server.index.IndexedChangeQuery.restart(IndexedChangeQuery.java:137)
	at com.google.gerrit.server.query.change.AndSource.readImpl(AndSource.java:133)
	at com.google.gerrit.server.query.change.AndSource.read(AndSource.java:99)
	at com.google.gerrit.server.query.change.QueryProcessor.queryChanges(QueryProcessor.java:160)
	at com.google.gerrit.server.query.change.QueryProcessor.queryChanges(QueryProcessor.java:102)
	at com.google.gerrit.server.query.change.QueryProcessor.queryChanges(QueryProcessor.java:86)
	at com.google.gerrit.server.query.change.InternalChangeQuery.query(InternalChangeQuery.java:212)
	at com.google.gerrit.server.query.change.InternalChangeQuery.byChangeSet(InternalChangeQuery.java:198)
	at com.google.gerrit.server.change.SubmittedTogether.apply(SubmittedTogether.java:84)
	at com.google.gerrit.server.api.changes.ChangeApiImpl.submittedTogether(ChangeApiImpl.java:205)

Patch-set: 1
Label: Code-Review=-1