Update patch set 2
Patch Set 2:

Interesting: the CI failed to provide the feedback because of the following error.

hudson.remoting.ProxyException: com.google.gerrit.extensions.restapi.RestApiException: Request returned status 429

Can we do something to whitelist the Gerrit CI?

Patch-set: 2
Reviewer: Gerrit User 1024147 <1024147@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Gerrit User 1006192 <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>