Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> I tried now locally using Linux and authenticating with GCP. No more permissions issues but the build and/or test is failing.
> 
> $ bazelisk test --config=remote     javatests/com/google/gerrit/integration/git/...
> Starting local Bazel server and connecting to it...
> INFO: Invocation ID: 40f6c79a-979a-4e80-a549-7bf27e23b6de
> DEBUG: /home/jenkins/.cache/bazel/_bazel_jenkins/bb2dc09ec74ab7b7157cd89c2ef96641/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:113:13: rbe_ubuntu1804 not using checked in configs; registry was set to 'gcr.io' and toolchain_config_suite_spec is configured for 'marketplace.gcr.io'
> INFO: Call stack for the definition of repository 'rules_cc' which is a git_repository (rule definition at /home/jenkins/.cache/bazel/_bazel_jenkins/bb2dc09ec74ab7b7157cd89c2ef96641/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
>  - <builtin>
>  - /home/jenkins/.cache/bazel/_bazel_jenkins/bb2dc09ec74ab7b7157cd89c2ef96641/external/io_bazel_rules_go/go/private/repositories.bzl:241:9
>  - /home/jenkins/.cache/bazel/_bazel_jenkins/bb2dc09ec74ab7b7157cd89c2ef96641/external/io_bazel_rules_go/go/private/repositories.bzl:99:5
>  - /home/jenkins/gerrit/WORKSPACE:101:1
> ERROR: An error occurred during the fetch of repository 'rules_cc':
>    Traceback (most recent call last):
> 	File "/home/jenkins/.cache/bazel/_bazel_jenkins/bb2dc09ec74ab7b7157cd89c2ef96641/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
> 		_clone_or_update(ctx)
> 	File "/home/jenkins/.cache/bazel/_bazel_jenkins/bb2dc09ec74ab7b7157cd89c2ef96641/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
> 		git_repo(ctx, directory)
> 	File "/home/jenkins/.cache/bazel/_bazel_jenkins/bb2dc09ec74ab7b7157cd89c2ef96641/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
> 		_update(ctx, git_repo)
> 	File "/home/jenkins/.cache/bazel/_bazel_jenkins/bb2dc09ec74ab7b7157cd89c2ef96641/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
> 		init(ctx, git_repo)
> 	File "/home/jenkins/.cache/bazel/_bazel_jenkins/bb2dc09ec74ab7b7157cd89c2ef96641/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
> 		_error(ctx.name, cl, st.stderr)
> 	File "/home/jenkins/.cache/bazel/_bazel_jenkins/bb2dc09ec74ab7b7157cd89c2ef96641/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
> 		fail(<1 more arguments>)
> error running 'git init /home/jenkins/.cache/bazel/_bazel_jenkins/bb2dc09ec74ab7b7157cd89c2ef96641/external/rules_cc' while working with @rules_cc:
> src/main/tools/process-wrapper-legacy.cc:58: "execvp(git, ...)": No such file or directory

Can it be that your Linux environment is missing some basic packages?
Does it work without RBE?

  $ bazelisk test javatests/com/google/gerrit/integration/git/...

Patch-set: 5
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>