Fix: Exception when editing group name to same name from WebUI
If the user edits the group name in the Web UI, the "Rename Group"
button is enabled.  If the name is then edited back to its original
value, the button remains enabled.

If the user then submits the edit, an exception occurs:

  JdbcSQLException: Unique index or primary key violation

Add a check in the PutName REST view to prevent the rename from
being executed with the same name.  If the new name is the same,
just return it.

Change-Id: Ifba0ba646ee7895596cec22449abe8e2a466c375