Update patch set 1
Patch Set 1:

This doesn't build:

 java/com/google/gerrit/server/git/WorkQueue.java:17: error: package com.google.gerrit.metrics.dropwizard does not exist
 import static com.google.gerrit.metrics.dropwizard.DropWizardMetricMaker.sanitizeMetricName;

and this is highlighting a problem with the introduction of the sanitizeMetricName method inside DropWizardMetricMaker, and its usage in WorkQueue.

We should not be depending on c.g.g.metrics.dropwizard from the WorkQueue class. Dropwizard is a specific implementation of metrics which might be replaced by something else (for example google binds their own).

I'll try to fix this on stable-2.14.

Patch-set: 1
Reviewer: David Ostrovsky <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Hugo Arès <1012987@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Eryk Szymanski <1014257@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Jacek Centkowski <1025452@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: David Pursehouse <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>