Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> External id test failures seem to be related:
> 
>   1) deleteExternalIds(com.google.gerrit.acceptance.rest.account.ExternalIdIT)
>   java.lang.AssertionError: Expected status code 204: Not true that <409> is equal to <204>
> 
>   2) 
>  
>  deleteExternalIdsOfOtherUserWithAccessDatabase(com.google.gerrit.acceptance.rest.account.ExternalIdIT)
> java.lang.AssertionError: Expected status code 204: Not true that <409> is equal to <204>

Yes, the external Id tests are attempting to delete an email address that is preferred.  See my earlier comment; I haven't worked on fixing the tests because I don't know if everyone agrees that preventing deletion of preferred email is wanted.

Patch-set: 3
Reviewer: Gerrit User 1011123 <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>