Update patch set 6
Patch Set 6:

> This works for master but not for stable-2.15
 > 
 > gr-app.js:2454 TypeError: this.plugin.restApi is not a function
 > at GrPluginActionContext.call (gr-app.js:2497)
 > at plugin.onAction (rebase-stack.js:22)
 > at HTMLElement.<anonymous> (gr-app.js:2508)
 > at HTMLElement.fire (gr-app.js:1453)
 > at HTMLElement._handleOveflowItemTap (gr-app.js:2571)
 > at HTMLElement.handler (gr-app.js:1423)
 > at HTMLElement._handleItemTap (gr-app.js:2534)
 > at handler (gr-app.js:1423)
 > at HTMLSpanElement.decorated (gr-app.js:1617)
 > at HTMLElement.fire (gr-app.js:1453)

Hmm it was added in https://github.com/GerritCodeReview/gerrit/commit/e5a2f5c5cd0ff760ebed996c8fca16c38e7c2716

Patch-set: 6
Reviewer: Paladox none <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>