Bazel: Workaround spurious remote cache related build failures
After Bazel version upgrade to 7.0 we are seeing spurious build
breakages on the CI, related to the remote cache:

[369 / 527] [Prepa] Compiling Java headers external/jgit/org.eclipse.jgit.ssh.apache/libssh-apache-hjar.jar (53 source files)
ERROR: /home/jenkins/workspace/Gerrit-verifier-chrome-latest/gerrit/java/com/google/gerrit/jgit/BUILD:3:13: Compiling Java headers java/com/google/gerrit/jgit/libjgit-hjar.jar (1 source file) failed: Failed to fetch blobs because they do not exist remotely.: Missing digest: cf3b2439c36619f2b6aaadddc55f15ddfd0c96566d22c1c507823ca74ac09732/127311204 for bazel-out/k8-fastbuild/bin/external/rules_java_builtin/toolchains/platformclasspath.jar

This problem was investigated upstream in context of this issue:
https://github.com/bazelbuild/bazel/issues/20161.

Use workaround suggested in that issue to unblock verification of
changes on the Gerrit CI.

Release-Notes: skip
Change-Id: Ia46de5cfcd379629608df90663092ca8e66f7a93