CreateChange: Return '409 Conflict' for all NoMergeBaseExceptions
There are 3 cases that lead to NoMergeBaseException:

1. TOO_MANY_MERGE_BASES:
   The number of merge bases exceeds 200.

2. CONFLICTS_DURING_MERGE_BASE_CALCULATION:
   In order to find a single merge base it may required to merge
   together multiple common predecessors. If during these merges
   conflicts occur the merge fails with this reason.

3. MULTIPLE_MERGE_BASES_NOT_SUPPORTED:
   Multiple merge bases have been found (e.g. the commits to be merged
   have multiple common predecessors) but the merge strategy doesn't
   support this (e.g. ResolveMerge).

Since change Ia485e24c1 case 1. and 2. result in '409 Conflict'. Case 3.
was left as '500 Internal Server Error' because it was assumed that this
case can never happen, as we though that we would always use
RecursiveMerger for creating merge commits, which does support multiple
merge bases. This assumption was wrong. In fact it depends on the user
input (ChangeInput -> merge -> strategy) and the project configuration
(useContentMerge = submit.mergeContent (default = false);
useRecursiveMerge = core.useRecursiveMerge (default = true)) which merge
strategy is used. Also see MergeUtil#mergeStrategyName().

E.g. if useContentMerge == false the StrategySimpleTwoWayInCore strategy
(aka MergeStrategy.SIMPLE_TWO_WAY_IN_CORE) is used for the creation of
the merge commit. This strategy doesn't support multiple merge cases and
hence currently results in a '500 Internal Server Error' [1].

[1]
org.eclipse.jgit.errors.NoMergeBaseException: No merge base could be determined. Reason=MULTIPLE_MERGE_BASES_NOT_SUPPORTED. Multiple merge bases for:
  494d93fd26cbb20e4c7f10e836515c3f4618f81c
  4c83952256a21e78c4c9ab8adeece22b14e2f783 found:
  100bf6071245bd5d38a1b8a38fdf822850ed5775
  a0f8bdd329aabb92f3616917cb0bcc11f1b96827
        at org.eclipse.jgit.merge.Merger.getBaseCommit(Merger.java:313)
        at org.eclipse.jgit.merge.ThreeWayMerger.mergeBase(ThreeWayMerger.java:150)
        at org.eclipse.jgit.merge.StrategySimpleTwoWayInCore$InCoreMerger.mergeImpl(StrategySimpleTwoWayInCore.java:133)
        at org.eclipse.jgit.merge.Merger.merge(Merger.java:266)
        at com.google.gerrit.server.git.MergeUtil.createMergeCommit(MergeUtil.java:446)
        at com.google.gerrit.server.restapi.change.CreateChange.newMergeCommit(CreateChange.java:505)
        at com.google.gerrit.server.restapi.change.CreateChange.createNewChange(CreateChange.java:321)
        at com.google.gerrit.server.restapi.change.CreateChange.apply(CreateChange.java:187)
        at com.google.gerrit.server.restapi.change.CreateChange.apply(CreateChange.java:104)
        at com.google.gerrit.httpd.restapi.RestApiServlet.lambda$invokeRestCollectionModifyViewWithRetry$7(RestApiServlet.java:808)
        at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
        at com.github.rholder.retry.Retryer.call(Retryer.java:160)
        at com.google.gerrit.server.update.RetryHelper.executeWithTimeoutCount(RetryHelper.java:560)
        at com.google.gerrit.server.update.RetryHelper.execute(RetryHelper.java:503)
        at com.google.gerrit.server.update.RetryableAction.call(RetryableAction.java:171)
        at com.google.gerrit.httpd.restapi.RestApiServlet.invokeRestEndpointWithRetry(RestApiServlet.java:833)
        at com.google.gerrit.httpd.restapi.RestApiServlet.invokeRestCollectionModifyViewWithRetry(RestApiServlet.java:803)
        at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:563)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        ...

Signed-off-by: Edwin Kempin <ekempin@google.com>
Change-Id: I3f106027d29de76c89ae2f50983c1eb6412d0a79