RFC: GerritIndexWriterConfig: Set commitWithinMs to 0 for in-memory tests
If not set, commitWithinMs defaults to 30000 ms (5 minutes).

This can result in both the closed and open subindexes returning results
immediately after a change is abandoned, resulting in flakiness (~5%) for
at least one acceptance test:

  1) abandonAndRestoreAllowedWithPermission(com.google.gerrit.acceptance.api.change.ChangeIT)
  com.google.gerrit.extensions.restapi.ResourceNotFoundException: Multiple changes found for I4bc6f1c3908e67ece55f21bca0d2d033f8fa458a
    at com.google.gerrit.server.change.ChangesCollection.parse(ChangesCollection.java:86)
    at com.google.gerrit.server.api.changes.ChangesImpl.id(ChangesImpl.java:79)
    at com.google.gerrit.acceptance.AbstractDaemonTest.info(AbstractDaemonTest.java:692)
    at com.google.gerrit.acceptance.api.change.ChangeIT.abandonAndRestoreAllowedWithPermission(ChangeIT.java:365)

When commitWithinMs is set to 0, changes to the index are committed
after every write.

Bug: Issue 5944
Change-Id: Iee90768a9f5eec1a3576d2a3930a6e8de011c65e