Inspector: remove print() from python script
The Startup.py script is intended to be run by Jython which does not
support __future__ resulting in:

  SyntaxError: ('future feature print_function is not defined',
  ('resource com/google/gerrit/pgm/Startup.py', 19, 0, ''))

This came from bc8eca1cd626b3df0504629f46708e48204db835 which mass
replaced `print` statements to make them compatible with Python 3,
however Jython implements Python 2 and does not have a __future__
module.

Change-Id: Iea397bcda05b55114d346666f25d20de1e246240