Fix buck build error because of not encoded argument
On Arch Linux using Python 2.7.6 with a recent clone of buck,
I got the following error:

  Traceback (most recent call last):
    File "gerrit/tools/download_file.py", line 100, in <module>
      cache_ent = cache_entry(args)
    File "gerrit/tools/download_file.py", line 80, in cache_entry
      h = sha1(args.u).hexdigest()
  TypeError: Unicode-objects must be encoded before hashing

Change-Id: I7a638b56a14cf579ba57f2a5c17df62cf3fbf266