Update patch set 1
Patch Set 1:

I added a "throw new RuntimeException" in every location that logs the UUID message, then ran the test to get a stack trace:

DEBUG com.google.gerrit.server.account.UniversalGroupBackend : Unknown GroupMembership for UUID: users-Copyright_Experts [CONTEXT RECEIVE_ID="com.googlesource.gerrit.plugins.copyright.CopyrightValidatorIT_testCo
pyrightValidator_pushNoLicense_project-1558572256972-b98637cb" ]
ERROR com.google.gerrit.server.extensions.events.ReviewerAdded : Couldn't fire event [CONTEXT RECEIVE_ID="com.googlesource.gerrit.plugins.copyright.CopyrightValidatorIT_testCopyrightValidator_pushNoLicense_proje
ct-1558572256972-b98637cb" ]
com.google.gerrit.exceptions.StorageException: java.lang.RuntimeException: Error in contains
        at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:384)
        at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:284)
        at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:276)
        at com.google.gerrit.server.extensions.events.EventUtil.changeInfo(EventUtil.java:77)
        at com.google.gerrit.server.extensions.events.ReviewerAdded.fire(ReviewerAdded.java:65)
        at com.google.gerrit.server.change.AddReviewersOp.postUpdate(AddReviewersOp.java:255)
        at com.google.gerrit.server.change.ReviewerAdder$ReviewerAdditionList.postUpdate(ReviewerAdder.java:569)
        at com.google.gerrit.server.change.ChangeInserter.postUpdate(ChangeInserter.java:441)
        at com.google.gerrit.server.update.BatchUpdate.executePostOps(BatchUpdate.java:603)
        at com.google.gerrit.server.update.BatchUpdate.execute(BatchUpdate.java:164)
        at com.google.gerrit.server.update.BatchUpdate.execute(BatchUpdate.java:353)
        at com.google.gerrit.server.update.BatchUpdate.execute(BatchUpdate.java:357)
        at com.google.gerrit.server.git.receive.ReceiveCommits.insertChangesAndPatchSets(ReceiveCommits.java:853)
        at com.google.gerrit.server.git.receive.ReceiveCommits.processCommandsUnsafe(ReceiveCommits.java:608)
        at com.google.gerrit.server.git.receive.ReceiveCommits.processCommands(ReceiveCommits.java:510)
        at com.google.gerrit.server.git.receive.AsyncReceiveCommits$Worker.run(AsyncReceiveCommits.java:133)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.gerrit.server.util.RequestScopePropagator.lambda$cleanup$1(RequestScopePropagator.java:182)
        at com.google.gerrit.server.util.RequestScopePropagator.lambda$context$0(RequestScopePropagator.java:170)
        at com.google.gerrit.server.util.ThreadLocalRequestScopePropagator.lambda$wrapImpl$0(ThreadLocalRequestScopePropagator.java:45)
        at com.google.gerrit.server.util.RequestScopePropagator$1.call(RequestScopePropagator.java:85)
        at com.google.gerrit.server.util.RequestScopePropagator$2.run(RequestScopePropagator.java:116)
        at com.google.gerrit.server.logging.LoggingContextAwareRunnable.run(LoggingContextAwareRunnable.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:295)
        at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:610)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error in contains
        at com.google.gerrit.server.account.UniversalGroupBackend$UniversalGroupMembership.contains(UniversalGroupBackend.java:130)
        at com.google.gerrit.server.permissions.ProjectControl.match(ProjectControl.java:330)
        at com.google.gerrit.server.permissions.ProjectControl.match(ProjectControl.java:165)
        at com.google.gerrit.server.permissions.RefControl.toRange(RefControl.java:320)
        at com.google.gerrit.server.permissions.RefControl.getRange(RefControl.java:147)
        at com.google.gerrit.server.permissions.ChangeControl.getRange(ChangeControl.java:122)
        at com.google.gerrit.server.permissions.ChangeControl.access$1900(ChangeControl.java:43)
        at com.google.gerrit.server.permissions.ChangeControl$ForChangeImpl.label(ChangeControl.java:340)
        at com.google.gerrit.server.permissions.ChangeControl$ForChangeImpl.can(ChangeControl.java:327)
        at com.google.gerrit.server.permissions.ChangeControl$ForChangeImpl.can(ChangeControl.java:279)
        at com.google.gerrit.server.permissions.ChangeControl$ForChangeImpl.test(ChangeControl.java:261)
        at com.google.gerrit.server.permissions.PermissionBackend$ForChange.testLabels(PermissionBackend.java:504)
        at com.google.gerrit.server.change.LabelsJson.permittedLabels(LabelsJson.java:134)
        at com.google.gerrit.server.change.LabelsJson.setAllApprovals(LabelsJson.java:456)
        at com.google.gerrit.server.change.LabelsJson.labelsForUnsubmittedChange(LabelsJson.java:199)
        at com.google.gerrit.server.change.LabelsJson.labelsFor(LabelsJson.java:111)
        at com.google.gerrit.server.change.ChangeJson.toChangeInfoImpl(ChangeJson.java:548)
        at com.google.gerrit.server.change.ChangeJson.toChangeInfo(ChangeJson.java:479)
        at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:372)
        at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:284)
        at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:276)
        at com.google.gerrit.server.extensions.events.EventUtil.changeInfo(EventUtil.java:77)
        at com.google.gerrit.server.extensions.events.ReviewerAdded.fire(ReviewerAdded.java:65)
        at com.google.gerrit.server.change.AddReviewersOp.postUpdate(AddReviewersOp.java:255)
        at com.google.gerrit.server.change.ReviewerAdder$ReviewerAdditionList.postUpdate(ReviewerAdder.java:569)
        at com.google.gerrit.server.change.ChangeInserter.postUpdate(ChangeInserter.java:441)
        at com.google.gerrit.server.update.BatchUpdate.executePostOps(BatchUpdate.java:603)
        at com.google.gerrit.server.update.BatchUpdate.execute(BatchUpdate.java:164)
        at com.google.gerrit.server.update.BatchUpdate.execute(BatchUpdate.java:353)
        at com.google.gerrit.server.update.BatchUpdate.execute(BatchUpdate.java:357)
        at com.google.gerrit.server.git.receive.ReceiveCommits.insertChangesAndPatchSets(ReceiveCommits.java:853)
        at com.google.gerrit.server.git.receive.ReceiveCommits.processCommandsUnsafe(ReceiveCommits.java:608)
        at com.google.gerrit.server.git.receive.ReceiveCommits.processCommands(ReceiveCommits.java:510)
        at com.google.gerrit.server.git.receive.AsyncReceiveCommits$Worker.run(AsyncReceiveCommits.java:133)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.gerrit.server.util.RequestScopePropagator.lambda$cleanup$1(RequestScopePropagator.java:182)
        at com.google.gerrit.server.util.RequestScopePropagator.lambda$context$0(RequestScopePropagator.java:170)
        at com.google.gerrit.server.util.ThreadLocalRequestScopePropagator.lambda$wrapImpl$0(ThreadLocalRequestScopePropagator.java:45)
        at com.google.gerrit.server.util.RequestScopePropagator$1.call(RequestScopePropagator.java:85)
        at com.google.gerrit.server.util.RequestScopePropagator$2.run(RequestScopePropagator.java:116)
        at com.google.gerrit.server.logging.LoggingContextAwareRunnable.run(LoggingContextAwareRunnable.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:295)
        at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:610)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Patch-set: 1