Update patch set 1
Patch Set 1: Code-Review-1

(4 comments)

> Since I have thus far utterly failed at monkey-testing the notedb
 > shadow repository stuff, I would appreciate some help with the
 > verification :)

The problem that was introduced in I8158e3f46 is fixed. However enabling notedb.write = true for "changes" table is still broken:

  [notedb "changes"]
    write = true

There is still mismatch between meta- and normal repositories: the read notedb operation is always done from '$gerrit_site'/notedb/All-Users.git repo, while the write operation is always done in '$gerrit_site'/git/All-Users.git repo. I believe that the problem is that AbstractChangeUpdate.openUpdateInBatch() wasn't adapted to be notedb meta data respository aware:

  MetaDataUpdate md =
      updateFactory.create(getProjectName(), getUser(), bru);

always trying to write in regular repo, with the effect that only the first draft comment is written correctly (in the wrong repo) and all subsequent attempts are failing because expected commit diverges from the real one (read from one repo and write in another cannot work):

  java.io.IOException: Cannot update refs/draft-comments/00/1000000-1 in
  '$gerrit_site'/git/All-Users.git: LOCK_FAILURE
  at com.google.gerrit.server.git.VersionedMetaData$1.updateRef(VersionedMetaData.java:354)

Patch-set: 1
Label: Code-Review=-1