Update patch set 6
Patch Set 6:

This change is causing issue downloading the commit message hook.

command used:
gitdir=$(git rev-parse --git-dir); scp -p -P 29450 ehugare@localhost:hooks/commit-msg ${gitdir}/hooks/

client side error:
Bad packet length 2424809510.
Disconnecting: Packet corrupt

server side error:
[2016-01-21 15:33:45,897] [SSH scp -p -f hooks/commit-msg (ehugare)] ERROR com.google.gerrit.sshd.BaseCommand : Internal server error (user ehugare account 1000000) during scp -p -f hooks/commit-msg
org.apache.sshd.common.SshException: flush(length=0) - stream is already closed
	at org.apache.sshd.common.channel.ChannelOutputStream.flush(ChannelOutputStream.java:119)
	at com.google.gerrit.sshd.BaseCommand$TaskThunk.run(BaseCommand.java:444)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:377)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

Patch-set: 6
Reviewer: Hugo Arès <1012987@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0