Update patch set 1
Patch Set 1:

> Borui is not in the office yet but I think he was running the test from eclipse, is it possible it's failing only in eclipse?

I managed to reproduce the problem and ...

1) Running ChangeIT altogether works
2) Running ChnageIT.addGroupAsReviewersWhenANotPerfectMatchedUserExists alone FAILS

The error is:
java.lang.AssertionError: Not true that <[User <user@example.com>]> contains exactly <[testUser <testUser@test.com>]>. It is missing <[testUser <testUser@test.com>]> and has unexpected items <[User <user@example.com>]>

I believe this is a test issue rather than a CI issue. The tests does not cleanup or setup the environment properly so that when they get executed altogether they interfere with each other.

We have then 2 problems to fix:
- the Test
- the Bug

CI looks good to me as it is unaware of what the tests are doing and just run them.

Patch-set: 1