Update git submodules
* Update plugins/delete-project from branch 'master'
  to 75b79c115ba3dd03aa56a3165e6c319fa30c6c4a
  - Merge branch 'stable-3.8'
    
    * stable-3.8:
      ConfigurationTest: Remove flaky invalidTargetArchiveFolder test
      Send Project Deleted Events also when archiving
    
    Change-Id: Ic64ac7317f430f520ef0350c0bbdb63846823086
    
  - Merge branch 'stable-3.7' into stable-3.8
    
    * stable-3.7:
      ConfigurationTest: Remove flaky invalidTargetArchiveFolder test
      Send project-deleted event after project deletion
    
    Change-Id: I2ac01b00d7ce442b96a032d90b4037670e65d79a
    
  - ConfigurationTest: Remove flaky invalidTargetArchiveFolder test
    
    This test is failing when running gerrit test in docker image with root
    user. It's also failing when remote build execution is used (BuildBuddy
    provider).
    
    It seems to rely on the fact that the exception is thrown:
    
    java.nio.file.FileSystemException: /\\\: Operation not permitted
    
    However when the test is executed with BuildBuddy RBE that exception is
    not raised and as a consequence of that the test ends up failing. It
    looks that the folder /\\\ is created in the remote executor.
    
    While it could be fixed with:
    
    exec_properties = {
        "dockerUser": "nobody",
    },
    
    we prefer not to complicate our build toolchain and rather remove the
    test.
    
    Change-Id: I51bccdf2cb19559690d3d88bd92cf60bc28f5fcd
    
  - Send Project Deleted Events also when archiving
    
    When projects are either deleted fully, or preserved by setting as
    hidden and moving to f.i. Deleted-Projects, we send a Project Deleted
    Event. We do not do the same if we archive the repository, even though
    this is effectively also a deleted project (more so than hidden is) from
    a Gerrit perspective.
    
    Not sending this event means that archived repositories are not properly
    removed from replicas when replicateRepositoryDeletions is set.
    
    This makes sure that we still send the projectDeletionEvent while
    archiving is set.
    
    Release-Notes: Plugin Delete-Project archiveDeletedRepos option now also emits a Project Deletion event.
    Change-Id: I0829a1a2016d67ac789b92f67d1d7c6a13b65c65