dev-bazel: Fix package name in example test invocation
Invoking the test with the given example fails because 'google'
is missing from the package:

  There was 1 failure:
  1) initializationError(org.junit.runner.manipulation.Filter)
  java.lang.Exception: No tests found matching RegEx[com.gerrit.server.notedb.ChangeNotesTest]

Change-Id: I5cd3a8e9358c29fdb59cceb4851db3841c26c749