Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Hi, i am wondering how can i convert plugin events-log which used this method please?
> 
> I've done something like
> 
> https://gerrit-review.googlesource.com/#/c/plugins/autosubmitter/+/125452/4/src/main/java/com/criteo/gerrit/plugins/automerge/AtomicityHelper.java@155
> 
> but it fails with
> 
> ERROR: /Users/patrickmulhall/Documents/workspace/gerrit/plugins/autosubmitter/BUILD:4:1: Building plugins/autosubmitter/libautosubmitter__plugin.jar (5 source files) failed: Worker process sent response with exit code: 1.
> plugins/autosubmitter/src/main/java/com/criteo/gerrit/plugins/automerge/AtomicityHelper.java:163: error: incompatible types: ChangeNotes cannot be converted to ChangeResource
>     RevisionResource r = new RevisionResource(notes, changeData.currentPatchSet());
>                                               ^
> Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
> Target //plugins/autosubmitter:autosubmitter failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 0.398s, Critical Path: 0.25s

A RevisionResource needs to be constructed with a ChangeResource and a PatchSet. It looks like you are attempting to create it with ChangeNotes.

You can create a ChangeResource by passing in a ChangeControl (this will change in the near-future). You can construct a ChangeControl with a ChangeControl.GenericFactory by calling either one of #controlFor.

Patch-set: 1
Reviewer: Patrick Hiesel <1026112@173816e5-2b9a-37c3-8a2e-48639d4f1153>