Update patch set 1
Patch Set 1:

It's been a while since I compiled master and I get an error, does it work for you?

ERROR: /home/ehugare/workspaces/gerrit/gerrit/polygerrit-ui/app/BUILD:46:1: every rule of type closure_js_binary implicitly depends upon the target '@com_google_javascript_closure_library//:closure/goog/base.js', but this target could not be found because of: no such package '@com_google_javascript_closure_library//': Error downloading [http://bazel-mirror.storage.googleapis.com/github.com/google/closure-library/archive/0e309e9c5fb611a70a47736a2eb1204ae48ab989.tar.gz, https://github.com/google/closure-library/archive/0e309e9c5fb611a70a47736a2eb1204ae48ab989.tar.gz] to /home/ehugare/.cache/bazel/_bazel_ehugare/371e057ac5310461e5436388c1c39793/external/com_google_javascript_closure_library/0e309e9c5fb611a70a47736a2eb1204ae48ab989.tar.gz: Tried to reconnect at offset 1,422,744 but server didn't support it.

Patch-set: 1
Reviewer: Hugo Arès <1012987@173816e5-2b9a-37c3-8a2e-48639d4f1153>