Update patch set 5
Patch Set 5:

@Kasper Nilsson  Hi, the browser is safari and the os is mac osx 10.12.4.

Full error log is

ReferenceError: Can't find variable: $jscomp
g — gr-app.js:1785
convertEffectInput — gr-app.js:1793:381
KeyframeEffect — gr-app.js:1798:201
animate — gr-app.js:1799:323
(anonymous function) — gr-app.js:1835:232
(anonymous function) — gr-app.js:1837:277
Global Code — gr-app.js:1869:291

Ah, it works in chrome but breaks in safari. Not sure why it wont work with the compiler running as es5 but changing it to es6 fixed it.

Patch-set: 5
Reviewer: Paladox none <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>