Update patch set 1
Patch Set 1:

> Sorry, I've never used that tool, so have no idea how it's supposed to work, but squashing changes sounds like something that might have caused this:
> 
>  > https://gerrit-review.googlesource.com/100756 closed)
>  > error: failed to push some refs to 'https://gerrit.googlesource.com/gerrit'
>
> Could be caused by:
> 
> - You've done a rebase locally including that other change, before it was merged, and now you have it with a different sha1 locally.

The referenced change is not mine, so I could only get it after it was merged.

> - Somehow you've replaced the Change-Id in one of your local changes with that change's Change-Id 

Because this is my 2nd push over the same thing that generated this 2nd review, when I squashed, I removed Change-Id of this review. But no, I didn't replace anything.

>  > 
>  > So what to do now?
> 
> Reset your local head to origin/master.  Cherry pick the previous commit, and then cherry pick this commit (use the links from the Download menu).
> 
> Then, do an interactive rebase:
> 
>   git rebase -i HEAD~2
> 
> and for this commit, change "pick" to "fixup".

I just pulled and rebased it again and everything worked. This review can be close.

Patch-set: 1
Reviewer: anatoly techtonik <1013527@173816e5-2b9a-37c3-8a2e-48639d4f1153>