Guard repository reference counting internals against `null`
The I3037064388 change introduced the repository reference counting
check in integration tests. It also uses the reference counting
mechanism in Gerrit test server called in tests. It seems that in
certain cases the reference counting clear (that is called after each
TC) is called before the Gerrit test server is stopped. When that
happens any operation on reference counting internal may result in NPE
e.g.:

SEVERE: Error while getting full commit message for change 1 [CONTEXT PLUGIN="gerrit" ]
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "this.decrementCallersStacks" is null
  at com.google.gerrit.testing.GitRepositoryReferenceCountingManager$RepositoryTracking.close(GitRepositoryReferenceCountingManager.java:119)
  at com.google.gerrit.server.query.change.ChangeData.loadCommitData(ChangeData.java:919)
  at com.google.gerrit.server.query.change.ChangeData.commitMessage(ChangeData.java:865)
  at com.google.gerrit.server.events.EventFactory.addCommitMessage(EventFactory.java:355)
  ...

Changes:
* ensure that any ooperation on the reference counting is NPE protected
* the `beforeTest` for new test function is called before before
  `afterTest` for the one that was finished; in that case `clear`
  function is called twice when there are more then 1 test functions;
  ensure that it is not called second time when it was called already
* synchronize `openRepositories` operating functions

This also reduces the flakines of some integration tests e.g.
`StreamEventsIT.draftCommentRefsDeletionShowInStreamEventsUponPublishing`

Release-Notes: skip
Change-Id: If77805574f4becb6ec3986ab906c0efa782198f1