ScheduleConfig: Throw provision exception for invalid start time
Migration off Joda time library to Java time API in: I2db9b803c3e
introduced serious regression with start time parsing for garbage
collection section: 4:00 became invalid now, that was a valid start time
prior to migration to Java time API.

Given that non working GC cycles in gerrit can jeopardize the stability
of the whole system, promote that situation from just logging the error
to a fatal provision exception, so that Gerri would fail to start in
such broken state:

[2020-05-23 12:03:40,151] ERROR com.google.gerrit.pgm.Daemon : Unable to start daemon
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Invalid start time: Text '4:00' could not be parsed at index 0
  at com.google.gerrit.server.config.GcConfig.<init>(Unknown Source)
  at com.google.gerrit.server.config.GerritGlobalModule.configure(GerritGlobalModule.java:294)
  while locating com.google.gerrit.server.config.GcConfig

Bug: Issue 12809
Change-Id: I7084f47ae19e555433e86a5799c3ff57a3597ef5