Update patch set 1
Patch Set 1: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 3.6s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/rules/RulesCache.java:110: error: incompatible types
    cacheDir = site.resolve(config.getString("cache", null, "directory"));
                           ^
  required: java.io.File
  found:    java.nio.file.Path
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/git/LocalDiskRepositoryManager.java:140: error: incompatible types
    basePath = site.resolve(cfg.getString("gerrit", null, "basePath"));
...

Patch-set: 1
Label: Verified=-1