Update patch set 3
Patch Set 3:

(1 comment)

> Gerrit-CI Build: https://gerrit-ci.gerritforge.com/job/Gerrit-verifier-change/5309/console

Looking at this breakage: [1], in this test, in NoteDbReadWrite mode:

  java.lang.AssertionError: Not true that ChangeInfo is empty at
  DraftChangeIT.deleteDraftChangeWhenDraftsNotAllowedAsAdmin(DraftChangeIT.java:158)

We create a change, mark it artificially as draft (allow draft workflow is disabled for this test), then we delete the change from the NoteDb. BatchUpdate asynchronously kick the reindexing, but then wait synchronously for it to end:

  ChangeIndexer.allAsList(indexFutures).get();

Now in test we trigger query for the change that was just deleted and reindexing is ready. How comes, that the query for the changeId, that was deleted returns non empty result? Again Lucene near runtime time feature issues?

* [1] http://paste.openstack.org/show/594150

Patch-set: 3