Update patch set 5
Patch Set 5:

> Have you verified it? Does it work for you?

Unfortunately this still does not work for. When running reindex I get the failure below. I guess this is because doing things in mutliple threads requires more database connections than I have. I'm just using H2 without any special configuration.

  2013-12-10 10:08:11,845] ERROR com.google.gerrit.server.index.ChangeBatchIndexer : Failed to index project test
  java.util.concurrent.ExecutionException: com.google.inject.ProvisionException: Guice provision errors:

  1) unable to open ReviewDb
    at com.google.gerrit.pgm.Reindex$ReviewDbModule.configure(Reindex.java:204)
    while locating com.google.gerrit.reviewdb.server.ReviewDb

  1 error
    at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
    at java.util.concurrent.FutureTask.get(FutureTask.java:111)
    at com.google.gerrit.server.index.ChangeBatchIndexer$1.run(ChangeBatchIndexer.java:157)
    at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
    at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
    at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
    at com.google.common.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:91)
    at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:302)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:153)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:336)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:360)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
  Caused by: com.google.inject.ProvisionException: Guice provision errors:

  1) unable to open ReviewDb
    at com.google.gerrit.pgm.Reindex$ReviewDbModule.configure(Reindex.java:204)
    while locating com.google.gerrit.reviewdb.server.ReviewDb

  1 error
    at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:1014)
    at com.google.gerrit.server.index.ChangeBatchIndexer$3.call(ChangeBatchIndexer.java:218)
    at com.google.gerrit.server.index.ChangeBatchIndexer$3.call(ChangeBatchIndexer.java:210)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    ... 10 more
  Caused by: com.google.gwtorm.server.OrmException: Cannot open database connection
    at com.google.gwtorm.jdbc.Database.newConnection(Database.java:129)
    at com.google.gwtorm.jdbc.JdbcSchema.<init>(JdbcSchema.java:41)
    at com.google.gerrit.reviewdb.server.ReviewDb_Schema_GwtOrm$$22.<init>(Unknown Source)
    at com.google.gerrit.reviewdb.server.ReviewDb_Schema_GwtOrm$$22_Factory_GwtOrm$$23.open(Unknown Source)
    at com.google.gwtorm.jdbc.Database.open(Database.java:121)
    at com.google.gerrit.pgm.Reindex$ReviewDbModule$2.get(Reindex.java:210)
    at com.google.gerrit.pgm.Reindex$ReviewDbModule$2.get(Reindex.java:204)
    at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
    at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
    at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:1005)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1051)
    at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:1001)
    ... 13 more
  Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot get a connection, pool error Timeout waiting for idle object
    at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:114)
    at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
    at com.google.gwtorm.jdbc.Database.newConnection(Database.java:127)
    ... 26 more
  Caused by: java.util.NoSuchElementException: Timeout waiting for idle object
    at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1144)
    at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
    ... 28 more

Patch-set: 5