Update patch set 2
Patch Set 2: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 4.6s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/change/CommentJson.java:28: error: package com.google.gwt.thirdparty.guava.common.collect does not exist
import com.google.gwt.thirdparty.guava.common.collect.ComparisonChain;
                                                     ^
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/change/CommentJson.java:28: error: package com.google.gwt.thirdparty.guava.common.collect does not exist
import com.google.gwt.thirdparty.guava.common.collect.ComparisonChain;
                                                     ^
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/change/CommentJson.java:109: error: cannot find symbol
...

Patch-set: 2
Reviewer: Diffy Cuckoo (Automated Verifier) <1012977@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1