Update patch set 2
Patch Set 2:

> > Patch Set 2: Verified-1
 > >
 > > This breaks NoteDbPrimaryIT#rebuildReviewDbRequiresNoteDbPrimary
 > with GERRIT_NOTEDB=read-write. You can reproduce by downloading
 > https://gerrit-review.googlesource.com/c/gerrit/+/125970 and
 > running the tests with:
 > >
 > >  bazel test --test_env=GERRIT_NOTEDB=read-write gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/server/notedb:all
 > >
 > > Partial stack trace:
 > >
 > >  java.lang.AssertionError: Expected test to throw (an instance of
 > com.google.gwtorm.server.OrmException and exception with message a
 > string containing "primary storage of 1 is REVIEW_DB")
 > > 	at org.junit.Assert.fail(Assert.java:89)
 > > 	at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:254)
 > > 	at org.junit.rules.ExpectedException.access$200(ExpectedException.java:101)
 > > 	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:236)
 > > 	at com.google.gerrit.acceptance.AbstractDaemonTest$1$1.evaluate(AbstractDaemonTest.java:196)
 > 
 > 
 > 
 > 
 > Does not seem related to this change as we are getting the exact
 > same error without it:
 > 
 > git checkout master
 > bazel clean --expunge
 > bazel build gerrit
 > bazel test --nocache_test_results --test_env=GERRIT_NOTEDB=read-write
 > gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/server/notedb:all

Bisect is saying that this change broke the test: https://gerrit-review.googlesource.com/#/c/gerrit/+/121071/

Patch-set: 2
Reviewer: Hugo Arès <1012987@173816e5-2b9a-37c3-8a2e-48639d4f1153>