Update patch set 3
Patch Set 3:

> Patch Set 3: Code-Review+1
> 
> (1 comment)
> 
> > > Seems like this line was lost during move from master to
>  > stable-2.14: [1].
>  > >
>  > > * [1] https://gerrit-review.googlesource.com/#/c/gerrit/+/179293/1/tools/eclipse/BUILD@13
>  > 
>  > Thanks.  That fixed it.  I missed this because I was only looking
>  > at the diff between stable-2.14 and stable-2.15.
>  > 
>  > Not sure why it works on stable-2.14 though, if that was missing.
> 
> Indeed, the reason for that is because on stable-2.14: //gerrit-acceptance-tests:lib depends on //gerrit-elasticsearch:elasticsearch_test_utils, while on stable-2.15 this dependency is missing (and this is good, because in fact it's not needed, so may be we could consider to clean that up always on stable-2.14):
>  
>   $ bazel query "allpaths(//tools/eclipse:main_classpath_collect, //lib/testcontainers:testcontainers)"
>   //tools/eclipse:main_classpath_collect
>   //gerrit-acceptance-tests:lib
>   //gerrit-elasticsearch:elasticsearch_test_utils
>   //lib/testcontainers:testcontainers
> 
> I proposed alternative fix here.

It turns out that on stable-2.14 the dependency is needed because ReindexIT uses the container. Removing it causes the acceptance test build to fail:

 gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/pgm/ElasticReindexIT.java:18: error: package com.google.gerrit.elasticsearch.testing does not exist
 import com.google.gerrit.elasticsearch.testing.ElasticContainer;

This is not the case on stable-2.15 because the ES tests were reverted out of ReindexIT.

Patch-set: 3
Reviewer: David Pursehouse <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>