AutoMerger: Parse body of merge commit to fix possible NPE
In our logs we sometimes see NullPointerExceptions like this [1,2] when
calling merge.getCommitterIdent(). This exception happens if the buffer
in the merge RevCommit instance is unset. Calling rw.parseBody(merge)
populates this buffer and hence should fix this.

We don't know what exactly is causing this or how to reproduce this from
a test. JGit just fixed an issue where the buffer in RevCommit got
unexpectedly cleared [3], but we don't know if this is related and if it
would fix this issue. Since we cannot reproduce this from a test, we can
also not verify this easily.

[1]
Caused by: java.lang.NullPointerException: Cannot read the array length because "b" is null
  at org.eclipse.jgit.util.RawParseUtils.committer(RawParseUtils.java:853)
  at org.eclipse.jgit.revwalk.RevCommit.getCommitterIdent(RevCommit.java:462)
  at com.google.gerrit.server.patch.AutoMerger.createAutoMergeCommit(AutoMerger.java:314)
  at com.google.gerrit.server.patch.AutoMerger.createAutoMergeCommit(AutoMerger.java:209)
  at com.google.gerrit.server.patch.AutoMerger.createAutoMergeCommitIfNecessary(AutoMerger.java:193)
  at com.google.gerrit.server.change.PatchSetInserter.updateRepo(PatchSetInserter.java:316)
  at com.google.gerrit.server.change.RebaseChangeOp.updateRepo(RebaseChangeOp.java:404)
  ...

[2]
java.lang.NullPointerException: Cannot read the array length because "b" is null
  at org.eclipse.jgit.util.RawParseUtils.committer(RawParseUtils.java:853)
  at org.eclipse.jgit.revwalk.RevCommit.getCommitterIdent(RevCommit.java:462)
  at com.google.gerrit.server.patch.AutoMerger.createAutoMergeCommit(AutoMerger.java:314)
  at com.google.gerrit.server.patch.AutoMerger.createAutoMergeCommit(AutoMerger.java:209)
  at com.google.gerrit.server.patch.BaseCommitUtil.getAutoMergeFromGitOrCreate(BaseCommitUtil.java:135)
  at com.google.gerrit.server.patch.BaseCommitUtil.getBaseCommit(BaseCommitUtil.java:112)
  at com.google.gerrit.server.patch.DiffOperationsImpl.computeDiffParameters(DiffOperationsImpl.java:569)
  at com.google.gerrit.server.patch.DiffOperationsImpl.loadModifiedFilesAgainstParentIfNecessary(DiffOperationsImpl.java:148)
  at com.google.gerrit.server.patch.DiffOperationsForCommitValidation.loadModifiedFilesAgainstParentIfNecessary(DiffOperationsForCommitValidation.java:81)
  at com.google.gerrit.server.project.SubmitRequirementConfigValidator.isFileChanged(SubmitRequirementConfigValidator.java:116)
  at com.google.gerrit.server.project.SubmitRequirementConfigValidator.onCommitReceived(SubmitRequirementConfigValidator.java:59)
  ...

[3] https://github.com/eclipse-jgit/jgit/issues/203

Change-Id: Idb86e5541cfa0d6b42ab3b44e3cf1162f6061d7e
Signed-off-by: Edwin Kempin <ekempin@google.com>