Implement Bazel build
To run the tests:

  bazel test --test_output=all //...

The output is: [1]. Note that http_tests is failing for now, with:

java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
which is strange, because the without-neverlink version of servlet-api
lib is contained in dependency set of java_test rule:

  junit_tests(
    name = 'httpd_tests',
    srcs = glob(['src/test/java/**/*.java']),
    deps = [
      ':httpd',
      '//gerrit-common:server',
      '//gerrit-extension-api:api',
      '//gerrit-reviewdb:server',
      '//gerrit-server:server',
      '//gerrit-util-http:http',
      '//gerrit-util-http:testutil',
      '//lib:jimfs',
      '//lib:junit',
      '//lib:gson',
      '//lib:gwtorm',
      '//lib:guava',
      '//lib:servlet-api-3_1-without-neverlink',
      [...]

To build the Gerrit plugin API, run:

  bazel build gerrit-plugin-api:plugin-api_deploy.jar

To build the Gerrit extension API, run:

  bazel build  gerrit-extension-api:extension-api_deploy.jar

TODOs:

Licenses (find out how to use builtin licenses support)
Reduce visibility (all public for now)
Generate HTML Documentation
Core plugins
gerrit_plugin() rule to build plugins in tree and standalone modes
GWT UI (only gwt_module() skylark rule is provided, no gwt_binary())
PolyGerrit UI
WAR
Publish artifacts to Maven Central
Ask Bazel team to add Gerrit to their CI on ci.bazel.io

[1] http://paste.openstack.org/show/506658/

Contributed-By: Han-Wen Nienhuys <hanwen@google.com>
Change-Id: I9a86e670882a44a5c966579cdeb8ed79b1590de3