Update patch set 2
Patch Set 2: Verified-1

This is an automated message from the Diffy, the Autoverifier.

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  [-] PARSING BUILD FILES...FINISHED 4.0s
warning: [options] bootstrap class path not set in conjunction with -source 1.6
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/query/change/ChangeQueryBuilder.java:129: error: method getMaxValue in class com.google.gerrit.server.query.change.SortKeyPredicate cannot be applied to given types;
    return after != null && after.getMaxValue(schema) > 0;
                                 ^
  required: no arguments
  found: com.google.gerrit.server.index.Schema<com.google.gerrit.server.query.change.ChangeData>
  reason: actual and formal argument lists differ in length
Note: Some input files use unchecked or unsafe operations.
...

Patch-set: 2
Label: Verified=-1