Update patch set 4
Patch Set 4: Verified-1

the build fails since schema 170 doesn't exist in 2.15:

gerrit-2.15 (stable-2.15)]$ bazelisk build release
Starting local Bazel server and connecting to it...
INFO: Invocation ID: fb4e6838-1cae-4c2d-a827-70bd54f68d86
DEBUG: /private/var/tmp/_bazel_d029788/9daa99b00764d39918e83c79bd13447d/external/io_bazel_rules_closure/closure/compiler/closure_js_binary.bzl:37:5: dependency_mode=LOOSE is deprecated and will be removed soon; prefer to use its equivalent PRUNE_LEGACY
INFO: Analyzed target //:release (370 packages loaded, 8871 targets configured).
INFO: Found 1 target...
INFO: From Building gerrit-extension-api/libapi.jar (295 source files):
...
---<error prone warnings removed>
...
Use --sandbox_debug to see verbose messages from the sandbox
gerrit-server/src/main/java/com/google/gerrit/server/schema/SchemaVersion.java:40: error: could not resolve Schema_170
  public static final Class<Schema_170> C = Schema_170.class;
                            ^
Target //:release failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/d029788/src/git/gerrit-2.15/gerrit-cache-h2/BUILD:4:1 Compiling Java headers gerrit-server/libserver-hjar.jar (1401 source files) failed (Exit 1) java failed: error executing command external/remotejdk11_macos/bin/java -Xverify:none '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED' ... (remaining 13 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 348.091s, Critical Path: 102.37s
INFO: 1547 processes: 1169 remote cache hit, 337 darwin-sandbox, 1 local, 40 worker.
FAILED: Build did NOT complete successfully

Patch-set: 4
Reviewer: Gerrit User 1004034 <1004034@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1