Update patch set 17
Patch Set 17: Verified-1

Tests fail in Eclipse with:

 java.lang.NoSuchMethodError: org.apache.lucene.util.UnicodeUtil.UTF16toUTF8

which I guess is a dependency error, but I can't track down why.  UnicodeUtil is in the lucene-core jar, which is included in the deps.

Tests fail on the command line due to an elasticsearch config problem.

Patch-set: 17
Label: Verified=-1