ChangeJson: Ensure for merged changes that labels for approvals are included
There may be approvals on labels that are not contained in the submit
records. E.g. this is the case if there is an approval on a label that
is ignored by a Prolog submit rule. In this case ChangeJson was
failing with:

  com.google.gwtorm.server.OrmException: java.lang.NullPointerException
    at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:303)
    at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:285)
    at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:263)
    at com.google.gerrit.server.change.GetChange.apply(GetChange.java:50)
    at com.google.gerrit.server.change.GetDetail.apply(GetDetail.java:51)
    at com.google.gerrit.server.change.GetDetail.apply(GetDetail.java:26)
    at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:367)
    ...
  Caused by: java.lang.NullPointerException
    at com.google.gerrit.server.change.ChangeJson.setLabelScores(ChangeJson.java:670)
    at com.google.gerrit.server.change.ChangeJson.labelsForClosedChange(ChangeJson.java:845)
    at com.google.gerrit.server.change.ChangeJson.labelsFor(ChangeJson.java:598)
    at com.google.gerrit.server.change.ChangeJson.toChangeInfo(ChangeJson.java:499)
    at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:294)
    ...

Change-Id: I46073f4077d83963d4a45a50189957cd8c9a1bd0
Signed-off-by: Edwin Kempin <ekempin@google.com>