Update patch set 2
Patch Set 2:

This causes buck test to fail:

 OSError: [Errno 2] No such file or directory: 'plugins/${pluginName}'

Patch-set: 2
Reviewer: David Pursehouse <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0