Fix broken CapabilitiesIT acceptance test
Ic929dc4 broke the capabilities REST API test:

  FAILURE testCapabilitiesUser: batchChangesLimit
  java.lang.NoSuchFieldException: batchChangesLimit

Add missing initialization of default batch changes limit in the
capabilities.

Add handling of the batch changes limit field in the acceptance
test.

Change-Id: I215a9e0e9140fe528fe5b02ef764a5dd29d15eff