Update patch set 3
Patch Set 3:

Since updating my local test Gerrit to this commit, pushing commits for code review are failing with 'internal server error'. I'm using H2 and I did not enable the new thread pool.

[2012-08-06 15:22:49,751] ERROR com.google.gerrit.server.git.ReceiveCommits : Can't insert changes for ABC
com.google.gwtorm.server.OrmException: Error updating database
	at com.google.gerrit.server.git.ReceiveCommits$1.apply(ReceiveCommits.java:226)
	at com.google.gerrit.server.git.ReceiveCommits$1.apply(ReceiveCommits.java:220)
	at com.google.common.util.concurrent.Futures$MappingCheckedFuture.mapException(Futures.java:1215)
	at com.google.common.util.concurrent.AbstractCheckedFuture.checkedGet(AbstractCheckedFuture.java:85)
	at com.google.gerrit.server.git.ReceiveCommits.insertChangesAndPatchSets(ReceiveCommits.java:675)
	at com.google.gerrit.server.git.ReceiveCommits.processCommands(ReceiveCommits.java:521)
	at com.google.gerrit.server.git.AsyncReceiveCommits$Worker.run(AsyncReceiveCommits.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at com.google.gerrit.server.util.RequestScopePropagator$5.call(RequestScopePropagator.java:196)
	at com.google.gerrit.server.util.RequestScopePropagator$4.call(RequestScopePropagator.java:174)
	at com.google.gerrit.server.util.ThreadLocalRequestScopePropagator$1.call(ThreadLocalRequestScopePropagator.java:58)
	at com.google.gerrit.server.util.RequestScopePropagator$1.call(RequestScopePropagator.java:81)
	at com.google.gerrit.server.util.RequestScopePropagator$2.run(RequestScopePropagator.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:337)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Cannot continue request, thread already has request in progress. A new thread must be used to propagate the request scope context.
	at java.util.concurrent.FutureTask$Sync.innerGet(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:63)
	at com.google.common.util.concurrent.AbstractCheckedFuture.checkedGet(AbstractCheckedFuture.java:78)
	... 18 more
Caused by: java.lang.IllegalStateException: Cannot continue request, thread already has request in progress. A new thread must be used to propagate the request scope context.
	at com.google.gerrit.server.util.ThreadLocalRequestScopePropagator$1.call(ThreadLocalRequestScopePropagator.java:51)
	at com.google.gerrit.server.util.RequestScopePropagator$1.call(RequestScopePropagator.java:81)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:56)
	at com.google.gerrit.server.git.ReceiveCommits$CreateRequest.insertChange(ReceiveCommits.java:1291)
	at com.google.gerrit.server.git.ReceiveCommits.insertChangesAndPatchSets(ReceiveCommits.java:671)
	... 17 more

Patch-set: 3