Update patch set 1
Patch Set 1: Verified-1

These are used by PatchTable:

 gerrit-gwtui/src/main/java/com/google/gerrit/client/patches/PatchTable.java:438: error: cannot find symbol
      Anchor sideBySide = new Anchor(Util.C.diffAllSideBySide());
                                           ^
  symbol:   method diffAllSideBySide()
  location: variable C of type com.google.gerrit.client.changes.ChangeConstants

 gerrit-gwtui/src/main/java/com/google/gerrit/client/patches/PatchTable.java:450: error: cannot find symbol
      Anchor unified = new Anchor(Util.C.diffAllUnified());
                                        ^
  symbol:   method diffAllUnified()
  location: variable C of type com.google.gerrit.client.changes.ChangeConstants
 Errors: 2. Warnings: 0.

So we can't remove them yet?

Patch-set: 1
Reviewer: Shawn Pearce <1001240@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1