Update patch set 3
Patch Set 3:

With this change, I'm having issue with launching the daemon from Eclipse. It fails with:

[2015-05-07 15:41:35,110] ERROR com.google.gerrit.pgm.Daemon : Unable to start daemon
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="/Users/d044411/site/index/changes_0016/open/segments_2"))): 5 (needs to be between 0 and 4)
  at com.google.gerrit.lucene.LuceneChangeIndex.<init>(LuceneChangeIndex.java:219)
  while locating com.google.gerrit.lucene.LuceneChangeIndex annotated with @com.google.inject.internal.UniqueAnnotations$Internal(value=10)

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1018)
	at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:679)
	at com.google.gerrit.lucene.$Proxy103.create(Unknown Source)
	at com.google.gerrit.lucene.LuceneVersionManager.start(LuceneVersionManager.java:156)
	at com.google.gerrit.lifecycle.LifecycleManager.start(LifecycleManager.java:74)
	at com.google.gerrit.pgm.Daemon.start(Daemon.java:295)
	at com.google.gerrit.pgm.Daemon.run(Daemon.java:205)
	at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:157)
	at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:93)
	at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:50)
	at Main.main(Main.java:25)
Caused by: org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="/Users/d044411/site/index/changes_0016/open/segments_2"))): 5 (needs to be between 0 and 4)
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:217)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:826)
	at com.google.gerrit.lucene.AutoCommitWriter.<init>(AutoCommitWriter.java:33)
	at com.google.gerrit.lucene.SubIndex.<init>(SubIndex.java:79)
	at com.google.gerrit.lucene.SubIndex.<init>(SubIndex.java:62)
	at com.google.gerrit.lucene.LuceneChangeIndex.<init>(LuceneChangeIndex.java:259)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.google.inject.internal.DefaultConstructionProxyFactory$2.newInstance(DefaultConstructionProxyFactory.java:86)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:108)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
	... 15 more

Patch-set: 3