Update patch set 1
Patch Set 1: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 2.8s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/project/ListProjects.java:292: error: variable ex is already defined in method display(java.io.OutputStream)
          } catch (NoSuchGroupException ex) {
                                        ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Errors: 1. Warnings: 0.
BUILD FAILED: //gerrit-server:server failed with exit code 1:
...

Patch-set: 1
Reviewer: Diffy Cuckoo (Automated Verifier) <1012977@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1