Update patch set 1
Patch Set 1:

The breakage is related. That's because polylint_test is invoked with bazel and not bazelisk in package.json:

   "polylint": "bazel test polygerrit-ui/app:polylint_test"

And given that there is no Bazel 2.1.0 yet installed on GerritForge docker image, the bazel check is failing:

  $ ./node_modules/eslint/bin/eslint.js --ext .html,.js polygerrit-ui/app
  Done in 21.59s.
  + yarn polylint
  yarn run v1.21.1
  $ bazel test polygerrit-ui/app:polylint_test
  ERROR: The project you're trying to build requires Bazel 2.1.0
  (specified in /home/jenkins/workspace/Gerrit-codestyle/gerrit/.bazelversion),
  but it wasn't found in /usr/bin.

In all other places we are checking of bazelisk installed and use it and fall back to bazel. Should we change `bazel test polygerrit-ui/app:polylint_test` to just `bazelisk test polygerrit-ui/app:polylint_test` in package.json?

Another option is to change the GerritForge CI docker image and change bazel to be a symbolic link to bazelisk.

The last opion is to figure out how to check bazelisk and use it or fall back to bazel in package.json.

Patch-set: 1
Reviewer: Gerrit User 1011123 <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Gerrit User 1012732 <1012732@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Gerrit User 1065256 <1065256@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Gerrit User 1006192 <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>