Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > I think this breaks the build on master:
>  > 
>  > hiesel@hiesel:~/gerrit(master)$ bazel build //...
>  > ERROR: /usr/local/google/home/hiesel/gerrit/javatests/com/google/gerrit/elasticsearch/BUILD:30:2:
>  > no such target '//javatests/com/google/gerrit/server:abstract_query_tests':
>  > target 'abstract_query_tests' not declared in package
>  > 'javatests/com/google/gerrit/server' defined by /usr/local/google/home/hiesel/gerrit/javatests/com/google/gerrit/server/BUILD
>  > and referenced by '//javatests/com/google/gerrit/elasticsearch:elasticsearch_accounts_test'
> 
> Thanks for letting us know. Investigating. Can it be that ES tests don't run on CI? I'm asking, because the CI was green wth this change.

Ugh, yes, it's most likely the reason.

Previously ES tests were disabled because they were unstable.

Maybe we should undo it. IIUC the tests are stable enough now.

Patch-set: 3