Update JGit to recent snapshot
This includes a new method on Repository, so our subclass needs to be
updated.

Also requires disabling atomic updates on InMemoryRepositoryMangers
used by acceptance tests, since a bug in the atomic implementation
causes BanCommitIT to fail:

 FAILURE com.google.gerrit.acceptance.rest.project.BanCommitIT banCommit: Not true that null reference starts with <"contains banned commit">
 java.lang.AssertionError: Not true that null reference starts with <"contains banned commit">
 	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:24)
 	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:20)
 	at com.google.common.truth.Subject.failWithRawMessage(Subject.java:381)
 	at com.google.common.truth.StringSubject.startsWith(StringSubject.java:167)
 	at com.google.gerrit.acceptance.rest.project.BanCommitIT.banCommit(BanCommitIT.java:49)

This is because ReceiveCommits rejects the command but still executes
the batch, and the relevant part of InMemoryRepository doesn't ensure
updates are NOT_ATTEMPTED before trying to apply them.

Change-Id: Icd2485c51723119c897406806e2f6e086831df3e