SshDaemon: More logging to debug channel tracking
This is a follow-on to issue Ib41c94fc43aca7c4916d40128f03b643cee66d9a.

We are still having users who are having connections fail, and the
logs showing

 SshChannelNotFoundException: Received SSH_MSG_CHANNEL_WINDOW_ADJUST on unassigned channel 0 (last assigned=null)

This error seems strange, because "last_assigned" is unset, suggesting
that a channel has never been opened; but the client is sending
window-adjustment commands, which presuambly means it thinks the
channel *has* been opened.

This has had some discussion in [1] and a convincing explaination is,
so far, not forthcoming.  As suggested there, this adds some more
logging points that might help to further debug this issue.

[1] https://github.com/apache/mina-sshd/issues/319

Change-Id: I975f9d1e91674a2fd7d9951ea258300e110ca045