Replace gitiles-servlet with blame-cache
Depending on the (whole) gitiles-servlet was causing class loading issues
when loading the gitiles plugin:

  java.lang.NoClassDefFoundError: com/google/template/soy/SoyFileSet

because gitiles-servlet was loaded by Gerrit's class loader but its
dependencies were only available to the plugin's class loader.

Change-Id: I7a7666a6227fe1668db11d0d82aff543c39ca47f