Bazel: Add no_rbe tag to //tools/bzl:always_pass_test
We are in process to run all tests on RBE platform, to have faster
throughput for test verification: it take a few seconds to run all
Gerrit tests on RBE platform.

However, when all tests are moved to RBE, then bazel test invocation
is failing with:

  $ bazelisk test --test_tag_filters=-flaky,elastic,no_rbe //...
  WARNING: All specified test targets were excluded by filters
  ERROR: No test targets were found, yet testing was requested

That's because no test rules wee tagged with elastic,no_rbe tags
on Gerrit@HEAD.

We should disable non RBE checker entirely, but to make the test pass
for now we add no_rbe tag to always_pass_test rule. It was added so that
test verification for plugin changes always succeed, also in the case
when plugins don't have any tests.

Change-Id: I5bf5170acdc6ccd42e583b733498cfb4fd8e724c