Update patch set 8
Patch Set 8:

@David Pursehouse im wondering could i have help please since it keeps failing to build.

with errors like

ProjectTagsScreen.java:408: error: cannot find symbol
      if (k.canDelete()) {
           ^
  symbol:   method canDelete()
  location: variable k of type com.google.gerrit.client.projects.TagInfo
/home/paladox/gerrit4/gerrit-gwtui/src/main/java/com/google/gerrit/client/admin/ProjectTagsScreen.java:430: error: cannot find symbol
      if (k.webLinks() != null) {


please?

Patch-set: 8
Label: Verified=0