Update git submodules
* Update plugins/gitiles from branch 'stable-3.3'
  to d83dc8b0cd4b56a769b4c6ce909ba9c3a79aa2a1
  - Merge branch 'stable-3.2' into stable-3.3
    
    * stable-3.2:
      fix: cannot build 'gerrit-3.2' on MacOS
      Load fonts directly from Gerrit instead of 3rd party domains
    
    Change-Id: I1bb1c0a342dc91961ac54aa340ccfb09db4ed7f6
    
  - fix: cannot build 'gerrit-3.2' on MacOS
    
    When `bazel build release` is called the following issue is being
    thrown:
      ERROR: /Users/jacek.centkowski/workspace/open/open-source/gerrit/plugins/gitiles/BUILD:23:9: Executing genrule //plugins/gitiles:gitiles-servlet-resources failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
    
      Use --sandbox_debug to see verbose messages from the sandbox
      sed: -I or -i may not be used with stdin
      Target //plugins/gitiles:gitiles failed to build
    
    It seems that 'Load fonts directly from Gerrit instead of 3rd party
    domains' introduced the `sed` transformation that is not supported under
    MacOS. As suggested in [1] the most portable way is to handle the backup
    file in the command line (at least it works on MacOS ;)).
    
    [1] https://stackoverflow.com/a/21243111
    
    Bug: Issue 15307
    Change-Id: I3c40bc42d0a0d1a25aacd1cd2687af03970f88b4
    
  - Merge "Load fonts directly from Gerrit instead of 3rd party domains" into stable-3.2
  - Merge branch 'stable-3.2-2021-07' into stable-3.2
    
    * stable-3.2-2021-07:
      Hide repository name and description when user has no access
    
    Change-Id: I1ebc91324242ca960c065360ea62fce6d725254b
    
  - Load fonts directly from Gerrit instead of 3rd party domains
    
    In environments without public Internet access or where tight control
    of loaded resources is necessary, loading fonts from 3rd party domains
    might be restricted. Hence, we switch to the fonts directly supplied
    by Gerrit.
    
    gitiles loads only the fonts 'Open Sans' and 'Source Code Pro'. Gerrit
    provides 'Open Sans' directly and offers 'Roboto Mono' as monospace
    alternative to 'Source Code Pro'.
    
    Change-Id: I4f4a0b7dd575cbc27641063e05d13b8a43a51d8b