Update patch set 6
Patch Set 6:

Fails with

ERROR: /home/jenkins/workspace/Gerrit-verifier-bazel/gerrit/gerrit-sshd/BUILD:5:1: Java compilation in rule '//gerrit-sshd:sshd' failed: Worker process sent response with exit code: 1..
gerrit-sshd/src/main/java/com/google/gerrit/sshd/HostKeyProvider.java:75: error: cannot find symbol
    FileKeyPairProvider kp = SecurityUtils.createFileKeyPairProvider();
                                          ^
  symbol:   method createFileKeyPairProvider()
  location: class SecurityUtilsgerrit-sshd/src/main/java/com/google/gerrit/sshd/SshDaemon.java:684: error: <anonymous com.google.gerrit.sshd.SshDaemon$3> is not abstract and does not override abstract method canForwardX11(Session,String) in ForwardingFilter
        new ForwardingFilter() {
                               ^gerrit-sshd/src/main/java/com/google/gerrit/sshd/SshDaemon.java:685: error: method does not override or implement a method from a supertype
          @Override
          ^gerrit-sshd/src/main/java/com/google/gerrit/sshd/SshDaemon.java:690: error: method does not override or implement a method from a supertype
          @Override
          ^____Elapsed time: 37.332s, Critical Path: 31.13s

now.

One of the errors was caused by this https://github.com/apache/mina-sshd/commit/0d7af8c8e052e1f7f980f18ec9795cff8f8af833#diff-975a65ed2dd3869b787e25b2011a2b23

Patch-set: 6
Reviewer: Paladox none <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>