Update patch set 1
Patch Set 1: Verified-1

> Patch Set 1: Code-Review+1
> 
> Another option to cherry pick to 2.16 as well?

Maybe once it is done confirming in stable-3.1, for which Issue 12218 is about (and master). I'm currently unable to run HA plugin tests in standalone with this change building the api:

flushProjectsCacheShouldSendPostForEvictingRemoteCache(com.ericsson.gerrit.plugins.highavailability.cache.CacheEvictionIT)
java.lang.NoClassDefFoundError: com/google/gerrit/pgm/Init
at com.google.gerrit.acceptance.GerritServer.init(GerritServer.java:342)
(...)

I also noticed that issue when testing HA plugin stand-alone in master. -Seems like this change (from master) broke the availability of at least that pgm class to the standalone testing runtime.

Patch-set: 1
Reviewer: Gerrit User 1012732 <1012732@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1