Update patch set 14
Patch Set 14:

> ❌ bazel/reviewdb : FAILURE

This is related:

ERROR: /home/jenkins/workspace/Gerrit-verifier-bazel/gerrit/BUILD:26:17: in java_home attribute of java_runtime rule //:absolute_javabase: $(ABSOLUTE_JAVABASE) not defined
ERROR: Analysis of target '//:absolute_javabase' failed; build aborted: Analysis of target '//:absolute_javabase' failed; build aborted

This is because we implemented :absolute_javabase in root BUILD file, and because the CI is building /... now. Once new bazel version is released with this change included: [1] we could remove that.

* [1] https://github.com/bazelbuild/bazel/commit/0173bdbf7bdd1874379d4dd3eb70d5321e0f1816

Patch-set: 14
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>