Bazel: Bump rules_closure to 3.10.0-rc1
The new rules_closure version was adapted to fixes needed for
--incompatible_load_{java|proto|python}_rules_from_bzl option,
but it seems that this changes exposes the very same issue, that
was reported here: [1].

$ bazel build :release
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/command.profile.gz'
INFO: Invocation ID: ea7c8f78-ccb9-4a14-981f-9a676c4383cd
ERROR: Failed to load Starlark extension '@rules_java//java:defs.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @rules_java
This could either mean you have to add the '@rules_java' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.

[1] https://github.com/bazelbuild/bazel/issues/9291

Change-Id: I82fc3d65fba40b8f966ca458dbfb93ff7068aafa