Update patch set 24
Patch Set 24: -Code-Review

Trying to upgrade an existing site, fails for me with:

Migrating data to schema 142 ...
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/crypto/generators/BCrypt
	at com.google.gerrit.server.account.HashedPassword.hashPassword(HashedPassword.java:74)
	at com.google.gerrit.server.account.HashedPassword.fromPassword(HashedPassword.java:80)
	at com.google.gerrit.server.schema.Schema_142.migrateData(Schema_142.java:38)
	at com.google.gerrit.server.schema.SchemaVersion.migrateData(SchemaVersion.java:153)
	at com.google.gerrit.server.schema.SchemaVersion.upgradeFrom(SchemaVersion.java:92)
	at com.google.gerrit.server.schema.SchemaVersion.check(SchemaVersion.java:83)
	at com.google.gerrit.server.schema.SchemaUpdater.update(SchemaUpdater.java:112)
	at com.google.gerrit.pgm.init.BaseInit$SiteRun.upgradeSchema(BaseInit.java:386)
	at com.google.gerrit.pgm.init.BaseInit.run(BaseInit.java:143)
	at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:203)
	at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:108)
	at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:63)
	at Main.main(Main.java:24)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.crypto.generators.BCrypt
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

Patch-set: 24
Reviewer: ekempin <1003935@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=0