Update patch set 13
Patch Set 13: Verified+1

> Gerrit-CI Build: https://gerrit-ci.gerritforge.com/job/Gerrit-verifier-default/11659/consoleText

CI is failing because it uses Java 7.

 java.lang.IllegalArgumentException: invalid source release: 8

The tests pass locally, although they seem to be running a lot slower than with Java 7.

Patch-set: 13
Label: Verified=+1