Unwrap ReviewDb in DbGroupMemberAuditListener
DbGroupMemberAuditListener needs to still be able to read from ReviewDb
even when read access is turned off. Whenever write access to ReviewDb
is turned off we need to make sure that DbGroupMemberAuditListener is
not called anymore.

This commit fixes the following stacktraces (which also lead to
inconsistencies between ReviewDb and NoteDb):

Failed to log delete accounts from group event
java.lang.UnsupportedOperationException: This table has been migrated to NoteDb
  at com.google.gerrit.reviewdb.server.DisallowReadFromGroupsReviewDbWrapper$GroupMemberAudits.byGroupAccount(DisallowReadFromGroupsReviewDbWrapper.java:220)
  at com.google.gerrit.server.group.DbGroupMemberAuditListener.onDeleteAccountsFromGroup(DbGroupMemberAuditListener.java:83)
  at com.google.gerrit.server.audit.AuditService.dispatchDeleteAccountsFromGroup(AuditService.java:62)
  at com.google.gerrit.server.group.db.GroupsUpdate.removeGroupMembersInReviewDb(GroupsUpdate.java:396)
  at com.google.gerrit.server.group.db.GroupsUpdate.updateMembersInReviewDb(GroupsUpdate.java:365)

Change-Id: Ib0370a7517ff831e0f0898b7893bae61707ac091