Fix Code Owners regression
When clicking on Add Owners, app was throwing js error:
Error: plugin 'code-owners' endpoint 'reply-reviewers': param is missing
a name.

Google-Bug-Id: b/231958341
Release-Notes: skip
Change-Id: Iff9488506359051efe20e3270353bef4868bd5b8