Update patch set 2
Patch Set 2:

> > NoteDB - Gerrit-CI Build: https://gerrit-ci.gerritforge.com/job/Gerrit-verifier-notedb/767/consoleText
 > 
 > LuceneQueryChangesV14Test byHashtagWithNotedb: Not true that
 > hashtag:foo (<[2]>) contains exactly <[2, 1]>. It is missing <[1]>
 > java.lang.AssertionError: Not true that hashtag:foo (<[2]>)
 > contains exactly <[2, 1]>. It is missing <[1]>
 > 
 > Unrelated?

I've seen the same failure on other changes, so no, I don't think it's caused by this change.

Patch-set: 2