Update patch set 1
Patch Set 1:

> NoteDB - Gerrit-CI Build: https://gerrit-ci.gerritforge.com/job/Gerrit-verifier/1705/consoleText

Change edit tests are failing again and again on the CI:

  1) hasEdit(com.google.gerrit.server.query.change.LuceneQueryChangesTest)
  java.lang.AssertionError: Not true that query 'has:edit' with expected changes [{2 (I326525e2d86f0882b8624345e063b136ad08923d), dest=repo,refs/heads/master, status=NEW, 
  lastUpdated=1254344400000}, {1 (Ib53ede6016ab00392d2f4643b923d4837f9329e1), dest=repo,refs/heads/master, status=NEW, lastUpdated=1254344400000}] and result [{1 
  (Ib53ede6016ab00392d2f4643b923d4837f9329e1), dest=repo,refs/heads/master, status=NEW, lastUpdated=1254344400000}, {2 (I326525e2d86f0882b8624345e063b136ad08923d), 
  dest=repo,refs/heads/master, status=NEW, lastUpdated=1254344400000}] (<[1, 2]>) contains only these elements in order <[2, 1]>
	at com.google.gerrit.server.query.change.AbstractQueryChangesTest.assertQuery(AbstractQueryChangesTest.java:1874)
	at com.google.gerrit.server.query.change.AbstractQueryChangesTest.assertQuery(AbstractQueryChangesTest.java:1866)
	at com.google.gerrit.server.query.change.AbstractQueryChangesTest.hasEdit(AbstractQueryChangesTest.java:1535)

So the question is: why is the order of resulting changes from the secondary index is not stable? Before thinking to deactivate the tests entirely, should we relax the tests to not test in order?

@Dave any opinion here?

Patch-set: 1