Update patch set 2
Patch Set 2: I would prefer that you didn't submit this

Making comments on the common ancestor seems to work now.

Yes, this feature is definitely useful for us. Not too often, but from time to time we get this question from our users, how for a merge commit they can see what comes in from the other branch. I think this is what can now be seen by choosing common ancestor as 'Old Version History'.

After thinking a bit more about this scenario I would like to share some thoughts.

If I choose 'Auto Merge' I see only those files for which conflicts were resolved or which were just modified in the merge commit (maybe a third file needed to be touched in order to resolve a conflict). It makes sense to look at this set of files because these modifications were not reviewed yet, while everything else which comes in by merging the other branch was already reviewed for that other branch.

If I choose 'Common Ancestor' I see all those files which were modified on the other branch. Looking at this file set helps to understand what is merged into the destination branch.

I wonder if a combined view, where I would see both file sets from 'Auto Merge' and 'Common Ancestor', would also make sense. This would show the diff between the merge commit and its paret commit from the destination branch. This view would allow me to see how the destination branch will change by submitting the merge commit. Do you think this view makes sense?

Also I'm wondering what is the best way to see inline comments. Let's assume another reviewer looks at the merge commit and uses the 'Common Ancestor' view and he now comments on files that are only visible in this view, if I now look at the change in 'Auto Merge' view I'll not see the inline comments of the other reviewer (because the commented files are not shown in the 'Auto Merge' file set). Again, maybe a combined view where I can see all the files (with their inline comments) would be useful. Or would it maybe make sense to always show files that have inline comments? I'm not sure about this, but would like to know what you think about it.

I also noticed another small issue. If I have chosen 'Common Ancestor' and I'm now clicking on 'Review' and 'Publish', now 'Auto Merge' is selected as 'Old Version History' but the shown file set is still the 'Common Ancestor' file set. The same happens when I have chosen 'Common Ancestor' and I'm clicking on a file to see the diff, if I'm now navigating back to the change by clicking on 'Up To Change' 'Auto Merge' is selected as 'Old Version History' but the shown file set is still the 'Common Ancestor' file set.

Also when trying out this change I very often got an ArrayIndexOutOfBoundsException when trying to look at the file diff for one of the files in the 'Common Ancestor' file set. I'm not sure if this exception is related to your change since I have seen it already in other contexts, however in this scenario I'm getting it for most files in the 'Common Ancestor' file set. Don't know maybe I'm just unlucky to hit this problem while trying out this change:
[2012-03-29 12:47:47,434] WARN  / : Error in patchScript
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 64
	at org.eclipse.jgit.util.IntList.get(IntList.java:82)
	at org.eclipse.jgit.diff.RawText.getEnd(RawText.java:215)
	at org.eclipse.jgit.diff.RawText.getString(RawText.java:187)
	at org.eclipse.jgit.diff.RawText.getString(RawText.java:166)
	at com.google.gerrit.httpd.rpc.patch.PatchScriptBuilder.packContent(PatchScriptBuilder.java:377)
	at com.google.gerrit.httpd.rpc.patch.PatchScriptBuilder.build(PatchScriptBuilder.java:207)
	at com.google.gerrit.httpd.rpc.patch.PatchScriptBuilder.toPatchScript(PatchScriptBuilder.java:125)
	at com.google.gerrit.httpd.rpc.patch.PatchScriptFactory.call(PatchScriptFactory.java:155)
	at com.google.gerrit.httpd.rpc.patch.PatchScriptFactory.call(PatchScriptFactory.java:60)
	at com.google.gerrit.httpd.rpc.Handler.to(Handler.java:65)
	at com.google.gerrit.httpd.rpc.patch.PatchDetailServiceImpl.patchScript(PatchDetailServiceImpl.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

Patch-set: 2
Label: Code-Review=-1
Label: Verified=0