Update patch set 27
Patch Set 27: Verified+1

> Gerrit-CI Build: https://gerrit-ci.gerritforge.com/job/Gerrit-verifier-change/5845/console

@Luca, in previous jenkins CI flow implementation, Buck verification was only scheduled, when BUCK files were present. In current implementation, it's always scheduled, even on this change where Buck build was removed:

  Archiving artifacts
  ERROR: No artifacts found that match the file pattern "gerrit/buck-out/gen/*.war,gerrit/buck-out/gen/plugins/*/*.jar,gerrit/buck-out/gen/*api/*api.jar, gerrit/buck-out/gen/gerrit-acceptance-framework/*.jar
  ". Configuration error?
  ERROR: ?gerrit/buck-out/gen/*.war? doesn?t match anything: ?gerrit? exists but not ?gerrit/buck-out/gen/*.war?

I filed this issue to change it and prepare the CI for Buck removal: [1].

* [1] https://bugs.chromium.org/p/gerrit/issues/detail?id=5306

Patch-set: 27
Label: Verified=+1