Update patch set 6
Patch Set 6:

Yea, it would have to be something actually introduced by this change...here's a fuller build log...does this shed any light on the issue?

[-] PARSING BUILD FILES...FINISHED 1.8s
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/Gerrit.java:885: error: unmappable character for encoding ASCII
    userSummaryPanel.add(new InlineLabel(" ???"));
                                           ^   
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/Gerrit.java:885: error: unmappable character for encoding ASCII
    userSummaryPanel.add(new InlineLabel(" ???"));
                                            ^   
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/Gerrit.java:885: error: unmappable character for encoding ASCII
    userSummaryPanel.add(new InlineLabel(" ???"));
                                             ^   
warning: [options] bootstrap class path not set in conjunction with -source 1.6 
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/Gerrit.java:45: error: package com.google.gerrit.extensions.webui does not exist
import com.google.gerrit.extensions.webui.GerritTopMenu;
                                         ^   
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/Gerrit.java:45: error: package com.google.gerrit.extensions.webui does not exist
import com.google.gerrit.extensions.webui.GerritTopMenu;
                                         ^   
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/Gerrit.java:207: error: package GerritTopMenu does not exist
    LinkMenuBar diffBar = menuBars.get(GerritTopMenu.DIFFERENCES.menuName);
                                                    ^   
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/Gerrit.java:668: error: package GerritTopMenu does not exist
    menuBars.put(GerritTopMenu.ALL.menuName, m); 
                              ^   
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/Gerrit.java:676: error: package GerritTopMenu does not exist
      menuBars.put(GerritTopMenu.MY.menuName, m); 
                                ^   
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/Gerrit.java:690: error: package GerritTopMenu does not exist
    menuBars.put(GerritTopMenu.DIFFERENCES.menuName, diffBar);
                              ^   
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/Gerrit.java:707: error: package GerritTopMenu does not exist
    menuBars.put(GerritTopMenu.PROJECTS.menuName, projectsBar);
                              ^   
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/Gerrit.java:719: error: package GerritTopMenu does not exist
      menuBars.put(GerritTopMenu.PEOPLE.menuName, peopleBar);
                                ^   
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/Gerrit.java:725: error: package GerritTopMenu does not exist
      menuBars.put(GerritTopMenu.PLUGINS.menuName, pluginsBar);
                                ^   
/home/deckard/workspace/gerrit/gerrit-gwtui/src/main/java/com/google/gerrit/client/Gerrit.java:751: error: package GerritTopMenu does not exist
      menuBars.put(GerritTopMenu.DOCUMENTATION.menuName, m); 
                                ^   
BUILD FAILED: //gerrit-gwtui:ui_module failed on step "javac" with exit code 1

Patch-set: 6
Reviewer: Conley Owens <1006257@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=0