Don't always close URLClassLoaders
The documentation[1] says:
"Closes this URLClassLoader, so that it can no longer be used to load
new classes or resources that are defined by this loader."

This was incorrectly converted to try-with-resources in [2].

The purpose of this method is to add URLs to the existing ClassLoader
so they can be used in the future, so closing it immediately is
counterproductive, and indeed was causing NoClassDefFoundErrors when
trying to start Gerrit.

[1] http://docs.oracle.com/javase/7/docs/api/java/net/URLClassLoader.html#close()
[2] Iead344269bc0b985b2cd2176f15a764e6a0abb70

Change-Id: I322b665a164e1783ca872ba7dcafdc9ad09e139a