WIP: Turn on SIMPLE compilation mode
This does not compile, it is just to repro the Behavior compile error.

Run
$ bazel build polygerrit-ui/app/polygerrit_ui_closure_bin

And you should see a bunch of errors like this one:

bazel-out/k8-fastbuild/bin/polygerrit-ui/app/gr-app.js:67428: ERROR - Behaviors must be global names or qualified names that are declared as object literals or array literals of other valid Behaviors.
      Gerrit.KeyboardShortcutBehavior,
      ^
  ProTip: "JSC_POLYMER_UNQUALIFIED_BEHAVIOR" can be added to the `suppress` attribute of:
  //polygerrit-ui/app:polygerrit_ui_closure_lib

There might be other errors, but if we get past this one without creating new ones, that would be a step forward.

Change-Id: Iefd4aa75ad8e56d1daf3526bbe0c0a23cc92825a