Workarounds to make the buck build work with Python 2.6
* Context management was only introduced for the `ZipFile` object in
Python 2.7.  This means code like:

 with ZipFile('file.zip') as zip_file:
   for n in zip_file.namelist():
     ...

causes an exception:

  AttributeError: ZipFile instance has no attribute '__exit__'

Fix this by rewriting the code as:

 zip_file = ZipFile('file.zip')
 for n in zip_file.namelist():
   ..
 zip_file.close()

Also add handling of `BadZipfile` and `LargeZipFile` errors.

* The `check_output` method in `subprocess` was only added in
Python 2.7.  Importing it in Python 2.6 results in an `ImportError`.

Catch `ImportError` and implement `check_output` locally using
functionality available in Python < 2.7

Change-Id: I6665cf40867cdc8a6fb8b044839735ff0988b1e3