Update patch set 4
Patch Set 4:

Not sure why this fails with

Time: 247.104
There was 1 failure:
1) hasEdit(com.google.gerrit.server.query.change.LuceneQueryChangesTest)
java.lang.AssertionError: Not true that query 'has:edit' with expected changes [{2 (I326525e2d86f0882b8624345e063b136ad08923d), dest=repo,refs/heads/master, status=NEW, lastUpdated=1254344400000}, {1 (Ib53ede6016ab00392d2f4643b923d4837f9329e1), dest=repo,refs/heads/master, status=NEW, lastUpdated=1254344400000}] and result [{1 (Ib53ede6016ab00392d2f4643b923d4837f9329e1), dest=repo,refs/heads/master, status=NEW, lastUpdated=1254344400000}, {2 (I326525e2d86f0882b8624345e063b136ad08923d), dest=repo,refs/heads/master, status=NEW, lastUpdated=1254344400000}] (<[1, 2]>) contains only these elements in order <[2, 1]>
	at com.google.gerrit.server.query.change.AbstractQueryChangesTest.assertQuery(AbstractQueryChangesTest.java:1874)
	at com.google.gerrit.server.query.change.AbstractQueryChangesTest.assertQuery(AbstractQueryChangesTest.java:1866)
	at com.google.gerrit.server.query.change.AbstractQueryChangesTest.hasEdit(AbstractQueryChangesTest.java:1535)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.google.gerrit.testutil.GerritServerTests$1$1.evaluate(GerritServerTests.java:43)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:168)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:140)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:79)
Caused by: java.lang.AssertionError: Not true that query 'has:edit' with expected changes [{2 (I326525e2d86f0882b8624345e063b136ad08923d), dest=repo,refs/heads/master, status=NEW, lastUpdated=1254344400000}, {1 (Ib53ede6016ab00392d2f4643b923d4837f9329e1), dest=repo,refs/heads/master, status=NEW, lastUpdated=1254344400000}] and result [{1 (Ib53ede6016ab00392d2f4643b923d4837f9329e1), dest=repo,refs/heads/master, status=NEW, lastUpdated=1254344400000}, {2 (I326525e2d86f0882b8624345e063b136ad08923d), dest=repo,refs/heads/master, status=NEW, lastUpdated=1254344400000}] (<[1, 2]>) contains only these elements in order <[2, 1]>
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:28)
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:22)
	at com.google.common.truth.Subject.failComparingToStrings(Subject.java:335)
	at com.google.common.truth.Subject.fail(Subject.java:312)
	at com.google.common.truth.IterableSubject$NotInOrder.inOrder(IterableSubject.java:417)
	... 47 more

Patch-set: 4