Update patch set 4
Patch Set 4: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 4.8s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/events/JsonEventSource.java:18: error: cannot find symbol
import com.google.gerrit.common.ChangeListener;
                               ^
  symbol:   class ChangeListener
  location: package com.google.gerrit.common
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/events/JsonEventSource.java:42: error: cannot find symbol
      DynamicSet<ChangeListener> unrestrictedListeners) {
...

Patch-set: 4
Label: Verified=-1