Update patch set 11
Patch Set 11:

> Patch Set 11:
> 
> > Patch Set 11:
> > 
> > In retrospect, was it good to choose 1.0.0rc2 over 0.29.1rc2? (0.29.1 wasn't released at the time this was created+merged, but was soon due to release with the same fixes.) Reportedly, IntelliJ plugin is incompatible for now [...]
> 
> What is the error message?

It was Tony to report this on Slack. I have reproduced this as well.

Version of the plugin: v2019.08.05 (latest for 2019.1.x), press Full Sync

I would need to update IntelliJ to 2019.2 to get a newer version of the plugin (v2019.08.19).

 $ echo "0.29.1" > .bazelversion

... fixes it for me for now.

ERROR: /path/to/gerrit/tools/BUILD:11:1: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on py_binary rule //tools:merge_jars: 
Traceback (most recent call last):
	File "/path/to/gerrit/tools/BUILD", line 11
		@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
	File "/home/user/.cache/bazel/_bazel_gert/657d7487a554575c9d983baaafc6bd5d/external/intellij_aspect/intellij_info_bundled.bzl", line 54, in _aspect_impl
		intellij_info_aspect_impl(target, ctx, semantics)
	File "/home/user/.cache/bazel/_bazel_gert/657d7487a554575c9d983baaafc6bd5d/external/intellij_aspect/intellij_info_impl.bzl", line 889, in intellij_info_aspect_impl
		collect_py_info(target, ctx, semantics, ide_info, <2 more arguments>)
	File "/home/user/.cache/bazel/_bazel_gert/657d7487a554575c9d983baaafc6bd5d/external/intellij_aspect/intellij_info_impl.bzl", line 294, in collect_py_info
		struct_omit_none(sources = sources, launcher = py_l..., <2 more arguments>)
	File "/home/user/.cache/bazel/_bazel_gert/657d7487a554575c9d983baaafc6bd5d/external/intellij_aspect/intellij_info_impl.bzl", line 298, in struct_omit_none
		_get_python_srcs_version(ctx)
	File "/home/user/.cache/bazel/_bazel_gert/657d7487a554575c9d983baaafc6bd5d/external/intellij_aspect/intellij_info_impl.bzl", line 270, in _get_python_srcs_version
		getattr(ctx.rule.attr, "srcs_version", defau...")
unexpected keyword 'default', for call to function getattr(x, name, default = unbound)

Patch-set: 11
CC: Gerrit User 1072905 <1072905@173816e5-2b9a-37c3-8a2e-48639d4f1153>