Update patch set 9
Patch Set 9: Code-Review-1

The one comment about logging the effective gc configuration is still unaddressed. I'm not quite sure how to do this (see inline question on ps 7).

Also I just noticed that the gc log file entries do not only appear in the gc log, but also in the error_log. Haven't checked yet what needs to be changed to prevent the log entries from appearing in the error_log.

Also it looks like the gc is corrupting the repositories, after running the gc several times now, I'm getting for almost all my test repositories 

  org.eclipse.jgit.errors.MissingObjectException: Missing unknown ...

I remember that Christian Halstrick told me that there is still a known issue. Not sure if I'm hitting this exact problem.

Patch-set: 9