Update JGit's dependencies to fix building from source
Due to Bazel rules being renamed in Change-Id I1e75690fe1ee2ab32fffe07c0c3,
but JGit's were not (yet), Bazel failed with errors like:

  ERROR: /path/to/.cache/bazel/_bazel_BUILD_USER/657d7487a554575c9d983baaafc6bd5d/external/jgit/lib/BUILD:10:1: no such package '@commons_compress//jar': The repository could not be resolved and referenced by '@jgit//lib:commons-compress'
  ERROR: /path/to/.cache/bazel/_bazel_BUILD_USER/657d7487a554575c9d983baaafc6bd5d/external/jgit/lib/BUILD:153:1: no such package '@log_api//jar': The repository could not be resolved and referenced by '@jgit//lib:slf4j-api'

This change duplicates the dependencies from Gerrit's WORKSPACE with the
names as known to JGit's Bazel rules to fix the build for those failurs.

Additionally, another error was encountered, because of a new dependency on
'com.jcraft.jzlib' in JGit due to a change earlier this year [1]. This
change adds that dependency.

Moved the 'hamcrest-library' from the WORKSPACE to the JGit rules where
it will be added conditionally only.

[1]: https://git.eclipse.org/r/#/c/114907/

Change-Id: I33be13e7f36ec2bcacbb9eb0983c88c6f3082097