Use Runnable instead of Callable in MailReceiver
Callable fails with this exception:
java.lang.UnsupportedOperationException: Callable not implemented

Other parts in Gerrit use Runnable. Using Runnable here as well fixed
the issue.

Change-Id: I36c96c8408a7295b06217f2d6df18e8253b0e1c8