Update patch set 11
Patch Set 11:

Fails with

ERROR: /Users/patrickmulhall/Documents/workspace/gerrit/gerrit-pgm/BUILD:140:1: Java compilation in rule '//gerrit-pgm:daemon' failed: Worker process sent response with exit code: 1.
gerrit-pgm/src/main/java/com/google/gerrit/pgm/SwitchSecureStore.java:68: error: constructor SitePaths in class SitePaths cannot be applied to given types;
    SitePaths sitePaths = new SitePaths(getSitePath());
                          ^
  required: Path,Config
  found: Path
  reason: actual and formal argument lists differ in lengthINFO: Building compleTarget //:release failed to build

Patch-set: 11
Reviewer: Paladox none <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>