Update patch set 8
Patch Set 8: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 2.4s
/home/deckard/workspace/gerrit/gerrit-extension-api/src/main/java/com/google/gerrit/extensions/api/changes/FileApi.java:17: error: cannot find symbol
import com.google.gerrit.extensions.common.DiffInfo;
                                          ^
  symbol:   class DiffInfo
  location: package com.google.gerrit.extensions.common
/home/deckard/workspace/gerrit/gerrit-extension-api/src/main/java/com/google/gerrit/extensions/api/changes/FileApi.java:27: error: cannot find symbol
  DiffInfo diff() throws RestApiException;
...

Patch-set: 8
Label: Verified=-1