Update patch set 2
Patch Set 2:

This one is failing with:

 java.lang.IllegalStateException: the temporary folder has not yet been created

which I'm not sure is related to the bazel update, and may instead be caused by the earlier issue that we saw with disk space?

Patch-set: 2
Reviewer: Gerrit User 1011123 <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>