assertSubmittedTogether: Remove hasSize assertion
The size is implicitely checked by the following containsExactly
assertion.

Removing the hasSize assertions leads to a better error message in case
of a mismatch. E.g. instead of

java.lang.AssertionError: Not true that
<[com.google.gerrit.extensions.common.ChangeInfo@15e8c040,
com.google.gerrit.extensions.common.ChangeInfo@1f71e024]> has a size of
<3>. It is <2>

we now get:

java.lang.AssertionError: Not true that
<[I05302dc4e6c53362ed6c2dbd2c0f280a98de531f,
Ie35c831b8647aa49bc0a1ab8da48582b0a630d89]> contains exactly
<[I05302dc4e6c53362ed6c2dbd2c0f280a98de531f,
Ie35c831b8647aa49bc0a1ab8da48582b0a630d89,
If4094077c565a3dde5747e905e70a1e8b09e39b3]>. It is missing
<[If4094077c565a3dde5747e905e70a1e8b09e39b3]>

Change-Id: I738f6323eccc450ad52622d2053e43b0c441ff53
Signed-off-by: Edwin Kempin <ekempin@google.com>