Guard repository reference counting internals against `null`
The I3037064388 change introduced the repository reference counting
check in integration tests. It also uses the reference counting
mechanism in Gerrit test server called in tests. It seems that in
certain cases the reference counting clear (that is called after each
TC) is called before the Gerrit test server is stopped. When that
happens any operation on reference counting internal may result in NPE
e.g.:

SEVERE: Error while getting full commit message for change 1 [CONTEXT PLUGIN="gerrit" ]
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "this.decrementCallersStacks" is null
  at com.google.gerrit.testing.GitRepositoryReferenceCountingManager$RepositoryTracking.close(GitRepositoryReferenceCountingManager.java:119)
  at com.google.gerrit.server.query.change.ChangeData.loadCommitData(ChangeData.java:919)
  at com.google.gerrit.server.query.change.ChangeData.commitMessage(ChangeData.java:865)
  at com.google.gerrit.server.events.EventFactory.addCommitMessage(EventFactory.java:355)
  ...

Changes:
* ensure that any ooperation on the reference counting is NPE protected
* when Repository.clear is called during
  `assertThatAllRepositoriesAreClosed` then false negative might be
  reported e.g.:

P.S. Hints to resolve the issue:
     See below the tracking information of when the Repository was created,
     referenced and closed throughout the test. Look carefully at the
     open/close or incrementOpen/close pairs for all the AutoCloseable
     objects (either Repository or one of its wrappers, like
     RepoView or RepoRefCache) that is not managed properly inside a
     try-with-resource enclosure.

See below more details about the Repository objects created / opened and not closed.
------------

  but without any repository being mentioned in the list - ensure that
  any repository is there prior failing the test

This also reduces the flakines of some integration tests e.g.
`StreamEventsIT.draftCommentRefsDeletionShowInStreamEventsUponPublishing`

Release-Notes: skip
Change-Id: If77805574f4becb6ec3986ab906c0efa782198f1