Update patch set 3
Patch Set 3:

Since this commit 'buck build api_install' fails for me with

  Traceback (most recent call last):
    File "/Users/d044411/git/gerrit/tools/maven/mvn.py", line 20, in <module>
      from util import check_output
  ImportError: No module named util
  BUILD FAILED: //tools/maven:install failed with exit code 1:

Patch-set: 3
Reviewer: ekempin <1003935@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0