Update patch set 1
Patch Set 1: I would prefer that you didn't submit this

(2 inline comments)

I could not run the pulse check tests when I used a ssh-key with a pass phrase (I only tried from eclipse). I get an error (see below)

I then created an ssh-key with out pass phrase. When I have only this ssh-key configured in Gerrit the tests run. If I have also the other ssh-key with the pass-phrase the tests fail.

org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of fetch command
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:138)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:173)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:119)
	at com.google.gerrit.test.GerritSshInterface.cloneProject(GerritSshInterface.java:132)
	at com.google.gerrit.test.pulsecheck.CreateProjectPC.testSshProjectCreation(CreateProjectPC.java:47)
Caused by: org.eclipse.jgit.errors.TransportException: ssh://stefanlay@localhost:29418/TestProject18: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:141)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:121)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:248)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:147)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:127)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:113)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1062)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:129)
	... 31 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:461)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 38 more

Patch-set: 1
Label: Code-Review=-1