Update patch set 1
Patch Set 1:

> Patch Set 1: Code-Review+2
> 
> Actually the tests are passing:
> 
>   ERROR: no such target '//Documentation:check_licenses': target 'check_licenses' not declared in package 'Documentation'
> 
> And we could override CI vote.

This was because the CI job was still broken.  I retriggered it after submitting Luca's fix.

Patch-set: 1