Update git submodules
* Update plugins/plugin-manager from branch 'stable-3.0'
  to d486f1edac54c63c46f92c93fa15958f89cfe60f
  - Merge branch 'stable-2.16'
    
    * stable-2.16:
      Set next version to 3.1
    
    Change-Id: I71973fc0b2e2764997f7007beabb2d257ca3f6eb
    
  - Set next version to 3.1
    
    Next forthcoming Gerrit version is 3.1 and thus the plugin-manager
    should return master plugins when the version string starts with
    3.1 *ONLY*.
    
    Bug: Issue 11880
    Change-Id: I49e193c75d2937b2ddb8dd67c1d84bf8b4e52bb9
    
  - Bazel: Remote unused PLUGIN_DEPS variable
    
    Change-Id: I39c1dfd9d5c1a025410bbd9cdf7eec0bd76dcccd
    
  - PluginsRepositoryTest: Skip test when expected env variables are not set
    
    If either the TEST_SRCDIR or TEST_WORKSPACE environment variables is
    not defined, the subsequent call to Paths.get will fail with NPE on
    dereferencing the null value returned by System.getenv. This happens
    when running the test in Eclipse and is expected because when running
    in Eclipse the release.war is not built.
    
    Refactor it so that the values are explicitly checked for nullness
    prior to dereferencing, and the test is skipped if they are.
    
    Also refactor the subsequent check for existence of the release.war to
    an assumption that causes the test to skip, rather than failing.
    
    Bug: Issue 11699
    Change-Id: Ibf9463cc237bd0f613a09a093b5257af92e7efda
    
  - PluginInfo: Make output of failing PluginsRepositoryTest more readable
    
    If you have additional plugins in your working tree the
    corePluginsRepositoryShouldReturnCorePluginsFromReleaseWar test fails
    (as expected) but it's output is rather unreadable [1]. Make it nicer
    [2].
    
    [1]
    1) corePluginsRepositoryShouldReturnCorePluginsFromReleaseWar(com.googlesource.gerrit.plugins.manager.repository.PluginsRepositoryTest)
    value of    : iterable.size()
    expected    : 11
    but was     : 12
    iterable was: [com.googlesource.gerrit.plugins.manager.repository.PluginInfo@3da6950f, com.googlesource.gerrit.plugins.manager.repository.PluginInfo@42684d86, com.googlesource.gerrit.plugins.manager.repository.PluginInfo@45a05350, com.googlesource.gerrit.plugins.manager.repository.PluginInfo@7d6a9d5e, com.googlesource.gerrit.plugins.manager.repository.PluginInfo@74ed7111, com.googlesource.gerrit.plugins.manager.repository.PluginInfo@74691677, com.googlesource.gerrit.plugins.manager.repository.PluginInfo@3314f179, com.googlesource.gerrit.plugins.manager.repository.PluginInfo@1abd1a28, com.googlesource.gerrit.plugins.manager.repository.PluginInfo@5478597, com.googlesource.gerrit.plugins.manager.repository.PluginInfo@39a1e1e6, com.googlesource.gerrit.plugins.manager.repository.PluginInfo@2daa5092, com.googlesource.gerrit.plugins.manager.repository.PluginInfo@5f346355]
    	at com.googlesource.gerrit.plugins.manager.repository.PluginsRepositoryTest.corePluginsRepositoryShouldReturnCorePluginsFromReleaseWar(PluginsRepositoryTest.java:60)
    
    [2]
    1) corePluginsRepositoryShouldReturnCorePluginsFromReleaseWar(com.googlesource.gerrit.plugins.manager.repository.PluginsRepositoryTest)
    unexpected (1): checks
    
    Change-Id: I520c4b918ad1b1a7bccea7e48afe1ea271aff5b5
    ---
    expected      : [codemirror-editor, commit-message-length-validator, delete-project, download-commands, gitiles, hooks, plugin-manager, replication, reviewnotes, singleusergroup, webhooks]
    but was       : [checks, codemirror-editor, commit-message-length-validator, delete-project, download-commands, gitiles, hooks, plugin-manager, replication, reviewnotes, singleusergroup, webhooks]
    	at com.googlesource.gerrit.plugins.manager.repository.PluginsRepositoryTest.corePluginsRepositoryShouldReturnCorePluginsFromReleaseWar(PluginsRepositoryTest.java:61)
    
    Change-Id: Iaac0ea0a421ba97b443ed99ba152323b77d79515
    Signed-off-by: Edwin Kempin <ekempin@google.com>
    
  - Adapt to change in Gerrit core
    
    With change I89c0c68bf Response#value() is now throwing Exception which
    needs to be handled.
    
    Signed-off-by: Edwin Kempin <ekempin@google.com>
    Change-Id: I8742c6ed231dad374192e0bc7002c86aba4cb687
    
  - CorePluginsRepository: Simplify manifest attributes extraction
    
    Change-Id: Iedf986e6bf4448f4cf2eda40e4486a72c6001de8
    
  - CorePluginsRepository: Convert to streams and lambdas
    
    Change-Id: If26858a4c3ba6e814d19252702af0dab95e037b6
    
  - Remove plugin entry .jar suffix when manifest is not found
    
    When the MANIFEST.MF cannot be found in the release.war, assume
    the entry name without the .jar suffix as plugin name.
    
    Change-Id: I0db39f42c33d87f739ce94cf2ce5e4d2372ab0f2
    
  - Add test for CorePluginsRepository
    
    Using dependency on release.war in Bazel junit_tests rule, using data
    attribute, we can depend on release.war content in the tests: [1].
    
    Then we can retrieve the TEST_SRCDIR passed through environment variable
    to the test and retrieve the content of the release.war from within the
    tests. The only disadvantage of this approach, is that the test in this
    form wouldn't work from within IDE. But in this case release.war could
    be built manually and passed in the test by other means.
    
    [1] https://docs.bazel.build/versions/master/build-ref.html#data
    
    Change-Id: I17128017e2ec0287baf34e84b35eed1683f3f422
    
  - Adapt to changed REST interfaces in Gerrit core
    
    Signed-off-by: Edwin Kempin <ekempin@google.com>
    Change-Id: I1d05880cbfd723f517460e43722ad128992acce1
    
  - ListAvailablePlugins: Let RestApiServlet do the conversion to JSON
    
    Also inline the display() method which had only a single caller.
    
    Signed-off-by: Edwin Kempin <ekempin@google.com>
    Change-Id: I63a9275fe48ce68d8cf81ad82d4fe6a37aa96781
    
  - Specify charset to fix DefaultCharset error from error prone
    
    When all error prone warnings are enabled the DefaultCharset
    bug pattern is reported, for example:
    
      plugins/plugin-manager/src/main/java/com/googlesource/gerrit/plugins/manager/FirstWebLoginListener.java:56:
      error: [DefaultCharset] Implicit use of the platform default charset, which
      can result in differing behaviour between JVM executions or incorrect behavior
      if the encoding of the data source doesn't match expectations.
            Files.write(firstLoginFile, new Date().toString().getBytes(), StandardOpenOption.CREATE);
                                                                      ^
        (see https://errorprone.info/bugpattern/DefaultCharset)
    
    Change-Id: I29e19b68c014da9afd491006d936f92219808978