Bazel: Add support for building with JDK 16
Bazel currently doesn't support building with JDK 16: [1]. This change
adds custom toolchain to support building with JDK 16. Due to issue: [2]
Bazel must be patched.

Test Plan:

  $ bazel build --config=java16 java/com/google/gerrit/common:server

Right now it doesn't work:

java.lang.IllegalArgumentException: error: invalid source release: 16
	at jdk.compiler/com.sun.tools.javac.main.Arguments.error(Arguments.java:907)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:383)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:114)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.fallback(ReducedClasspathJavaLibraryBuilder.java:103)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:65)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:110)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:118)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.build(BazelJavaBuilder.java:97)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.parseAndBuild(BazelJavaBuilder.java:77)
	at com.google.devtools.build.lib.worker.WorkRequestHandler.respondToRequest(WorkRequestHandler.java:115)
	at com.google.devtools.build.lib.worker.WorkRequestHandler.lambda$createResponseThread$0(WorkRequestHandler.java:98)
	at java.base/java.lang.Thread.run(Thread.java:831)
Target //java/com/google/gerrit/common:server failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.273s, Critical Path: 0.09s
INFO: 7 processes: 7 internal.
FAILED: Build did NOT complete successfully

[1] https://github.com/bazelbuild/bazel/issues/13270
[2] https://github.com/bazelbuild/bazel/issues/13138

Change-Id: Ib1a689c683cb31041490a7377294026d4b15f0ee