GetDiff: Return empty diff for path '/'
Trying to get the diff for '/' (e.g. "GET
/changes/foo%2Fbar~1234/revisions/8/files/%2F/diff?intraline&whitespace=IGNORE_NONE")
resulted in a "500 Internal Server Error" response caused by an
IllegalArgumentException [1].

Instead of failing with an internal server error return an empty diff,
same as for non-existing paths.

[1]
java.lang.IllegalArgumentException: Empty path not permitted.
  at org.eclipse.jgit.treewalk.filter.PathFilter.create(PathFilter.java:53)
  at org.eclipse.jgit.treewalk.TreeWalk.forPath(TreeWalk.java:188)
  at org.eclipse.jgit.treewalk.TreeWalk.forPath(TreeWalk.java:149)
  at com.google.gerrit.server.patch.PatchScriptBuilder$SidesResolver.find(PatchScriptBuilder.java:425)
  at com.google.gerrit.server.patch.PatchScriptBuilder$SidesResolver.resolve(PatchScriptBuilder.java:357)
  at com.google.gerrit.server.patch.PatchScriptBuilder.resolveSides(PatchScriptBuilder.java:110)
  at com.google.gerrit.server.patch.PatchScriptBuilder.toPatchScript(PatchScriptBuilder.java:91)
  at com.google.gerrit.server.patch.PatchScriptFactory.getPatchScript(PatchScriptFactory.java:239)
  at com.google.gerrit.server.patch.PatchScriptFactory.call(PatchScriptFactory.java:212)
  at com.google.gerrit.server.restapi.change.GetDiff.apply(GetDiff.java:159)
  at com.google.gerrit.server.restapi.change.GetDiff.apply(GetDiff.java:66)
  at com.google.gerrit.extensions.restapi.RestReadView.apply(RestReadView.java:79)
  ...

Release-Notes: GetDiff: Return empty diff for path '/' instead of failing with an internal server error
Change-Id: Icda3135b0d5a81e12698c0b844594d5aa0cbf71f
Signed-off-by: Edwin Kempin <ekempin@google.com>