Update patch set 2
Patch Set 2: Verified-1

Tests no longer compile.

  gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/pgm/ReindexIT.java:39: error:   
  recursivelyDelete(java.io.File) has private access in com.google.gerrit.acceptance.TempFileUtil
      TempFileUtil.recursivelyDelete(sitePath);

Patch-set: 2
Label: Verified=-1