Update patch set 5
Patch Set 5:

The test failure is:

> java.lang.AssertionError: Differences between ReviewDb and NoteDb for change 2:
ChangeMessage present 1 time in A but 0 times in B: NormalizedChangeMessage{changeId=2, author=1000000, writtenOn=2016-02-25 22:51:34.0, message=Uploaded patch set 1., patchset=2,1}

This happens because all four events (two PatchSetEvents, two ChangeMessageEvents) happen fast enough to be grouped together by sameUpdate. Since there can only be one ChangeMessage per update, the second one steps on the first one.

Incidentally, this test method runs second; if I run just this method in Eclipse, it passes sometimes, presumably because warming up causes things to happen a little slower.

We can fix this immediately by setting a time step of 1s, but that's masking the real problem. We need to improve the batching algorithm to only allow one of specific types of event (ChangeMessageEvent, PatchSetEvent, probably more) per batch.

Patch-set: 5
Label: Verified=0