Update patch set 20
Patch Set 20: Verified-1

The cookbook plugin tests fail when running from a clean workspace:

 buck clean && buck test --no-results-cache -f com.googlesource.gerrit.plugins.cookbook.CookbookIT

because the plugin jar file is not found:

 java.nio.file.NoSuchFileException: /gerrit/buck-out/gen/plugins/cookbook-plugin/cookbook-plugin.jar

Full stack trace at [1].

It passes after explicitly building the plugin before running the test:

 buck build plugins/cookbook-plugin

[1] http://paste.openstack.org/show/439300/

Patch-set: 20
Label: Verified=-1