Update patch set 18
Patch Set 18:

> Patch Set 14:
> 
> > Doesn't work for me
> 
> Have you checked the CI log?
> 
>   ERROR: /home/jenkins/.cache/bazel/_bazel_jenkins/3239551e333dc09ba2b5ef07ff4549b6/external/jgit/lib/BUILD:216:1: no such package '@servlet-api-3_1//jar':
>   The repository '@servlet-api-3_1' could not be resolved and referenced by '@jgit//lib:servlet-api'
> 
> That's because JGit build tool chain must be adapted after the rename of @servlet-api-3_1 to @servlet-api in Gerrit core (the same must happen in JGit as well). See this change for more details: [1]. 

note that updating to another version of any 3rd party dependency (or adding a new one) in JGit requires filing a CQ ticket in IPzilla and is subject to approval by the Eclipse legal team, this means this can take a while

Patch-set: 18
Reviewer: Gerrit User 1004034 <1004034@173816e5-2b9a-37c3-8a2e-48639d4f1153>