Fix toolchain definitions for bazel 0.17.1
Without this change, building fails with:

  $ bazel build tools:error_prone_warnings_toolchain
  ERROR: /usr/local/google/home/dborowitz/nobackup/c/gerrit-upstream/gerrit/tools/BUILD:45:1: no such target '@bazel_tools//tools/jdk:platformclasspath.jar': target 'platformclasspath.jar' not declared in package 'tools/jdk' (did you mean 'platformclasspath8.jar'?) defined by /usr/local/google/home/dborowitz/.cache/bazel/_bazel_`

This target was renamed in 0.17.1:

  https://bazel.googlesource.com/bazel/+/3987300d6651cf0e6e91b395696afac6913a7d66
  https://bazel.googlesource.com/bazel/+/35eaec4caae64af9077e7e614edfa62a09c3b0c4/CHANGELOG.md#release-0_17_1-2018_09_14

Change-Id: Ib1ade4041ecf3839e2755c21858882dca9dd30cb