Load change for BatchUpdate post ops on async indexing
On change deletion, we currently observe the following error:

com.google.gerrit.exceptions.StorageException: Unable to load change 372514
	at com.google.gerrit.server.query.change.ChangeData.reloadChange(ChangeData.java:628)
	at com.google.gerrit.server.query.change.ChangeData.change(ChangeData.java:615)
	at com.google.gerrit.server.update.BatchUpdate.lambda$execute$0(BatchUpdate.java:183)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Unknown Source)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)

I believe this is caused by attempting to load the change for post-ops
on change deletion.

Change-Id: I9e768d28c425244fd987b173e1559714fad294e6
Release-Notes: skip