Bazel: Remove bazel version check
Starting from Bazel 2.0.0 the version check is part of the Bazel's shell
script wrapper:

Bazel's Debian package and the binary installer now include an
improved wrapper that understands `<WORKSPACE>/.bazelversion`
files and the `$USE_BAZEL_VERSION` environment variable. This is
similar to what Bazelisk offers
(https://github.com/bazelbuild/bazelisk#how-does-bazelisk-know-\
whch-bazel-version-to-run-and-where-to-get-it-from), except that it
works offline and integrates with apt-get.

Given that all supported Gerrit versions have been upgraded to Bazel
2.0.0, we can remove our own implementation of the version check.

If a different Bazel version is used, bazel shell script would refuse
to run and issue this error message:

ERROR: The project you're trying to build requires Bazel 2.0.0
(specified in /home/<user>/projects/gerrit2/.bazelversion), but it
wasn't found in /home/<user>/.bazel/bin.

As a side effect of this change, we don't need to explicitly load now
bazel_skylib library. But given that rules_closure internally depends
on it, don't pass omit_bazel_skylib in rules_closure_dependencies()
method.

Change-Id: I3469145375aa78ed7f173f7c66acf1ddb7f7b745