Update patch set 13
Patch Set 13: Code-Review-1

> Gerrit-CI Build: https://gerrit-ci.gerritforge.com/job/Gerrit-verifier-change/8249/console

@Edwin, now its' broken because if recent draft notification commit, that I missed to remove during the rebase:

  ERROR: /home/jenkins/workspace/Gerrit-verifier-bazel/gerrit/gerrit-server/BUILD:20:1: Java compilation in rule '//gerrit-server:server' failed: Worker process sent response with exit code: 1..
  gerrit-server/src/main/java/com/google/gerrit/server/mail/send/CreateChangeSender.java:50: error: cannot find symbol
    boolean isDraft = change.getStatus() == Change.Status.DRAFT;

Do you have time to fix that here? ;)

Patch-set: 13
Reviewer: David Ostrovsky <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=-1