Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> I am still seeing this failure during the tests:
> 
>   ERROR org.eclipse.jgit.internal.storage.file.LockFile : Creating lock file 
>   /home/davido/.config/jgit/config.lock failed
>   java.nio.file.FileSystemException: /home/davido/.config/jgit/config.lock: Read-only file system
> 
> To reproduce, cherry-pick this Java 10 change, but without switching entirely to Java 10: [1] and run:
> 
>   $ bazel test //javatests/com/google/gerrit/acceptance/git:GitmodulesIT
> 
> The full stack trace is here: [2].
> 
> [1] https://gerrit-review.googlesource.com/c/gerrit/+/238383
> [2] http://paste.openstack.org/show/787870

looking at [2] it seems you compiled this with Java 11 and tried to run the tests using Java 8.
The test seems to load your real /etc/gitconfig, /home/davido/.config/jgit/config
and ~/.gitconfig. This means the test depends on your local machine's configuration which is typically
something you want to avoid in tests. This can be done using a mocked SystemReader
like StandaloneSiteTest does. I will push another change adding this to AbstractDaemonTest.

For me on Mac compiling and running [1] using Java 11 this test doesn't fail

Patch-set: 3