Bazel: Add no_rbe tag to //tools/bzl:always_pass_test
We are in process to run all tests on RBE platform, to have faster
throughput for test verification: it takes a few seconds to run all
Gerrit tests on RBE platform.

However, when all tests are moved to RBE, then bazel test invocation
is failing with:

  $ bazelisk test --test_tag_filters=-flaky,elastic,no_rbe //...
  WARNING: All specified test targets were excluded by filters
  ERROR: No test targets were found, yet testing was requested

This is because no test rules are tagged with elastic,no_rbe tags
anymore.

We should disable non RBE checker entirely, but to make the test pass
for now we add no_rbe tag to always_pass_test rule. It was added so that
test verification for plugin changes always succeed, also in the case
when plugins don't have any tests.

With this addition the change verification on non RBE platform succeeds:

  Target //tools/bzl:always_pass_test up-to-date:
  bazel-bin/tools/bzl/always_pass_test
  INFO: Elapsed time: 4.361s, Critical Path: 1.26s
  INFO: 5 processes: 3 internal, 2 processwrapper-sandbox.
  INFO: Build completed successfully, 5 total actions
  //tools/bzl:always_pass_test                            PASSED in 0.0s

Change-Id: I5bf5170acdc6ccd42e583b733498cfb4fd8e724c