Update patch set 1
Patch Set 1: Verified-1 Code-Review-1

> > can you give an example of something that should work with XZ
 > > today?
 
Check this commit: 1e9338854c6fc40f118fd51fe09eb06b6c16f315 where git-upload-archive command support was introduced. A test was also added, but that only uses zip archive format over SSH.

Enable download archive:

  [download]
    archive = tar
    archive = tbz2
    archive = tgz
    archive = txz
    archive = zip

start gerrit, configure SSH key and execute:

  $ git archive -f tar.xz --prefix=test-project-1.0/ --remote=ssh://davido@localhost:29418/test_project refs/changes/58/3258/1 > test_project-1.0.tar.xyz

Now, verify, that the content of test_project-1.0.tar.xyz is sane:

  $ tar -Jtf test_project-1.0.tar.xyz
  test-project-1.0/
  test-project-1.0/README.md
  test-project-1.0/Test.java
  [...]

Apply this CL. git-upload-archive for tar.xz format is now broken:

  $ git archive -f tar.xz --prefix=test-project-1.0/ --remote=ssh://davido@localhost:29418/test_project refs/changes/58/3258/1 > test_project-1.0.tar.xyz
  fatal: internal server error

With this server log:

  [2018-01-10 08:12:24,037] [SSH git-upload-archive '/test_project' (davido)] ERROR 
  com.google.gerrit.sshd.BaseCommand : Internal server error (user davido account 1000000) during git-upload-archive '/test_project'
  java.lang.NoClassDefFoundError: org/tukaani/xz/FilterOptions
	at org.eclipse.jgit.archive.TxzFormat.createArchiveOutputStream(TxzFormat.java:81)
	at org.eclipse.jgit.archive.TxzFormat.createArchiveOutputStream(TxzFormat.java:62)
	at org.eclipse.jgit.api.ArchiveCommand.writeArchive(ArchiveCommand.java:397)
	at org.eclipse.jgit.api.ArchiveCommand.call(ArchiveCommand.java:452)
	at com.google.gerrit.sshd.commands.UploadArchive.runImpl(UploadArchive.java:201)
	at com.google.gerrit.sshd.AbstractGitCommand.service(AbstractGitCommand.java:97)
	at com.google.gerrit.sshd.AbstractGitCommand.access$0(AbstractGitCommand.java:86)
	at com.google.gerrit.sshd.AbstractGitCommand$1.run(AbstractGitCommand.java:63)
	at com.google.gerrit.sshd.BaseCommand$TaskThunk.run(BaseCommand.java:419)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:435)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.tukaani.xz.FilterOptions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

Patch-set: 1
Reviewer: David Ostrovsky <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1
Label: Code-Review=-1