GetDiff: Reject edit as base as ‘400 Bad Request’
Trying to use a change edit as base for a diff computation failed with
an Internal Server Error, caused by [1]. The diff computation against
change edits is just not supported, reject those request as '400 Bad
Request' so that they do not count against our error budget.

[1]
java.lang.IllegalArgumentException: edit not supported for left side
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
        at com.google.gerrit.server.patch.PatchScriptFactory.getAId(PatchScriptFactory.java:274)
        at com.google.gerrit.server.patch.PatchScriptFactory.call(PatchScriptFactory.java:208)
        at com.google.gerrit.server.restapi.change.GetDiff.apply(GetDiff.java:143)
        at com.google.gerrit.server.restapi.change.GetDiff.apply(GetDiff.java:64)
        at com.google.gerrit.httpd.restapi.RestApiServlet.lambda$invokeRestReadViewWithRetry$3(RestApiServlet.java:742)
        at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
        at com.github.rholder.retry.Retryer.call(Retryer.java:160)
        at com.google.gerrit.server.update.RetryHelper.executeWithTimeoutCount(RetryHelper.java:560)
        at com.google.gerrit.server.update.RetryHelper.execute(RetryHelper.java:503)
        at com.google.gerrit.server.update.RetryableAction.call(RetryableAction.java:171)
        at com.google.gerrit.httpd.restapi.RestApiServlet.invokeRestEndpointWithRetry(RestApiServlet.java:833)
        at com.google.gerrit.httpd.restapi.RestApiServlet.invokeRestReadViewWithRetry(RestApiServlet.java:737)
        at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:507)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        ...

Change-Id: If637c017d51b4397e8ad19ae759a4682d57e206a
Signed-off-by: Edwin Kempin <ekempin@google.com>