Update patch set 3
Patch Set 3:

Tests seem to fail with this series:

  FAILURE listBranches: missing branch: refs/heads/dev
  java.lang.AssertionError: missing branch: refs/heads/dev
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:621)
        at com.google.gerrit.acceptance.rest.project.BranchAssert.assertBranches(BranchAssert.java:40)
        at com.google.gerrit.acceptance.rest.project.ListBranchesIT.listBranches(ListBranchesIT.java:155)

Patch-set: 3