WiP: Add support for secondary index with Elasticsearch
Missing features and known issues:

- Ordering (asc, desc) of results is not implemented

- Search fails when query includes the "owner:" operator

- Site fails to load when debugging in Eclipse, and acceptance tests
  fail with the error:

  java.lang.NoClassDefFoundError: Could not initialize class
  org.apache.lucene.codecs.Codec

Change-Id: I5e4fc08ce34d33c090c9e0bf320de1b17309f774