Do not fail if comment context is missing
It's better to return the result without the missing comment context
rather than failing completely.

This isn't a proper fix, but a band-aid for a NPE [1] that we don't know
yet how to fix.

We are adding some more logging so that we can better see where the
comment context starts being missing. After the investigation is done,
the new logging may be removed again.

[1]
java.lang.NullPointerException: null value in entry: CommentContextKey{project=myproject, changeId=286427113, id=c70baa47_54c6afa7, path=/PATCHSET_LEVEL, patchset=3, contextPadding=3}=null
  at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:35)
  at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:188)
  at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:298)
  at com.google.gerrit.server.comment.CommentContextCacheImpl.getAll(CommentContextCacheImpl.java:122)
  at com.google.gerrit.server.restapi.change.CommentJson$BaseCommentFormatter.addCommentContext(CommentJson.java:172)
  at com.google.gerrit.server.restapi.change.CommentJson$BaseCommentFormatter.format(CommentJson.java:143)
  at com.google.gerrit.server.restapi.change.CommentJson$HumanCommentFormatter.format(CommentJson.java:241)
  at com.google.gerrit.server.restapi.change.ListChangeComments.getAsMap(ListChangeComments.java:105)
  at com.google.gerrit.server.restapi.change.ListChangeComments.apply(ListChangeComments.java:83)
  at com.google.gerrit.server.restapi.change.ListChangeComments.apply(ListChangeComments.java:38)
  ...

Signed-off-by: Edwin Kempin <ekempin@google.com>
Change-Id: If6d005116329e960504a7618918321254725073e