Update patch set 2
Patch Set 2:

(1 comment)

> (1 comment)
 > 
 > > (1 comment)
 > >
 > > Eh, the build failure shows us why we probably don't want to do
 > > this...
 > 
 > Yes, but I think, at least concerning the
 > 
 > PluginGuiceEnvironment.java:54: error: package org.apache.sshd.server
 > does not exist
 > import org.apache.sshd.server.Command;
 > 
 > we could (probably) add the dependence to Apache SSHD, without
 > introducing circular dependency on gerrit-sshd <- gerrit-server <-
 > gerrit-sshd.

We don't want to depend on gerrit-sshd. SSH can be completely disabled for a server and then the SSH module is not even loaded.

Patch-set: 2