Update patch set 7
Patch Set 7:

Also, any hints on the best way to format .java files?

java -jar ~/google-java-format-1.7.jar NegCanBlockLabelFunctionTest.java 
java.lang.NoClassDefFoundError: com/google/common/base/Splitter
...

So my CLASSPATH (undefined) is not helping. The doc doesn't tell me what to set CLASSPATH to in any regard.

I need to format the file. Thanks.

Patch-set: 7
Reviewer: Gerrit User 1025883 <1025883@173816e5-2b9a-37c3-8a2e-48639d4f1153>