Update patch set 4
Patch Set 4:

I'm not able to generate the Eclipse project on the head of master; it's failing with:

 TypeError: Object #<Object> has no method 'tmpDir'

I checked out this series of changes to see if that makes it any better, but now I get the same errors with `buck build gerrit`.

I'm sure this is caused by something wrong with my environment.  Now I'm on Ubuntu 12.04 behind a corporate firewall.  When I was using my macbook, It Just Worked.

Full log here: http://paste.openstack.org/show/479203/

Patch-set: 4