Update patch set 1
Patch Set 1:

This causes ES tests on master to fail consistently for me:

 1) reindexIfStale(com.google.gerrit.elasticsearch.ElasticQueryChangesTest)
com.google.gerrit.server.account.AccountException: Cannot assign external ID "gerrit:user" to
account 1000001; external ID already in use.
  at com.google.gerrit.server.account.AccountManager.create(AccountManager.java:270)
  at com.google.gerrit.server.account.AccountManager.authenticate(AccountManager.java:133)
  at com.google.gerrit.server.query.change.AbstractQueryChangesTest.createAccount(AbstractQuer
yChangesTest.java:688)
  at com.google.gerrit.server.query.change.AbstractQueryChangesTest.reindexIfStale(AbstractQue
ryChangesTest.java:1627)


I imagine we can fix the test setup to make this work.

Patch-set: 1