Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [gerrit/try/Verify gerrit CL](https://cr-buildbucket.appspot.com/build/8787298878710702737) has failed with summary:

---
yarn run v1.22.19
$ tsc --project ./polygerrit-ui/app/tsconfig.json
polygerrit-ui/app/embed/diff/gr-diff-builder/gr-diff-builder-element_test.ts(9,3): error TS6133: 'createDiff' is declared but its value is never read.
polygerrit-ui/app/embed/diff/gr-diff-builder/gr-diff-builder-element_test.ts(13,9): error TS6133: 'queryAndAssert' is declared but its value is never read.
polygerrit-ui/app/embed/diff/gr-diff-builder/gr-diff-builder-element_test.ts(19,3): error TS6133: 'DiffInfo' is declared but its value is never read.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Patch-set: 2
Tag: autogenerated:cq:new-patchset-run:1678175766