Update patch set 2
Patch Set 2:

Actually i lied: it failed in one test:

  FAIL  51,4s  9 Passed   1 Failed   com.google.gerrit.acceptance.git.SubmitOnPushIT
  FAILURE submitOnPushToNonExistingBranch_Error: verify: false
  com.jcraft.jsch.JSchException: verify: false

But it was normal those days on stable-2.8 as we had sporadic test failures due to Jsch issues.

Patch-set: 2