Update patch set 1
Patch Set 1: Verified-1

`buck test` is failing:

 [2014-12-15 10:50:44.513][error][command:48345b4c-5baa-45b4-a78f-a9b7767c6c83][tid:24][com.google.common.eventbus.EventBus.buck-build-events] Could not dispatch event: 
 com.facebook.buck.event.listener.ChromeTraceBuildListener@202863c to public void com.facebook.buck.event.listener.ChromeTraceBuildListener.ruleStarted(com.facebook.buck.rules.BuildRuleEvent$Started)
 java.util.concurrent.ExecutionException: java.io.FileNotFoundException: /home/david/gerrit/src/com/facebook/buck/python/__test_main__.py (No such file or directory)
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2320)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.facebook.buck.util.DefaultFileHashCache.get(DefaultFileHashCache.java:84)
	at com.facebook.buck.rules.RuleKey$Builder.setInputVal(RuleKey.java:301)
	at com.facebook.buck.rules.RuleKey$Builder.setInput(RuleKey.java:295)
	at com.facebook.buck.python.PythonBinary.appendDetailsToRuleKey(PythonBinary.java:112)
	at com.facebook.buck.rules.AbstractBuildRule.appendToRuleKey(AbstractBuildRule.java:149)
	at com.facebook.buck.rules.AbstractBuildRule.getRuleKeyPair(AbstractBuildRule.java:178)
	at com.facebook.buck.rules.AbstractBuildRule.getRuleKey(AbstractBuildRule.java:159)
	at com.facebook.buck.rules.BuildRuleEvent.getRuleKeySafe(BuildRuleEvent.java:64)
	at com.facebook.buck.event.listener.ChromeTraceBuildListener.ruleStarted(ChromeTraceBuildListener.java:213)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.AsyncEventBus.access$001(AsyncEventBus.java:34)
	at com.google.common.eventbus.AsyncEventBus$1.run(AsyncEventBus.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
 Caused by: java.io.FileNotFoundException: /home/david/gerrit/src/com/facebook/buck/python/__test_main__.py (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)

Patch-set: 1
Label: Verified=-1