Update patch set 17
Patch Set 17:

@David Pursehouse it will now fail at

com.google.gerrit.acceptance.rest.project.DeleteTagsIT
FAILURE com.google.gerrit.acceptance.rest.project.DeleteTagsIT deleteTagsNotFound: Not true that <[refs/tags/test-1, refs/tags/test-2, refs/tags/test-3]> contains exactly <[HEAD, refs/meta/config, refs/tags/master, refs/tags/test-1, refs/tags/test-2, refs/tags/test-3]>. It is missing <[HEAD, refs/meta/config, refs/tags/master]>
java.lang.AssertionError: Not true that <[refs/tags/test-1, refs/tags/test-2, refs/tags/test-3]> contains exactly <[HEAD, refs/meta/config, refs/tags/master, refs/tags/test-1, refs/tags/test-2, refs/tags/test-3]>. It is missing <[HEAD, refs/meta/config, refs/tags/master]>
	at 

Not sure how to fix that one? Do I remove assertTags?

Patch-set: 17