Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3:
> > 
> > > Patch Set 3:
> > > 
> > > > Patch Set 3:
> > > > 
> > > > I successfully ran the build on my laptop:
> > > > 
> > > > - install ant 1.9.13
> > > > - use java 1.7_80
> > > > - install JCE unlimited strength jurisdiction policy
> > > > - recompile buck with java 7
> > > > - buck build :release succeeds
> > > > - buck build :api succeeds
> > > > - buck test --all: most tests succeed except GarbageCollectionIT fails (4 errors) all with the error
> > > > 
> > > > [2019-01-08 15:06:06,319] ERROR com.google.gerrit.pgm.Daemon : Unable to start daemon
> > > > java.lang.IllegalStateException: No SSHD host key
> > > > 	at com.google.gerrit.sshd.SshDaemon.checkConfig(SshDaemon.java:315)
> > > [...]
> > > > 
> > > > not yet sure if that's a problem with the code or with my environment
> > > 
> > > I ran all tests on GerritForge docker image and they were all passing, see m previous comment and the link where I pasted the reault of the tests.
> > > 
> > > However, that is not enough, as David Pursehouse pointed out. The problem fixed in: [1] is not covered in any existing integration test:
> > > 
> > > "
> > > In protocol v0 bidirectional transports, the AdvertiseRefsHook is called at ref advertisement time and all is well. But in protocol v0 HTTP, we're not seeing the AdvertiseRefsHook called anywhere for the /git-upload-pack request, meaning that wants aren't validated and I can fetch anything that is pointed to by any ref (using fetch-by-sha1), as long as I can guess the object name.
> > > "
> > > 
> > > Someone would have to test manually, that without this change, we have this vulnerability and this change did actually fix it.
> > > 
> > > [1] https://bugs.chromium.org/p/gerrit/issues/detail?id=10262
> > 
> > I am doing this right now, testing that:
> > 
> > - Gerrit works
> 
> This is good, it works.
> 
> > - The problem is fixed
> 
> Not sure it is, see below what I've done:
> 
> - Create a repo with two branches (master + mybranch)
> - One SHA1 is in master but not in mybranch
> - A user can only see mybranch but not master
> 
> What I see is that the user with a 'ls-remote' doesn't see mybranch.
> However, if he can guess the SHA1 of master, he can fetch master and see master commits as well.
> 
> See below:
> 
> git ls-remote http://user@localhost:8080/test-repo                                                                                                                                         86c3a008bb981a825947449ff7d7ab2a850a1027	refs/heads/mybranch
> 
> git fetch http://user@localhost:8080/test-repo b82b7be48f031d0dc5342b7c57c65eb11c8102ca
> From http://localhost:8080/test-repo
>  * branch            b82b7be48f031d0dc5342b7c57c65eb11c8102ca -> FETCH_HEAD
> 
> git log -1 FETCH_HEAD
> commit b82b7be48f031d0dc5342b7c57c65eb11c8102ca (HEAD, origin/master, origin/HEAD, master)
> Author: Luca Milanesio <luca.milanesio@gmail.com>
> Date:   Tue Jan 8 15:31:20 2019 +0000
> 
> Am I missing something?
> 
> Gerrit says at startup "Gerrit Code Review 2.9.4-3-gbb3011f0b0"

I believe I misread the exploit: so basically I need to make *only* a git upload pack with the ref-name 'refs/heads/master' and it should be allowed on 2.9.4 (exploitable) but not on 2.9.4-3-gbb3011f0b0 (fixed). Let me try again.

Patch-set: 3
Reviewer: Gerrit User 1006192 <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>