Revert "Report success of preview fix load"
This reverts commit b053505459794dbe9e1c8c9d31aac70e02ddd9d1.

Reason for revert: Throws typescript error TS4111 on typescript used in google

Change-Id: I93fc130365d6cc6f044cb4fcaed2a44b1db4277f