Update patch set 11
Patch Set 11:

This is now causing errors like

[2017-06-18 16:55:18,757] [HTTP-69] WARN  com.google.gerrit.server.change.Files$ListFiles : Cannot copy patch review flags
com.google.gerrit.server.patch.PatchListNotAvailableException: patch set 0 of change 2 not found

could that be fixed please so that it dosent do that?

Patch-set: 11
CC: Paladox none <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>