Update patch set 2
Patch Set 2:

when compiling it fails because of:

bazel-out/k8-fastbuild/bin/polygerrit-ui/app/gr-app.js:13598: ERROR - Namespace not provided by any srcs or direct deps of //polygerrit-ui/app:polygerrit_ui_closure_lib.
goog.require('security.polymer_resin.hintUsesDeprecatedRegisterElement');
             ^
  ProTip: "CR_NOT_PROVIDED" or "strictDependencies" can be added to the `suppress` attribute of:
  //polygerrit-ui/app:polygerrit_ui_closure_lib

bazel-out/k8-fastbuild/bin/polygerrit-ui/app/gr-app.js:13599: ERROR - Namespace not provided by any srcs or direct deps of //polygerrit-ui/app:polygerrit_ui_closure_lib.
goog.require('security.polymer_resin.sanitizer');
             ^
  ProTip: "CR_NOT_PROVIDED" or "strictDependencies" can be added to the `suppress` attribute of:
  //polygerrit-ui/app:polygerrit_ui_closure_lib

Which i presume is a google internal thing.

Patch-set: 2
Reviewer: Gerrit User 1013302 <1013302@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Work-in-progress: false