Update patch set 2
Patch Set 2:

PS1 had the logic inverted. PS2 still has a test failure:

 1) watched(com.google.gerrit.server.query.change.LuceneQueryChangesTest)                                                                                                                                                             [183/4809]
 com.google.gerrit.extensions.restapi.BadRequestException: Error in operator is:watched
 ...
 Caused by: java.lang.IllegalArgumentException: negating any() is unsafe because it post-filters all results
   at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
   at com.google.gerrit.index.query.Predicate.not(Predicate.java:86)
   at com.google.gerrit.server.query.change.IsWatchedByPredicate.none(IsWatchedByPredicate.java:103)
   at com.google.gerrit.p

That's good: this is a real issue in the code. It does mean that it'll require a deeper fix.

Patch-set: 2
Reviewer: Gerrit User 1010008 <1010008@173816e5-2b9a-37c3-8a2e-48639d4f1153>