Update patch set 12
Patch Set 12:

Wrong header is being returned, see below which compares 2.15 vs 2.16

xxx@xxx:~$ curl -I https://gerrit.wikimedia.org/r/p/mediawiki/core/info/refs?service=git-upload-pack
HTTP/1.1 200 OK
Date: Fri, 25 Jan 2019 20:58:08 GMT
Server: Apache
Strict-Transport-Security: max-age=106384710; includeSubDomains; preload
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Pragma: no-cache
Cache-Control: no-cache, max-age=0, must-revalidate
Content-Type: application/x-git-upload-pack-advertisement
Transfer-Encoding: chunked
Set-Cookie: JSESSIONID=v0jlwkc5auzp2ulgp2jzu8ay;Path=/r;Secure
Backend-Timing: D=3664 t=1548449888525631

xxx@xxx:~$ curl -I https://gerrit-test.wmflabs.org/gerrit/p/testing/test/info/refs?service=git-upload-pack
HTTP/2 200 
server: nginx/1.13.6
date: Fri, 25 Jan 2019 20:58:38 GMT
content-type: application/x-git-upload-pack-advertisement
content-length: 8246
expires: Thu, 01 Jan 1970 00:00:00 GMT
pragma: no-cache
cache-control: no-cache, max-age=0, must-revalidate
set-cookie: XSRF_TOKEN=;Path=/;Expires=Thu, 01-Jan-1970 00:00:00 GMT;Max-Age=0
set-cookie: JSESSIONID=node0dbl6ny91j5h612g8peyc9bcfx3.node0;Path=/gerrit;Secure
backend-timing: D=8335 t=1548449918117943
x-clacks-overhead: GNU Terry Pratchett


which causes zuul to fail with:

2019-01-25 20:55:52,255 ERROR zuul.source.Gerrit: Exception looking for ref refs/heads/master
Traceback (most recent call last):
  File "/usr/share/python/zuul/local/lib/python2.7/site-packages/zuul/source/gerrit.py", line 49, in getRefSha
    refs = self.connection.getInfoRefs(project)
  File "/usr/share/python/zuul/local/lib/python2.7/site-packages/zuul/connection/gerrit.py", line 394, in getInfoRefs
    data = urllib.request.urlopen(url).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 406: Not Acceptable

Patch-set: 12
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>