Fix build on MacOS 13.3
After upgrading MacOS to 13.3.1 the gerrit build fails with the
following errors apparently caused by zlib:

$ bazelisk build release
...
external/remote_java_tools/java_tools/zlib/gzwrite.c:89:20: error: call
to undeclared function 'write'; ISO C99 and later do not support
implicit function declarations [-Wimplicit-function-declaration]
            writ = write(state->fd, strm->next_in, put);
                   ^
external/remote_java_tools/java_tools/zlib/gzwrite.c:89:20: note: did
you mean 'fwrite'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdio.h:165:9:
note: 'fwrite' declared here
size_t   fwrite(const void * __restrict __ptr, size_t __size, size_t __nitems, FILE * __restrict __stream) __DARWIN_ALIAS(fwrite);
         ^
external/remote_java_tools/java_tools/zlib/gzwrite.c:110:24: error: call
to undeclared function 'write'; ISO C99 and later do not support
implicit function declarations [-Wimplicit-function-declaration]
                writ = write(state->fd, state->x.next, put);
                       ^
external/remote_java_tools/java_tools/zlib/gzwrite.c:661:9: error: call
to undeclared function 'close'; ISO C99 and later do not support
implicit function declarations [-Wimplicit-function-declaration]
    if (close(state->fd) == -1)
        ^

To fix this
- revert "Work around build errors on MacOS 13.3 and XCode 14.3"
- and follow the advise in [1]:
  - update bazel to 6.1.2
  - update remote_java_tools to 12.1
    https://github.com/bazelbuild/java_tools/releases/tag/java_v12.1

Set new errorprone bug patterns to WARN until we fixed occurrences.
Also demote the severity for these bug patterns to warning:

o LiteProtoToString
o MutableConstantField
o ProvidesMethodOutsideOfModule

Also suppress warnings for the following bug patterns: DoNotCall,
MathAbsoluteNegative and Unused using @SuppressWarnings annotation.

Also note that PreferredInterfaceType bug pattern is reported, but can
only be demoted to warning severity using the MutableConstantField bug
pattern, see also [2].

[1] https://github.com/bazelbuild/bazel/issues/17956
[2] https://github.com/google/error-prone/issues/3872

Release-Notes: Update bazel to 6.2.1 and remote_java_tools to 12.1 to fix build on MacOS 13.3
Change-Id: Ib9d8d8be44a58c470f712d297c39518498c43dc2