NoteDBMigrator: allow to set an external executor
By default the WorkQueue executor used to run the online noteDb
migration is created with metrics-capability, so that the scheduling the
execution and the termination of submitted tasks could be monitored.

Upon termination of the ThreadPool executor, however, the metrics are
not removed from the metrics registry.

This is not just polluting the metrics registry with unnecessary
metrics, but it is also preventing from creating another queue with the
same name later within the same Gerrit runtime, causing the following
exception:

java.lang.IllegalArgumentException: A metric named
queue/<queue_name>/max_pool_size already exists

The root cause of this problem could be fixed by cherry-picking
I06d48535702a and explicitly de-register the metrics upon executor
termination, as attempted in Iaca9881cd46.

Unfortunately however, this cannot be done on stable-2.16, because it
would be against the policies of stable and EOL branches.

Allow to explicitly set an executor, so that it can survive the
NoteDBMigrator object lifespan and be re-used to perform the online
migration multiple times without causing any metrics collision.

When setting the executor explicitly, the argument `threads`makes no
sense anymore, since it won't be used to create an thread-pool.  When
both are used, a `MigrationException` is thrown.

Note that this is not a problem for the `migrate-to-notedb` program,
which is using `DisabledMetriMaker`, hence not emitting metrics at all.

Release-Notes: skip
Forward-Compatible: checked
Change-Id: Idc6ef55ca8a15551c81c59f70c131ddbb40b7101