Update patch set 10
Patch Set 10: Code-Review-1

This is no longer working for me:

$ sh tools/check-format.sh
.....................
____Loading package: tools/bzl
ERROR: no such target '//tools/bzl:google-java-format': target 'google-java-format' not declared in package 'tools/bzl' defined by /usr/local/google/home/ekempin/git/gerrit/tools/bzl/BUILD.
____Elapsed time: 2.438s

bazel failed

Patch-set: 10
Reviewer: Edwin Kempin <1003935@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=-1