GetRelated: Reload change if it is stale
If the index doesn't contain the current patch set of the change for
which the related changes should be returned, GetRelated fails with an
Internal Server Error:

  java.lang.IllegalArgumentException: [PatchSet 123,4] not found in [...]
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:388)
    at com.google.gerrit.server.change.RelatedChangesSorter.sort(RelatedChangesSorter.java:70)
    at com.google.gerrit.server.change.GetRelated.getRelated(GetRelated.java:95)
    at com.google.gerrit.server.change.GetRelated.apply(GetRelated.java:68)
    at com.google.gerrit.server.change.GetRelated.apply(GetRelated.java:46)
    at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:331)
    ...

Be more tolerant and automatically reload the change from DB/NoteDb in
this case.

Change-Id: I415342491e7345893bd0ef25733bb0fe3bb8d986
Signed-off-by: Edwin Kempin <ekempin@google.com>