PolyGerrit: Add missing URLEncodingBehavior behavour to gr-change-list-view
Noticed when testing I352f741b170df477ccd267dc4d6bc951f0b8affa

I was getting this

TypeError: this.encodeURL is not a function.
(In 'this.encodeURL(query,false)', 'this.encodeURL' is undefined) 

When pressing enter.

Change-Id: I3459b4ccfc2217a80d4615bee25943245f236cf4