Update patch set 2
Patch Set 2:

This actually broke 2 tests :(

FAIL    129.6s 23 Passed   0 Skipped   2 Failed   com.google.gerrit.acceptance.edit.ChangeEditIT
FAILURE deleteEditRest: expected:<204> but was:<404>
java.lang.AssertionError: expected:<204> but was:<404>

FAILURE deletingNonExistingEditRest: expected:<400> but was:<404>
java.lang.AssertionError: expected:<400> but was:<404>

Can anyone have a look?

Patch-set: 2