Update git submodules
* Update plugins/delete-project from branch 'master'
  to e345e6e79900a72981e4ad19d37c7fbdcae4818b
  - Fix ProtectedMembersInFinalClass error flagged by error prone
    
    Running recent error prone version complaining on that code:
    
    DeleteCommand.java:53: error: [ProtectedMembersInFinalClass] Make members
    of final classes package-private: <init>
      protected DeleteCommand(DeleteProject deleteProject, DeletePreconditions preConditions) {
                ^
        (see https://errorprone.info/bugpattern/ProtectedMembersInFinalClass)
    
    Bug: Issue 12677
    Change-Id: I3ef90ac3106240403dc88178262edf2447f30cb8
    
  - Fix JavaTimeDefaultTimeZone error flagged by error prone
    
    Running recent error prone version complaining on that code:
    
    TimeMachine.java:54: error: [JavaTimeDefaultTimeZone] Clock.systemDefaultZone()
    is not allowed because it silently uses the system default time-zone.
    You must pass an explicit time-zone (e.g., ZoneId.of("America/Los_Angeles")
     to this method.
        clock = Clock.systemDefaultZone();
                                       ^
        (see https://errorprone.info/bugpattern/JavaTimeDefaultTimeZone)
    
    Bug: Issue 12677
    Change-Id: I10e34bf90d1903aeb40810509b87b0519971ade1