Update patch set 3
Patch Set 3: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 4.1s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/change/Submit.java:241: error: cannot find symbol
        visibility &= c.canSubmit(); // todo: there is no Change.canSubmit() method. Find another way.
                       ^
  symbol:   method canSubmit()
  location: variable c of type com.google.gerrit.reviewdb.client.Change
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
...

Patch-set: 3
Label: Verified=-1