Update patch set 2
Patch Set 2:

This fixes the quota error but now it's throwing

404 GET /config/server/info
safari 10.0.3            ✖ elements/change/gr-reply-dialog/gr-reply-dialog_test.html » gr-reply-dialog tests » only send labels that have changed

  QuotaExceededError (DOM Exception 22): The quota has been exceeded. (http://localhost:2000/components/tmp.Xlcates9/elements/shared/gr-storage/gr-storage.js:97)

safari 10.0.3            Tests failed: Error thrown outside of test function: Attempted to wrap getConfig which is already wrapped
  checkWrappedMethod at /components/sinonjs/sinon.js:1326
          wrapMethod at /components/sinonjs/sinon.js:1366
           <unknown> at gr-reply-dialog_test.html:54
          wrapMethod at /components/sinonjs/sinon.js:1385
           <unknown> at gr-reply-dialog_test.html:54
404 DELETE /changes/42/reviewers/7
Test run ended in failure: Error thrown outside of test function: document.getElementById(...).restore is not a function
, Error thrown outside of test function: Attempted to wrap getConfig which is already wrapped
  checkWrappedMethod at /components/sinonjs/sinon.js:1326
          wrapMethod at /components/sinonjs/sinon.js:1366
           <unknown> at gr-reply-dialog_test.html:54
          wrapMethod at /components/sinonjs/sinon.js:1385
           <unknown> at gr-reply-dialog_test.html:54

chrome 57 (63/0/0 error)
safari 10.0.3 (521/0/1 error)

Error: Error thrown outside of test function: document.getElementById(...).restore is not a function
, Error thrown outside of test function: Attempted to wrap getConfig which is already wrapped
  checkWrappedMethod at /components/sinonjs/sinon.js:1326
          wrapMethod at /components/sinonjs/sinon.js:1366
           <unknown> at gr-reply-dialog_test.html:54
          wrapMethod at /components/sinonjs/sinon.js:1385
           <unknown> at gr-reply-dialog_test.html:54

on mac os 10.12.3 and tested on a clean git clone of gerrit no patches applied.

Patch-set: 2
CC: Paladox none <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>