RestApiException: Make default constructor protected
Nobody should throw a RestApiException without message. The only legit
case to use the default constructor of RestApiException is from the
default contructor of ResourceNotFoundException, which may be used to
signal that a REST endpoint doesn't exist (in which case no resource ID
is provided to it)

Signed-off-by: Edwin Kempin <ekempin@google.com>
Change-Id: If7b0640ba0933451130150d40c6c511db90899a5