Update patch set 3
Patch Set 3:

> Doesn't compile:
 > 
 > gerrit-server/src/test/java/com/google/gerrit/server/project/RefControlTest.java:368:
 > error: cannot find symbol
 > block(parent, SUBMIT, ANONYMOUS_USERS, "refs/heads/*");
 > ^
 > symbol:   variable parent
 > location: class com.google.gerrit.server.project.RefControlTest

Because it was cherry-picked from master where another change on the RefControlTest introduced the `parent` variable.

It compiles now I've cherry-picked the missing change as a dependency of this one.

Patch-set: 3