Fix ConfigUtil's javadoc to use @param instead of invalid @params
With commit 85279183ecdef19cb82e34138ed2b24307f888d0, ConfigUtil's
javadoc started using the invalid @params (trailing 's') javadoc
keywords. Due to Java 8's stricter handling of javadoc, using @params
made building the plugin-api-javadoc.jar artifact fail with (edited
for readibility) [1]:

  gerrit-server/[...]/ConfigUtil.java:272: error: unknown tag: params
   * @params defaults instance of class with default values
     ^

Hence, we fix the keywords to the valid @params to allow building on
Java 8 again.

[1] See
http://builds.quelltextlich.at/gerrit/nightly/master-java_8/2015-09-13/plugin-api-javadoc.jar.build.stderr.txt
http://builds.quelltextlich.at/gerrit/nightly/master-java_8/2015-09-13/index.html#plugin-api-javadoc.jar

Change-Id: Ic9d3d2e906f53b125dd5febb4bcb6540b15c5b77