Update patch set 24
Patch Set 24:

I'm getting a test failure with this change now. Not sure how it is related. Anyone else seeing this?

FAILURE com.google.gerrit.acceptance.git.VisibleRefFilterIT subsetOfRefsVisibleWithAccessDatabase: Not true that <[refs/changes/16/16/1, refs/heads/branch, refs/users/00/1000000/edit-16/1, refs/tags/branch-tag, refs/changes/17/17/1, refs/tags/master-tag]> contains exactly <[refs/changes/16/16/1, refs/changes/17/17/1, refs/heads/branch, refs/tags/branch-tag, refs/tags/master-tag, refs/users/00/1000000/edit-16/1, refs/users/01/1000001/edit-16/1]>. It is missing <[refs/users/01/1000001/edit-16/1]>
java.lang.AssertionError: Not true that <[refs/changes/16/16/1, refs/heads/branch, refs/users/00/1000000/edit-16/1, refs/tags/branch-tag, refs/changes/17/17/1, refs/tags/master-tag]> contains exactly <[refs/changes/16/16/1, refs/changes/17/17/1, refs/heads/branch, refs/tags/branch-tag, refs/tags/master-tag, refs/users/00/1000000/edit-16/1, refs/users/01/1000001/edit-16/1]>. It is missing <[refs/users/01/1000001/edit-16/1]>
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:24)
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:20)
	at com.google.common.truth.Subject.failWithRawMessage(Subject.java:381)
	at com.google.common.truth.IterableSubject.failWithBadResultsAndSuffix(IterableSubject.java:370)
	at com.google.common.truth.IterableSubject.containsExactly(IterableSubject.java:321)
	at com.google.common.truth.IterableSubject.containsExactlyElementsIn(IterableSubject.java:261)
	at com.google.gerrit.acceptance.git.VisibleRefFilterIT.assertRefs(VisibleRefFilterIT.java:364)
	at com.google.gerrit.acceptance.git.VisibleRefFilterIT.assertRefs(VisibleRefFilterIT.java:339)
	at com.google.gerrit.acceptance.git.VisibleRefFilterIT.subsetOfRefsVisibleWithAccessDatabase(VisibleRefFilterIT.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        ...

Patch-set: 24
Label: Verified=0