Update patch set 2
Patch Set 2: -Verified

Something seems still wrong in this series:
 
Steps: 
 * set notedb to read/write on changes
 * run RebuildNoteDb -> no error reported
 * run reindex -> see stacktrace below:

[2016-04-22 11:15:31,097] [Index-Batch-3] ERROR com.google.gerrit.server.index.change.AllChangesIndexer : Failed to index project Test2
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:435)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at com.google.gerrit.server.index.change.AllChangesIndexer$1.run(AllChangesIndexer.java:163)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:634)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:110)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:377)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.gerrit.server.notedb.ChangeNotes$Factory.create(ChangeNotes.java:166)
	at com.google.gerrit.server.notedb.ChangeNotes$Factory.scanNoteDb(ChangeNotes.java:347)
	at com.google.gerrit.server.notedb.ChangeNotes$Factory.scan(ChangeNotes.java:325)
	at com.google.gerrit.server.index.change.AllChangesIndexer$3.call(AllChangesIndexer.java:234)
	at com.google.gerrit.server.index.change.AllChangesIndexer$3.call(AllChangesIndexer.java:224)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	... 10 more
Reindexing changes: projects: 33% (2/6)[2016-04-22 11:15:31,138] [Index-Batch-2] ERROR com.google.gerrit.server.index.change.AllChangesIndexer : Failed to index project test
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:435)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at com.google.gerrit.server.index.change.AllChangesIndexer$1.run(AllChangesIndexer.java:163)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:634)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:110)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:377)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.gerrit.server.notedb.ChangeNotes$Factory.create(ChangeNotes.java:166)
	at com.google.gerrit.server.notedb.ChangeNotes$Factory.scanNoteDb(ChangeNotes.java:347)
	at com.google.gerrit.server.notedb.ChangeNotes$Factory.scan(ChangeNotes.java:325)
	at com.google.gerrit.server.index.change.AllChangesIndexer$3.call(AllChangesIndexer.java:234)
	at com.google.gerrit.server.index.change.AllChangesIndexer$3.call(AllChangesIndexer.java:224)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	... 10 more
Reindexing changes: projects: 50% (3/6)[2016-04-22 11:15:31,237] [Index-Batch-4] ERROR com.google.gerrit.server.index.change.AllChangesIndexer : Failed to index project NewTest
java.util.concurrent.ExecutionException: com.google.gwtorm.server.OrmException: org.eclipse.jgit.errors.ConfigInvalidException: Change 64: Missing footers: Branch, Change-id
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:435)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at com.google.gerrit.server.index.change.AllChangesIndexer$1.run(AllChangesIndexer.java:163)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:634)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:110)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:377)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gwtorm.server.OrmException: org.eclipse.jgit.errors.ConfigInvalidException: Change 64: Missing footers: Branch, Change-id
	at com.google.gerrit.server.notedb.AbstractChangeNotes.load(AbstractChangeNotes.java:134)
	at com.google.gerrit.server.notedb.ChangeNotes$Factory.create(ChangeNotes.java:172)
	at com.google.gerrit.server.notedb.ChangeNotes$Factory.scanNoteDb(ChangeNotes.java:347)
	at com.google.gerrit.server.notedb.ChangeNotes$Factory.scan(ChangeNotes.java:325)
	at com.google.gerrit.server.index.change.AllChangesIndexer$3.call(AllChangesIndexer.java:234)
	at com.google.gerrit.server.index.change.AllChangesIndexer$3.call(AllChangesIndexer.java:224)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	... 10 more
Caused by: org.eclipse.jgit.errors.ConfigInvalidException: Change 64: Missing footers: Branch, Change-id
	at com.google.gerrit.server.notedb.ChangeNotes.parseException(ChangeNotes.java:108)
	at com.google.gerrit.server.notedb.ChangeNotesParser.parseException(ChangeNotesParser.java:850)
	at com.google.gerrit.server.notedb.ChangeNotesParser.checkMandatoryFooters(ChangeNotesParser.java:821)
	at com.google.gerrit.server.notedb.ChangeNotesParser.parseAll(ChangeNotesParser.java:173)
	at com.google.gerrit.server.notedb.ChangeNotes.onLoad(ChangeNotes.java:550)
	at com.google.gerrit.server.notedb.AbstractChangeNotes.load(AbstractChangeNotes.java:131)
	... 16 more
Reindexing changes: projects: 83% (5/6), 0% (3/4501) (|)[2016-04-22 11:15:32,444] [Index-Batch-3] ERROR com.google.gerrit.server.index.change.AllChangesIndexer : Failed to index project nicos-corex
java.util.concurrent.ExecutionException: com.google.gwtorm.server.OrmException: org.eclipse.jgit.errors.ConfigInvalidException: Change 877: Missing footers: Branch, Change-id
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:435)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at com.google.gerrit.server.index.change.AllChangesIndexer$1.run(AllChangesIndexer.java:163)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:634)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:110)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:377)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gwtorm.server.OrmException: org.eclipse.jgit.errors.ConfigInvalidException: Change 877: Missing footers: Branch, Change-id
	at com.google.gerrit.server.notedb.AbstractChangeNotes.load(AbstractChangeNotes.java:134)
	at com.google.gerrit.server.notedb.ChangeNotes$Factory.create(ChangeNotes.java:172)
	at com.google.gerrit.server.notedb.ChangeNotes$Factory.scanNoteDb(ChangeNotes.java:347)
	at com.google.gerrit.server.notedb.ChangeNotes$Factory.scan(ChangeNotes.java:325)
	at com.google.gerrit.server.index.change.AllChangesIndexer$3.call(AllChangesIndexer.java:234)
	at com.google.gerrit.server.index.change.AllChangesIndexer$3.call(AllChangesIndexer.java:224)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	... 10 more
Caused by: org.eclipse.jgit.errors.ConfigInvalidException: Change 877: Missing footers: Branch, Change-id
	at com.google.gerrit.server.notedb.ChangeNotes.parseException(ChangeNotes.java:108)
	at com.google.gerrit.server.notedb.ChangeNotesParser.parseException(ChangeNotesParser.java:850)
	at com.google.gerrit.server.notedb.ChangeNotesParser.checkMandatoryFooters(ChangeNotesParser.java:821)
	at com.google.gerrit.server.notedb.ChangeNotesParser.parseAll(ChangeNotesParser.java:173)
	at com.google.gerrit.server.notedb.ChangeNotes.onLoad(ChangeNotes.java:550)
	at com.google.gerrit.server.notedb.AbstractChangeNotes.load(AbstractChangeNotes.java:131)
	... 16 more

Patch-set: 2
Reviewer: Björn Pedersen <1011624@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0