Update patch set 4
Patch Set 4: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUILD FILES...FINISHED 2.7s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/ioutil/FlipTable.java:32: error: unmappable character for encoding ASCII
 * ?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
   ^
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/ioutil/FlipTable.java:32: error: unmappable character for encoding ASCII
 * ?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
    ^
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/ioutil/FlipTable.java:32: error: unmappable character for encoding ASCII
...

Patch-set: 4
Reviewer: Diffy Cuckoo (Automated Verifier) <1012977@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1