Update patch set 2
Patch Set 2:

That's not what I see. Although based on my limited debugging thus far, there is some flakiness. All the more reason to revert the original change until we know what's going on.

 $ git rev-parse HEAD
 3f8b7a5da2e2704a552caff7588b1ea86435683f
 $ buck test --no-results-cache gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/rest/change:ActionsIT
 Using buckd.
 [-] PROCESSING BUCK FILES...FINISHED 0.1s
 [-] BUILDING...FINISHED 0.4s (325/325 JOBS)
 Log:
 TESTING //gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/rest/change:ActionsIT
 FAIL     12.2s  9 Passed   0 Skipped   1 Failed   com.google.gerrit.acceptance.rest.change.ActionsIT
 FAILURE revisionActionsTwoChangeChangesInTopic_conflicting[submitWholeTopicEnabled]: Not true that <true> is null
 java.lang.AssertionError: Not true that <true> is null
         at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:27)
         at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:23)
         at com.google.common.truth.Subject.fail(Subject.java:205)
         at com.google.common.truth.Subject.isNull(Subject.java:80)
         at com.google.gerrit.acceptance.rest.change.ActionsIT.revisionActionsTwoChangeChangesInTopic_conflicting(ActionsIT.java:99)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:606)
         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
         at com.google.gerrit.acceptance.AbstractDaemonTest$1$1.evaluate(AbstractDaemonTest.java:163)
         at org.junit.rules.RunRules.evaluate(RunRules.java:18)
         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
         at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
         at org.junit.runners.Suite.runChild(Suite.java:128)
         at org.junit.runners.Suite.runChild(Suite.java:24)
         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
         at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
         at org.junit.runners.Suite.runChild(Suite.java:128)
         at org.junit.runners.Suite.runChild(Suite.java:24)
         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
         at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
         at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
         at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
         at com.facebook.buck.junit.JUnitRunner.run(JUnitRunner.java:104)
         at com.facebook.buck.junit.BaseRunner.runAndExit(BaseRunner.java:210)
         at com.facebook.buck.junit.JUnitMain.main(JUnitMain.java:47)
 
 TESTS FAILED: 1 Failures
 Failed target: //gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/rest/change:ActionsIT
 FAIL com.google.gerrit.acceptance.rest.change.ActionsIT

Patch-set: 2