Shutdown executor for auto-commiting Lucene index when stopping Gerrit
If the executor is not shut down a reference to the Lucene index is
kept in memory. This memory leak became a problem when running the
acceptance tests, because for every test we start/stop a Gerrit
instance. This problem got worse since we are having the account
index, since the account index references the account cache which then
also stays in memory. Finally for some changes (e.g. see comments on
[1]) this resulted in tests failing with:

  java.lang.OutOfMemoryError: GC overhead limit exceeded

[1] https://gerrit-review.googlesource.com/79089

Change-Id: I9a6c2f3c73137d380585869a3a90b0d013c9cdf1
Signed-off-by: Edwin Kempin <ekempin@google.com>