Update patch set 5
Patch Set 5: Verified-1

This breaks 

FAIL    CACHED 23 Passed   0 Skipped   1 Failed   com.google.gerrit.acceptance.api.change.ChangeIT
FAILURE defaultSearchDoesNotTouchDatabase: ReviewDb is disabled for this test
java.lang.AssertionError: ReviewDb is disabled for this test
	at com.google.gerrit.acceptance.DisabledReviewDb.changes(DisabledReviewDb.java:144)
	at com.google.gerrit.server.query.change.ChangeData.reloadChange(ChangeData.java:560)
	at com.google.gerrit.server.query.change.ChangeData.change(ChangeData.java:550)
	at com.google.gerrit.server.query.change.ChangeData.changeControl(ChangeData.java:532)
	at com.google.gerrit.server.project.SubmitRuleEvaluator.<init>(SubmitRuleEvaluator.java:115)
	at com.google.gerrit.server.git.MergeSuperSet.completeChangeSetWithoutTopic(MergeSuperSet.java:104)
	at com.google.gerrit.server.git.MergeSuperSet.completeChangeSet(MergeSuperSet.java:89)
	at com.google.gerrit.server.change.Submit.submittable(Submit.java:489)
	at com.google.gerrit.server.change.ChangeJson.toChangeInfo(ChangeJson.java:390)
	at com.google.gerrit.server.change.ChangeJson.toChangeInfo(ChangeJson.java:317)
	at com.google.gerrit.server.change.ChangeJson.formatQueryResults(ChangeJson.java:296)
	at com.google.gerrit.server.query.change.QueryChanges.query0(QueryChanges.java:145)
	at com.google.gerrit.server.query.change.QueryChanges.query(QueryChanges.java:132)
	at com.google.gerrit.server.query.change.QueryChanges.apply(QueryChanges.java:99)
	at com.google.gerrit.server.api.changes.ChangesImpl.get(ChangesImpl.java:134)
	at com.google.gerrit.server.api.changes.ChangesImpl.access$000(ChangesImpl.java:46)
	at com.google.gerrit.server.api.changes.ChangesImpl$1.get(ChangesImpl.java:108)
	at com.google.gerrit.acceptance.api.change.ChangeIT.defaultSearchDoesNotTouchDatabase(ChangeIT.java:472)

Patch-set: 5
Label: Verified=-1