Fix CommentHtml.soy compilation error
Bug was introduced in change 523342.

The error that we are seeing is:
```
SoyCompilationException: errors during Soy compilation
java/com/google/gerrit/server/libserver.jar!/com/google/gerrit/server/mail/CommentHtml.soy:80:17: error: parse error at 'and': expected }, ?, ||, ??, as, instanceof, &&, ^, &, ==, !=, ===, !==, <, >, <=, >=, +, -, *, /, %, ?., ., [, ?[, (, or !
80:   {if $fromName and $change}
```

Release-Notes: skip
Change-Id: I4510b6a1b17287202000e73ce4422792d59fbb11