Escape unescaped angle brackets in javadoc
In ab11101fb2240a15cc6fdf1e31cdd675024edc7e {@code} tags got removed
from within a few javadoc <pre> tags, arguing that they are already in
a <pre> block. But <pre> on it's own does not allow unescaped use of
angle brackets, and hence javadoc building fails [1] again on Java 8.

Re-adding {@code} would be the canonical fix, as the {@code}
tag (quoting from the javadoc man page):

  Displays text in code font without interpreting the text as HTML
  markup or nested javadoc tags.

So it allows both using angle and curly brackets within {@code}.

However, as Eclipse currently chokes on braces within {@code} and
displays warnings [2], we escape the angle brackets for now to make
both eclipse and javadoc happy.

[1]

  [...]/registration/DynamicItem.java:70: error: malformed HTML
   *   DynamicSet.itemOf(binder(), new TypeLiteral<Thing<Foo>>() {});
                                                  ^
See
  http://builds.quelltextlich.at/gerrit/nightly/master-java_8/2015-06-14/extension-api-javadoc.jar.build.stderr.txt
  http://builds.quelltextlich.at/gerrit/nightly/master-java_8/2015-06-14/index.html#extension-api-javadoc.jar

[2] See the corresponding Eclipse bugs:
  https://bugs.eclipse.org/bugs/show_bug.cgi?id=258706
  https://bugs.eclipse.org/bugs/show_bug.cgi?id=206345

Change-Id: I39b2cfd06cbc5bd5d6a46dd567ac1abf21f09ee8