Update patch set 3
Patch Set 3: Code-Review-1 Verified-1

Acceptance tests don't compile with buck:

 gerrit/gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/rest/change/SubmitByFastForwardIT.java:58: error: cannot find symbol
     ActionsIT.approve(adminSession, change2.getChangeId());
     ^
   symbol:   variable ActionsIT
   location: class com.google.gerrit.acceptance.rest.change.SubmitByFastForwardIT

and

 gerrit-acceptance-tests/src/test/java/com/google/gerrit/acceptance/rest/change/BUCK (:SubmitByFastForwardIT) is missing deps:
     ':ActionsIT',


In [1] it might have been better to factor those utility methods out into the superclass rather than making them static in ActionsIT.

[1] https://gerrit-review.googlesource.com/#/c/66341/1

Patch-set: 3
Label: Code-Review=-1
Label: Verified=-1