Update patch set 2
Patch Set 2: Verified-1

Fails with internal server error when passing invalid json content in.

 $ echo "INVALID" | ssh -p 29418 david.pursehouse@localhost gerrit review 56f657ceea362b168efe6a245b6b4ad442fda31a --message "Message" --json
 
 fatal: internal server error while approving 125,1
 one or more approvals failed; review output above

From the log:

 [2014-07-09 12:19:31,871] ERROR com.google.gerrit.sshd.commands.ReviewCommand : internal error while approving 125,1
 com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 4
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:180)
        at com.google.gson.Gson.fromJson(Gson.java:755)
        at com.google.gson.Gson.fromJson(Gson.java:721)
        at com.google.gson.Gson.fromJson(Gson.java:670)
        at com.google.gson.Gson.fromJson(Gson.java:642)
        at com.google.gerrit.sshd.commands.ReviewCommand.reviewFromJson(ReviewCommand.java:213)
        at com.google.gerrit.sshd.commands.ReviewCommand.run(ReviewCommand.java:178)
        at com.google.gerrit.sshd.SshCommand$1.run(SshCommand.java:35)
        at com.google.gerrit.sshd.BaseCommand$TaskThunk.run(BaseCommand.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:368)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
 Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 4
        at com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:168)
        ... 16 more

Patch-set: 2
Label: Verified=-1