Allow load labels to cross package boundaries by default
With bazel 0.25.0 the option
  --incompatible_disallow_load_labels_to_cross_package_boundaries
is by default set to true. Due to this change in bazel the method of
including multiple custom plugins with external dependencies as
described in `./Documentation/dev-build-plugins.txt` failed. In this
case bazel failed to build with an error:

  ERROR: Failed to load Starlark extension
  '//plugins:%PLUGIN%/external_plugin_deps.bzl'. It usually happens
  when the repository is not defined prior to being used. This could
  either mean you have to add the '' repository with a statement like
  `http_archive` in your WORKSPACE file (note that transitive
  dependencies are not added automatically), or the repository '' was
  defined too late in your WORKSPACE file.

  ERROR: cycles detected during target parsing

This change disables this option by default for Gerrit-builds by adding
the respective entry to the .bazelrc-file. This is meant as a temporary
workaround to allow to continue using load-statements to load plugin's
external_plugin_deps.bzl contents as before.

Bug: Issue 10924
Change-Id: I339c4890031216ff08a5d1d45621a9002dd8da43