Update patch set 8
Patch Set 8:

Also 

chrome 56                Tests passed
Test run ended in failure: Error thrown outside of test function: Attempted to wrap getConfig which is already wrapped
  checkWrappedMethod at /components/sinonjs/sinon.js:1326
          wrapMethod at /components/sinonjs/sinon.js:1366
           <unknown> at gr-reply-dialog_test.html:54
          wrapMethod at /components/sinonjs/sinon.js:1385
           <unknown> at gr-reply-dialog_test.html:54

chrome 56 (1578/0/0)
safari 10.0.3 (479/0/1 error)

Error: Error thrown outside of test function: Attempted to wrap getConfig which is already wrapped
  checkWrappedMethod at /components/sinonjs/sinon.js:1326
          wrapMethod at /components/sinonjs/sinon.js:1366
           <unknown> at gr-reply-dialog_test.html:54
          wrapMethod at /components/sinonjs/sinon.js:1385
           <unknown> at gr-reply-dialog_test.html:54

Patch-set: 8
Reviewer: Paladox none <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>