Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> The newly added test seems to be flaky.
> 
> 
> See https://gerrit-ci.gerritforge.com/job/Gerrit-verifier-bazel/72280/consoleText

I don't think this is flakyness of the new tests.
The failure is caused by a timeout [1], and at the same test run also other tests failed due to the same issue. So I think this issue is unrelated to the new tests, but rather a general issue that might occur on push in tests.

[1] com.google.gerrit.acceptance.git.HttpPushForReviewIT_cannotPushTheSameCommitTwiceForReviewToTheSameBranchCreateNewChangeForAllNotInTarget_project
java.util.concurrent.ExecutionException: (timeout 256ms, cancelled)
	at com.google.gerrit.server.git.MultiProgressMonitor.waitFor(MultiProgressMonitor.java:247)
	at com.google.gerrit.server.git.receive.AsyncReceiveCommits.onPreReceive(AsyncReceiveCommits.java:363)
	at org.eclipse.jgit.transport.ReceivePack.service(ReceivePack.java:388)
	at org.eclipse.jgit.transport.ReceivePack.receive(ReceivePack.java:327)
	at org.eclipse.jgit.http.server.ReceivePackServlet.doPost(ReceivePackServlet.java:185)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	...
Caused by: java.util.concurrent.CancellationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.google.gerrit.server.git.WorkQueue$Task.get(WorkQueue.java:583)
	at com.google.gerrit.server.git.MultiProgressMonitor.waitFor(MultiProgressMonitor.java:243)
	... 67 more

Patch-set: 2