Update patch set 3
Patch Set 3:

It appears this change breaks installing a local gerrit.

bbadour@lark:~/android/g/gerrit$ $(bazel info output_base)/external/local_jdk/bin/java \
>         -jar bazel-bin/gerrit.war init -d ../gerrit_testsite
INFO: Invocation ID: 7ccf0717-6817-464a-bb25-0e4ee2dfd0ea
Using secure store: com.google.gerrit.server.securestore.DefaultSecureStore
[2019-05-23 11:49:57,108] [main] INFO  com.google.gerrit.server.config.GerritServerConfigProvider : No /usr/local/google/home/bbadour/android/g/gerrit/../gerrit_testsite/etc/gerrit.config; assuming defaults

*** Gerrit Code Review 3.0.0-424-g0903cb9f30
*** 

Create '/usr/local/google/home/bbadour/android/g/gerrit/../gerrit_testsite' [Y/n]? 

*** Git Repositories
*** 

Location of Git repositories   [git]: 

*** Index
*** 

Type                           [LUCENE]: 
error: 'LUCENE' is not a valid choice
       Supported options are:
         lucene
         elasticsearch
Type                           [LUCENE]: lucene
error: 'lucene' is not a valid choice
       Supported options are:
         lucene
         elasticsearch
Type                           [LUCENE]: elasticsearch
error: 'elasticsearch' is not a valid choice
       Supported options are:
         lucene
         elasticsearch
Type                           [LUCENE]:

Patch-set: 3
CC: Gerrit User 1073305 <1073305@173816e5-2b9a-37c3-8a2e-48639d4f1153>