Update patch set 5
Patch Set 5:

FYI this breaks ./tools/eclipse/project.py:

 .../gerrit/plugins/cookbook-plugin/src/main/java/com/googlesource/gerrit/plugins/cookbook/client/CookBookPlugin.java:17: error: package com.google.gerrit.plugin.client does not exist
 import com.google.gerrit.plugin.client.Plugin;

Patch-set: 5
Reviewer: Dave Borowitz <1010008@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0