Update patch set 2
Patch Set 2:

> Patch Set 1: Verified-1
> 
> Gerrit-CI Build: https://gerrit-ci.gerritforge.com/job/Gerrit-verifier-change/6487/console

 noteDbUsesOriginalSubjectFromPatchSetAndIgnoresChangeField(com.google.gerrit.acceptance.server.notedb.ChangeRebuilderIT)
 java.lang.AssertionError: Differences between ReviewDb and NoteDb for Change{34 (I8e891ef253ee3b2cb237be7b5662c6ec482b04c8), dest=com.google.gerrit.acceptance.server.notedb.ChangeRebuilderIT_noteDbUsesOriginalSubjectFromPatchSetAndIgnoresChangeField_project,refs/heads/master, status=M}:
 postSubmit differs for PatchSetApproval.Key 34%2C2,1000000,SUBM: {false} != {true}

This is a separate problem, and it's the same problem that causes very many tests to fail with GERRIT_NOTEDB=CHECK. I'm working on that one next.

The proximate cause for this is that the test method pushed to refs/heads/master instead of refs/for/master, so it resulted in merging the change. That behavior is not part of that test method, so I just fixed it here.

It's not immediately obvious why that method didn't fail before making this change, but I do know that the issue with SUBM is around ordering and grouping of events during rebuilding. This change slightly tweaks event ordering as well so it's not too surprising for it to cause this brittle failure.

Patch-set: 2
Reviewer: Dave Borowitz <1010008@173816e5-2b9a-37c3-8a2e-48639d4f1153>