Update patch set 1
Patch Set 1:

This breaks running gerrit daemon for me, both from a war and from Eclipse. All I get is:

 Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"

Stepping into the debugger I see there's something wrong with the logging code, and the actual NCDFE is:

 java.lang.NoClassDefFoundError: com/google/gerrit/server/config/ConfigSection
 	at com.google.gerrit.server.schema.DataSourceProvider.open(DataSourceProvider.java:95)
 	at com.google.gerrit.server.schema.DataSourceProvider.get(DataSourceProvider.java:69)
 	at com.google.gerrit.pgm.util.SiteLibraryBasedDataSourceProvider.get(SiteLibraryBasedDataSourceProvider.java:53)
 	at com.google.gerrit.server.schema.DataSourceProvider.get(DataSourceProvider.java:1)
 	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
 	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:73)
 	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:66)
 	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:63)
 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1058)
 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
 	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
 	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
 	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1051)
 	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
 	at com.google.inject.Guice.createInjector(Guice.java:96)
 	at com.google.gerrit.pgm.util.SiteProgram.createDbInjector(SiteProgram.java:146)
 	at com.google.gerrit.pgm.Daemon.start(Daemon.java:271)
 	at com.google.gerrit.pgm.Daemon.run(Daemon.java:200)
 	at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:63)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:606)
 	at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:167)
 	at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:94)
 	at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:51)
 	at Main.main(Main.java:25)
 Caused by: java.lang.ClassNotFoundException: com.google.gerrit.server.config.ConfigSection
 	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
 	at java.security.AccessController.doPrivileged(Native Method)
 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:427)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:360)
 	... 32 more

Patch-set: 1
Reviewer: Dave Borowitz <1010008@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=0