Update patch set 33
Patch Set 33: Verified-1

Patchset merges but does not build.
The following snippet of output may point you in the right direction:

  Not using buckd because watchman isn't installed.
[-] PARSING BUCK FILES...FINISHED 4.2s
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/config/GerritTopMenus.java:23: error: cannot find symbol
import com.google.gerrit.extensions.webui.GerritTopMenu;
                                         ^
  symbol:   class GerritTopMenu
  location: package com.google.gerrit.extensions.webui
/home/deckard/workspace/gerrit/gerrit-server/src/main/java/com/google/gerrit/server/config/GerritTopMenus.java:196: error: cannot find symbol
  private MenuEntry menu(GerritTopMenu gerritMenu, MenuItem... items) {
...

Patch-set: 33
Label: Verified=-1