Update patch set 1
Patch Set 1: Verified-1

java/com/google/gerrit/httpd/DirectChangeByCommit.java:55: error: method toGerrit in class UrlModule cannot be applied to given types;
    UrlModule.toGerrit(token, req, rsp);
             ^
  required: boolean,String,HttpServletRequest,HttpServletResponse
  found: String,HttpServletRequest,HttpServletResponse
  reason: actual and formal argument lists differ in length

Patch-set: 1
Reviewer: Gerrit User 1010516 <1010516@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1