Update patch set 7
Patch Set 7:

> Patch Set 7: Code-Review-1
> 
> building this with bazel 1.0.0rc2 succeeds though running the tests fails with the following error:
> 
> $ bazel test //... --test_tag_filters=-docker
> INFO: Writing tracer profile to '/private/var/tmp/_bazel_d029788/7bad2a2008c0528ccb0e391a73771531/command.profile.gz'
> INFO: Invocation ID: db35ea07-76e8-4d0d-95d1-636f859234f5
> ERROR: /Users/d029788/src/git/gerrit/plugins/codemirror-editor/BUILD:2:1: file '//tools/bzl:js.bzl' does not contain symbol 'bundle_assets'
> ERROR: /Users/d029788/src/git/gerrit/plugins/codemirror-editor/BUILD:28:1: name 'bundle_assets' is not defined

Thanks for trying to verify this change.

What branch are you building? This change was uploaded to stable-2.14, but your build breakage is from codemirror-editor plugin. Note, that this plugin was only added on stable-2.16 branch. Can it be, that your submodules in gerrit tree are from different branches (not from stable-2.14)?

Patch-set: 7
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>